### ISSUE TITLE
[Feature]: Check your internet bar is present even in full screen

### ISSUE THREAD

**Issue by lwjc02** [movie-web/movie-web#1003]
### What feature do you want to add?

Would like to change the check your internet feature to not invade the source when in full screen.

### Why do you want to have this feature?

As it is ruining the experience of the user and prevents the use of the website.

**Comment by TheScreechingBagel** [comment]
this has been added in a new version, but you're using an outdated cached version. movie-web.app has been taken down, switch to an updated community instance:
https://movie-web.github.io/docs/instances
