### ISSUE TITLE
Add v-cloud server that works with tmdb

### ISSUE THREAD

**Issue by Mrunknow3** [movie-web/movie-web#1005]
### What feature do you want to add?

Vega movie website have v-cloud servers

### Why do you want to have this feature?

Server request

**Comment by JorrinKievit** [comment]
Those sites offer files in mkv format, which cant be played in the browser

**Comment by amamadman** [comment]
Even though they don't fully support mkv, browsers still play it if you set the video type to mp4.Also how does vegamovie work tmdb? Is there a api?

**Comment by JorrinKievit** [comment]
I tested files served from vegamovies, they didnt play in the browser. And for your question, you can scrape by movie title and release year

**Comment by Mrunknow3** [comment]
> I tested files served from vegamovies, they didnt play in the browser. And for your question, you can scrape by movie title and release year

Understood, but any hindi good source you can add then

**Comment by quote-therizzler** [comment]
movie-web is currently focusing on english, you can find some hindi streaming sites here:
https://fmhy.pages.dev/non-english#streaming-10
