### ISSUE TITLE
[Feature]: Report Button on videos

### ISSUE THREAD

**Issue by ninonook1** [movie-web/movie-web#1009]
### What feature do you want to add?

ive tend to notice that some videos i watch do not connect to the right ones, and i feel as though it would be a bit redundant to report each one here. And I feel it would be more useful to have a report-like button on videos to notify you when it does not show the correct video.

### Why do you want to have this feature?

it would be a lot more convenient for both the viewer and the manager to report and fix on incorrect videos, it would also mean a much more reliable watching experience instead of searching for the correct one.

**Comment by TheScreechingBagel** [comment]
just to make sure, are you using a community instance? (or self-hosted)
https://movie-web.github.io/docs/instances

**Comment by lonelil** [comment]
movie-web doesn’t host any content, it only links to it, movie-web can’t “fix” the video.
