### ISSUE TITLE
[Bug]: Movie web's Chinese traditional variant is using Chinese simplified variant characters.

### ISSUE THREAD

**Issue by superlincoln953** [movie-web/movie-web#1016]
### What happened?

When you are using Chinese traditional variant, the site will use and show you Chinese simplified variant characters.
Using Chinese traditional
![Screenshot 2024-03-15 at 11-08-36 设置 - movie-web](https://github.com/movie-web/movie-web/assets/115524074/4c205777-fd20-4fac-9611-d47eec23ff4f)
Using Chinese simplified
![Screenshot 2024-03-15 at 11-09-00 设置 - movie-web](https://github.com/movie-web/movie-web/assets/115524074/d0042405-e7c5-4293-9f80-d15a042457e0)

### What browsers are you seeing the problem on?

Firefox

### Steps to reproduce?

1. Use Chinese traditional in movie web
2. Use Chinese simplified in movie web
3. compare the two and see no difference

**Comment by binaryoverload** [comment]
I've managed to reproduce this issue. It's likely something to do with how we handle language codes
