### ISSUE TITLE
[Feature]: Scroll click on back to home

### ISSUE THREAD

**Issue by russssl** [movie-web/movie-web#1018]
### What feature do you want to add?

![image](https://github.com/movie-web/movie-web/assets/70024944/9e142163-7b48-4827-ac00-fd1a2bb61a42)
scroll lock in "back to home would open home in the new tab

### Why do you want to have this feature?

it would be very convenient to have such feature

**Comment by JipFr** [comment]
What?

**Comment by russssl** [comment]
> What?

scroll click on the link opens it in the new tab.

**Comment by binaryoverload** [comment]
He means the middle click to open a new tab, which only works for links. We could technically implement it, but I would question _why_ - just open a new tab

**Comment by russssl** [comment]
> He means the middle click to open a new tab, which only works for links. We could technically implement it, but I would question _why_ - just open a new tab

Yes, this is what I mean. Dunno, thought like it would be nice to have it, I do implement scroll clicks in my apps where it is possible so for me it is just natural thing to  have

**Comment by quote-therizzler** [comment]
i would use this, tried to middle click on it too a few times lol

**Comment by russssl** [comment]
If the devs will agree I could implement it

**Comment by Ciarands** [comment]
Ive also done this a few times, would be a nice QoL feature

**Comment by JorrinKievit** [comment]
> If the devs will agree I could implement it

Sure go ahead 😄

**Comment by JorrinKievit** [comment]
Yep!
