### ISSUE TITLE
Red bar at the top of the website keeps showing an exclamation mark followed by ''Check your internet connection''

### ISSUE THREAD

**Issue by GeekCanada** [movie-web/movie-web#1020]
### What happened?

No matter what I watch, this red bar appears at the top of the website and it's very annoying considering the fact that every single movie that I watch works flawlessly with zero buffering or loading time. 

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

I did an internet test to see if the issue was my internet and my speed it phenomenal so I don't understand the problem.

**Comment by JorrinKievit** [comment]
Check pinned issue
