### ISSUE TITLE
[Feature]: Enable extension detection on supported web browsers on iOS like Orion browser

### ISSUE THREAD

**Issue by cooldude-91** [movie-web/movie-web#1022]
### What feature do you want to add?

Orion browser on iOS allows you to use Chrome and Firefox desktop extensions, even movie-web extension can be installed from chrome store on iOS.

### Why do you want to have this feature?

But there is a check in movie-web application code where it detects that if it is an iOS device it disables the extension feature all together. It should allow the user to use installed extension.

**Comment by binaryoverload** [comment]
Hi there,

We would love to be able to enable this, but with some testing, we cannot get the extension to work on the iOS Orion browser
