### ISSUE TITLE
[Feature]: Disable broken sources and re-order rankings

### ISSUE THREAD

**Issue by Ciarands** [movie-web/movie-web#1026]
### What feature do you want to add?

As the title states, broken sources should be disabled until they're fixed and rankings should be evaluated and re-ordered based on some reasonable metric, a more critical lens on these elements would improve the project.

I'd like to add some documentation for how sources should be ranked based on what qualities we look for and modify the parameters of existing sources to disable the broken ones.

### Why do you want to have this feature?

The current ranking of a lot of the sources don't make any sense, a source like "Goojara" which to my knowledge has never worked shouldn't have been ranked so highly as it doesn't seem that great as-is (any source that uses doodstream as a primary embed is questionable).

It would also be nice to make use of the `disabled` parameter in the providers lib more frequently, it feels silly to not make use of this when the resulting consequence leads to an overall worse experience for the end user.

**Comment by JorrinKievit** [comment]
You wanna do it @Ciarands ?

**Comment by Ciarands** [comment]
yeah im happy to

**Comment by amamadman** [comment]
> Maybe if we can have the option to prioritise sources on global level by drag and drop? Because for me VidSrcTo VidPlay is the fastest and most clear one but showbox appears first.

For that, in providers.runAll() you can specify the order like this, sourceOrder: [ "vidsrcto", "showbox", "goojara" ]. And the rest of the sources will run after these in the order from ranks. So maybe you could make the system in the frontend where the user can set the order of the sources simply by dragging them. But if you want to change the order in the providers package it self the you'll have to change the ranks for every provider.

**Comment by amamadman** [comment]
Also in my observation, only showbox, vidsrcto, primewire(after it gets added), hdrezka, goojara, vidsrc and ridoomovies work properly. The other sources partially work, like for gomovies, zoechip, flixhq everything works but the embeds are dead, for nepu the search is broken, streambucket and dood have captcha issues. And like remotestram was total dogshit and smashysteam doesn't work either
