### ISSUE TITLE
[Bug]: [object object] error details

### ISSUE THREAD

**Issue by MattEzekiel** [movie-web/movie-web#1031]
### What happened?

Trying to search for "Quiet on Set" display an error and when clicking on "show details" it shows this:
![image](https://github.com/movie-web/movie-web/assets/50919956/66a3f2cb-15f8-4c0a-ab2e-64cce114c9cd)

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

1. Search for quiet on set
2. Expect an error
3. Click on show details

**Comment by JorrinKievit** [comment]
These are simply errors from providers because it can't find the show. So this is not really a bug on our side, but the provider simply doesn't have the content. There are extension only sources that do have this show though.
