### ISSUE TITLE
[Bug]: Kiwi Browser can install extension but can't accept permissions

### ISSUE THREAD

**Issue by Ivan951236** [movie-web/movie-web#1034]
### What happened?

What did I expect:
The extension should work with any browsers with addon support built on chrominum
What happened instead:
The web browser has trouble with accepting permissions with other instances

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

1. Do Onboarding
2. Do the extension setup
3. If haven't already then install the extension (chrome version)
4. Try to accept the permissions

### Other relevant information

Web Browser: Kiwi Browser on Android 12
Web Browser Version according to settings page (Major):124
Extensions Installed: Nothing but movie-web extension
Begging: Please I really don't want to switch to firefox because of media suttering
Mobile Device Model: Samsung Galaxy A11 (SM-A115F)

**Comment by binaryoverload** [comment]
Not sure how we can approach this, as the reason it doesn't work is that the redirect isn't set on the extension grant page due to the Kiwi browser opening the popout in a completely separate tab

**Comment by Benlee1129** [comment]
Unfortunately, the newest version of the extension doesn't work in kiwi browser. I used the old one of v.1.0.3 and movie-web is able to be granted the permission.

**Comment by Ivan951236** [comment]
> Unfortunately, the newest version of the extension doesn't work in kiwi browser. I used the old one of v.1.0.3 and movie-web is able to be granted the permission.

I also tried v.1.0.3 as well, For me still couldn't accept permission tho

**Comment by jessedegans** [comment]
This is a known issue with Kiwi, it seems to be reported in 2019 but Kiwi is not keen on fixing it anytime soon: https://github.com/kiwibrowser/android/issues/78

**Comment by binaryoverload** [comment]
Thanks for pointing us towards the issue

**Comment by jessedegans** [comment]
@binaryoverload 
It seems there might be an issue with Kiwi browser's permission API. Some projects have attempted to "fix" this by creating a special build for kiwi that includes all required permissions in the manifest, bypassing the broken prompt.

To my understanding from what I read on this repo, movie-web follows the principle of least privilege, but this could be a potential solution to explore. Or perhaps a better approach would be to wait for their developers. What are your thoughts on this?

**Comment by binaryoverload** [comment]
@jessedegans I don't really have any interest in making special builds specifically for Kiwi - we'll wait for Kiwi to fix their APIs
