### ISSUE TITLE
[Bug]: movie-web.app is not accessible through Google Chrome but runs perfectly fine on Microsoft Edge

### ISSUE THREAD

**Issue by zaid-ahmad** [movie-web/movie-web#1035]
### What happened?

I recently switched browsers from Edge to Chrome and when I tried opening the website through Chrome, I get "This site can't be reached" message.

When I tried doing the same on Edge, the website loads perfectly but since I made the switch, I installed the PWA version and that too, works fine.

I prefer the website, however so hopefully it gets fixed soon.

### What browsers are you seeing the problem on?

Google Chrome Version 123.0.6312.59 (Official Build) (64-bit)

**Comment by binaryoverload** [comment]
See the pinned issue #936
