### ISSUE TITLE
[Feature]: How to update movie-web instance automatically?

### ISSUE THREAD

**Issue by itsmeadarsh2008** [movie-web/movie-web#1036]
### What feature do you want to add?

Just like in Vercel or Netlify, we have a feature (automatic deployment of latest commit)

### Why do you want to have this feature?

It's hard to manually update by deleting projects from Vercel and GitHub. 

### Any other details to share?

Any other way to customize the installation to achieve this?

**Comment by lonelil** [comment]
fork movie-web instead of cloning, then click sync fork to update.
