### ISSUE TITLE
[Feature]: Handle multiple languages

### ISSUE THREAD

**Issue by nduboi** [movie-web/movie-web#1037]
### What feature do you want to add?

A new button where we can choose the language of the film, it's was a feature from the old version of the app

### Why do you want to have this feature?

I want to choose the language

**Comment by JipFr** [comment]
We don't know which language the videos we get are in, so we can't provide a setting for it. This was also never in the app.

**Comment by nduboi** [comment]
I remembered that in V3.2.3 we could change languages!

**Comment by nduboi** [comment]
I'm sure I'm wrong!

**Comment by erynith** [comment]
> I remembered that in V3.2.3 we could change languages!

you are confusing subtitles for languages
