### ISSUE TITLE
[Feature]: Play with external media player option

### ISSUE THREAD

**Issue by vijayvcm** [movie-web/movie-web#1039]
### What feature do you want to add?

An additional setting/option to play with external media players.

It would be better if we have an additional option to play with external media players just below the download option (It could be anywhere else).

![IMG_8193](https://github.com/movie-web/movie-web/assets/11239522/19f0ae18-6b89-4784-9acc-cd699f57de60)

### Why do you want to have this feature?

Most of the time I (probably others as well) don’t play videos with default browser provided media player. I prefer to play videos with external media players since they provide lot of options to customise and browsers dont have many options to adjust the settings.

### Any other details to share?

Many media players such as VLC, Infuse, etc provide an option to play with their media players via callback urls. 

(e.g)

vlc-x-callback://x-callback-url/stream?url=http://example.com/dogs.mp4&sub=https://example.com/dogs.srt

https://support.firecore.com/hc/en-us/articles/215090997-API-for-Third-Party-Apps-Services

**Comment by binaryoverload** [comment]
Out of scope, if you wish to use a different player you can either download the video if it's an MP4 video, or use the HLS link to play the video directly
