### ISSUE TITLE
Implement MW 

### ISSUE THREAD

**Issue by mosesman831** [movie-web/movie-web#1040]
Will it be possible to implement mw-extension into a hosted MW site? Without the extension it will be lot easier to control.

**Comment by binaryoverload** [comment]
The extension exists out of necessity, we wouldn't use it if we didn't need it

**Comment by mosesman831** [comment]
Because I am working on a LIVE TV stream and it has to use MOVIE-WEB extension or else it will not load on PlayerJS.

**Comment by mosesman831** [comment]
@binaryoverload Do you have any good ways to implement this for my LIVETV stream? I want to use it anywhere but the extension is really pulling me down.

**Comment by binaryoverload** [comment]
Live TV is not supported by movie-web, this is out of scope
