### ISSUE TITLE
[Bug]: Extension Too Old

### ISSUE THREAD

**Issue by GhostGamr** [movie-web/movie-web#1043]
### What happened?

![image](https://github.com/movie-web/movie-web/assets/89459341/346a73b1-8542-4f84-860c-f0cb72f30802)
![image](https://github.com/movie-web/movie-web/assets/89459341/297737fb-e006-406f-9e6d-d9521f629543)

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Other relevant information

The browser I use is Opera version: 108.0.5067.40 
I hv recently reinstalled the extension but still see the problem. Can you please help me with this?
Extension Version: 1.1.3

**Comment by GhostGamr** [comment]
Addition: I have deleted the cookies to freshly see the website but now the website dosent load at all and shows failed to connect.
![image](https://github.com/movie-web/movie-web/assets/89459341/000b7447-0e01-4439-9fc0-6b776ca63fc7)

**Comment by JorrinKievit** [comment]
Check pinned issue
