### ISSUE TITLE
[Bug]: "check your internet connection" always displayed

### ISSUE THREAD

**Issue by jdriez** [movie-web/movie-web#1046]
### What happened?

the "check your internet connection" pannel is always displayed shen watching a video despite the internet connection being fine and the video playing as normal

### Steps to reproduce?

launch a video
<img width="1440" alt="image" src="https://github.com/movie-web/movie-web/assets/132510528/4a5d89e9-833a-4961-8901-8f946e6b7eff">

**Comment by JipFr** [comment]
Please check the pinned issue https://github.com/movie-web/movie-web/issues/936
