### ISSUE TITLE
[Feature] - Show a "Next Season" button when at the end of a TV season

### ISSUE THREAD

**Issue by sussy-code** [movie-web/movie-web#1049]
### What happened?

when at the last episode in the season, even if there is another season there is no NextEpisodeButton because of his the nextEp var is set

### What browsers are you seeing the problem on?

Microsoft Edge

### Steps to reproduce?

1. go to a show and click on it
2. go to the last episode of the season
3. fast forward to ~10 seconds before episode depletion 
4. don’t see a button for the next episode even if there’s another season

**Comment by blikje7up** [comment]
I would like to see an "Next season" button. Most of the time there is a large pause in the timeline of the show, that way there is a clear distinction between new episode's and a new season.

**Comment by binaryoverload** [comment]
> I would like to see an "Next season" button. Most of the time there is a large pause in the timeline of the show, that way there is a clear distinction between new episode's and a new season.

I agree with this - approving :)

**Comment by dro-1** [comment]
Hello  @binaryoverload , 
I just found out about this project and I'll love to contribute to it.

 I'm a React Developer but this would be my first time contributing to an open source project of this magnitude. I'll like to take on this issue but the only thing I'll need from you is to please point me in the right direction in terms of files in the project I should look at to get up to speed in little to no time.

Thanks.

**Comment by binaryoverload** [comment]
@dro-1 happy to assign you to this issue

The file you'd be wanting to look at is the next episode button, which I've linked below. This component can be modified to show next season when at the end of the season

https://github.com/movie-web/movie-web/blob/dev/src/components/player/atoms/NextEpisodeButton.tsx

**Comment by dro-1** [comment]
I also run into this error "Failed to verify your humanity. Please try again." when I try to watch movies. I don't know if it's a fault from my end.

**Comment by levrx** [comment]
> I also run into this error "Failed to verify your humanity. Please try again." when I try to watch movies. I don't know if it's a fault from my end.

It was my adblocker extension that made this show, just to let you know.

**Comment by dro-1** [comment]
> > I also run into this error "Failed to verify your humanity. Please try again." when I try to watch movies. I don't know if it's a fault from my end.
> 
> It was my adblocker extension that made this show, just to let you know. Try disabling it.

Thanks a lot. 
@binaryoverload I've finally figured it out and created a PR for the fix #1098. 
Looking forward to your review.
