### ISSUE TITLE
[Feature]: return embeds

### ISSUE THREAD

**Issue by erynith** [movie-web/movie-web#1059]
### What feature do you want to add?

hear me out

what if the providers package also returned the embeds alongside the scraped result

### Why do you want to have this feature?

what if someone wants to use the embeds

"but why?" idk ask them not me

**Comment by binaryoverload** [comment]
We already return embeds for sources that support it when running [`runSourceScraper`](https://movie-web.github.io/providers/api-reference/providercontrolsrunsourcescraper)

**Comment by erynith** [comment]
my fault g
