### ISSUE TITLE
[Bug]: Thai subtitles issue 

### ISSUE THREAD

**Issue by loganrg8752** [movie-web/movie-web#1066]
### What happened?

When using Thai subtitles on any movie, they appear as complete gibberish as if their format isn’t supported by movie-web. This issue is present with self uploaded subtitles on any movie.

### Steps to reproduce?

Download any Thai subtitles from a source like opensubtitles and plug them into movie-web.

**Comment by zisra** [comment]
You probably don't have the correct fonts downloaded. What device/browser/OS are you on?

Cannot reproduce, here's where I got my file: https://www.opensubtitles.com/en/subtitles/the-simpsons-movie-2007-eng-axxo-en
<img width="398" alt="Screenshot 2024-03-30 at 11 07 37 PM" src="https://github.com/movie-web/movie-web/assets/100528712/59f82cce-d31f-4630-847e-2bce975fc341">

**Comment by loganrg8752** [comment]
That’s strange, I’m on macOS and using google chrome. My default system language is already in Thai, assumed I’d already have the font. But, I’ll double check and see if I can get it worked out.
