### ISSUE TITLE
[Feature]: new providers 

### ISSUE THREAD

**Issue by jpants36** [movie-web/movie-web#1069]
### What feature do you want to add?

Couple of new providers 

V-Cloud (https://v-cloud.bio)
PlayM4U (https://play.playm4u.xyz)
Streamruby (https://streamruby.com)
FileLions (https://filelions.to)

### Why do you want to have this feature?

V-Cloud offers decent 4k and 1080p streams, like Showbox.

The others provide general 1080p streams.

**Comment by lonelil** [comment]
These are just embeds, not streaming sites?

**Comment by ztpn** [comment]
I've code for filelions scraper, do I PR? It's not that great plus it's only returned by primewire, so I don't think it matters. And I think someone was working on m4u source

**Comment by zisra** [comment]
Sure you can add it to primewire @ztpn
