### ISSUE TITLE
[Feature]: Store custom subtitles.

### ISSUE THREAD

**Issue by Sir0ne** [movie-web/movie-web#1075]
### What feature do you want to add?

Store subtitles previously added to a show and store it on the server.

### Why do you want to have this feature?

So people can add subtitles to shows for everyone to use or just switching devices.

### Any other details to share?

It would also be nice to mass add subtitles to a show instead of one by one.
I'm sure this won't be needed after the major update, but it would be nice to have for more obscure shows that may not have a sub.
Having a whitelist option would be needed, subtitles can be unsafe.

**Comment by JorrinKievit** [comment]
Out of scope. We do not want to store any content on servers except for account details.
