### ISSUE TITLE
[Bug]: ads on showbox

### ISSUE THREAD

**Issue by Preston-Riley** [movie-web/movie-web#1084]
### What happened?

on showbox there is ads

### Steps to reproduce?

watch a newer movie on showbox.

**Comment by zisra** [comment]
Which movie?

**Comment by Preston-Riley** [comment]
ghostbusters frozen empire

**Comment by TheScreechingBagel** [comment]
it’s a camrip what do you expect lmao

**Comment by Preston-Riley** [comment]
can i disable camrip?

**Comment by TheScreechingBagel** [comment]
no, cam rip just means it’s been recorded with a camera there is nothing to “disable”

that movie is not yet out digitally
