### ISSUE TITLE
[Bug]: Subtitles do not appear in fullscreen mode in some movies/shows

### ISSUE THREAD

**Issue by ShivaSingh361** [movie-web/movie-web#1087]
### What happened?

Subtitles don't seem to appear during fullscreen mode in the browser, in some movies, ex: Cars 2006, Cars 2, etc. When the movie-ui disappears, subtitles disappear along with it too. Please look into this issue. Thank you.

### What browsers are you seeing the problem on?

Chrome

**Comment by JipFr** [comment]
What device are you trying this on? If it's on an iPhone, that's just a restriction of the fullscreen API. There's nothing we can do about it if you're on iOS

**Comment by binaryoverload** [comment]
Closing as stale
