### ISSUE TITLE
[Bug]: Showbox and VidSrcTo Content Sdraping Error

### ISSUE THREAD

**Issue by antoniodni** [movie-web/movie-web#1104]
### What happened?

So, for about the past week (sorry it took so long to report, I figured it would get fixed but it appears I’m the only one having this issue :)) when content scraping, Showbox and VidSrcTo have had an error occur. It occurs on all movies and shows. (Multiple attempts linked below.)

https://github.com/movie-web/movie-web/assets/156142166/57a8d03f-b333-4aa7-892f-e89038188d35

### What browsers are you seeing the problem on?

Chrome

### Other relevant information

I use Chrome on an iPad, so could that be a part of the issue? (I imagine not, but it’s still worth a shot I guess.) I don’t have a browser extension, but I’ve tried with and without a NetLify proxy and with and without a VPN. I still get the same results.

**Comment by TheScreechingBagel** [comment]
i think you’re using an old version; what instance is this on? try a community instance

**Comment by TheScreechingBagel** [comment]
brw showbox isnt working anymore and vidsrcto is extension only

but you’re still on an old version pretty sure
