### ISSUE TITLE
[Feature]: Provide ability to use alternate TMDB api incase of failure using the default api

### ISSUE THREAD

**Issue by meghrathod** [movie-web/movie-web#1107]
### What feature do you want to add?

If the search fails through the main TMDB API endpoint, then we can try having the search redirect to the alternate endpoint, or we can have an optional environment variable that can be used to manage these endpoints that the self-hoster can change as per their target audience. 

### Why do you want to have this feature?

In India and maybe elsewhere, major internet providers like Jio block the main TMDB URL, [https://api.themoviedb.org](https://api.themoviedb.org), however, the mirror, [https://api.tmdb.org](https://api.tmdb.org), is not blocked. 

### Any other details to share?

We can additionally allow users to use this simple proxy [tmdb-proxy](https://github.com/chervontsev/tmdb-proxy) to self-host their own endpoint to circumvent this restriction or use the tmdb mirror endpoint for the solution. I can work on this and create a pull request if required for fixing this issue. A lot of such issues have been closed without any resolution, and this can help a lot of self-hosting users.

**Comment by meghrathod** [comment]
Also official TMDB twitter account recommends this [here](https://twitter.com/themoviedb/status/1089256456333848576).

**Comment by JorrinKievit** [comment]
Lets keep the main one, if the request fails, fallback to the other url, if that one fails show the error
