### ISSUE TITLE
[Bug]: Showbox provider down

### ISSUE THREAD

**Issue by Simondegoose** [movie-web/movie-web#1112]
### What happened?

1. Showbox provider seems to be down for quiet some time now. I waited until others started reporting but at least from the 7th of april this has been an issue. 

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

**Comment by zisra** [comment]
Duplicate and known issue

**Comment by JorrinKievit** [comment]
Yup, wont be fixed in the near future. Check https://github.com/movie-web/movie-web/issues/393 for updates on providers
