### ISSUE TITLE
[Feature]: Add https://andyday.tv/ provider

### ISSUE THREAD

**Issue by itsmeadarsh2008** [movie-web/movie-web#1113]
### What feature do you want to add?

https://andyday.tv/

### Why do you want to have this feature?

It's stable because of zero ad experience except for rare video ads.
AndyDay is a Free Movies streaming site with zero ads. They let you watch movies online without having to register or pay, with over 10000 movies and TV series. 

### Any other details to share?

I was searching through the internet to get a stable site to watch movies. Here's what I got.

**Comment by zisra** [comment]
This is just a FlixHQ clone, which we already have

**Comment by itsmeadarsh2008** [comment]
I don't think so because it has 2 servers like UpCloud and I'm seeing no ads at all nor any adblock disable popup.

**Comment by Ciarands** [comment]
> I don't think so because it has 2 servers like UpCloud and I'm seeing no ads at all nor any adblock disable popup.

Respectfully, you think wrong

**Comment by lonelil** [comment]
![image](https://github.com/movie-web/movie-web/assets/51315646/96c80505-3ceb-4e7f-8f0e-f60e2a20dd31)
