### ISSUE TITLE
[Bug]: TMBD returns 404

### ISSUE THREAD

**Issue by techroy23** [movie-web/movie-web#1118]
### What happened?

TMBD returns 404 even with valid read key
![image](https://github.com/movie-web/movie-web/assets/53241974/8d15ef0d-304b-4d73-b7fc-a536d8bdf67f)

### Steps to reproduce?

1.) Download the latest PWA release.
2.) Update the config.js vars.
3.) run with ```python -m http.server 8080```

**Comment by JorrinKievit** [comment]
Seems like you're blocked? Can you access https://www.themoviedb.org/? I dont think this is an issue on our side

**Comment by techroy23** [comment]
Yes i can access it 
![image](https://github.com/movie-web/movie-web/assets/53241974/a7267e6f-8d37-4e97-9337-155bfd983cc8)
![image](https://github.com/movie-web/movie-web/assets/53241974/f338ac29-5da0-4484-b915-b9cffb75ec26)

**Comment by JorrinKievit** [comment]
Can reproduce on the instances, when a movie for example is opened it also does a request to a /tv endpoint, and it does not exist. And after that it does the same non-existent request to the fallback URL

1. First request url: https://api.themoviedb.org/3/tv/?append_to_response=external_ids
2. Also does this request at the same time (which is valid): https://api.themoviedb.org/3/movie/299534?append_to_response=external_ids
3. And after that does a request to this (which is invalid): https://api.themoviedb.org/3/tv/299534?append_to_response=external_ids 

Site continues to work fine though
