### ISSUE TITLE
[Bug]: Search results broken

### ISSUE THREAD

**Issue by TecEash1** [movie-web/movie-web#1120]
### What happened?

The thing that says 'failed to find media'. Expected TMDB to work as expected and load the results.

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

Not really sure, this only happens on some browsers. e.g. it happens on my TV but is fine everywhere else. Someone else also had the issue on their iPhone. But for me it was fine on there.

### Other relevant information

This issue only seems to occur after updating to the latest 4.7.0 update. Reverting the changes in the tmdb file/downgrading fixes all of these issues.
Corresponding discord thread: https://discord.com/channels/871713465100816424/1229392614105808917

Also when viewed in the /admin panel tmdb does produce an error on the devices where it doesn't work anymore

**Comment by TecEash1** [comment]
it also occurred for a person on safari in the mw discord and was working fine on my browser beforehand

**Comment by Nam3ls** [comment]
if thats so then how can I Revert the changes in the tmdb file/downgrade ?
