### ISSUE TITLE
[Bug]: VidSrc says missing movie when it's not

### ISSUE THREAD

**Issue by joshholly** [movie-web/movie-web#1125]
### What happened?

So when I was searching for a few movies, it tries to load from vidsrc, and the movie-web app says there's no video for that movie. However, when I go to vidsrc.me and put in the movie ID, it is there. 

I am using @movie-web/providers 2.2.9 . How can I upgrade it to the latest one using vercel?

### What browsers are you seeing the problem on?

Chrome, Safari

### Steps to reproduce?

1. Search for a movie that's not available on VidSrc According to movie-web (in my case it was Pink Flamingos) 
2. It says movie  not found

**Comment by joshholly** [comment]
Also. How come VidSrcTo only works when I have the browser extension? I really would like for my users who don't have the browser extension to be able to use VidSrcTo, as there's a lot of good movies there. How can I enable VidSrcTo for non-extension users? It's in @movie-web/providers

**Comment by JorrinKievit** [comment]
VidSrc.me isnt working and is disabled in the latest version. VidSrcTo is a browser extension source for a reason, we didnt do that for no reason. It requires headers that cant be applied client side
