### ISSUE TITLE
[Bug]: Not able to set fixed quality on WarezCDN

### ISSUE THREAD

**Issue by itsmeadarsh2008** [movie-web/movie-web#1127]
### What happened?

I'm not able to set the quality of the video.

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

1. Search movie `Zom 100: Bucket List of the Dead`
2. *automatically checks and finds in WarezCDN*
3. [Bug] Quality being unknown and unable to set one.

**Comment by JorrinKievit** [comment]
Provider does not have multiple qualities
