### ISSUE TITLE
[Bug]: Subtitle disappeared 

### ISSUE THREAD

**Issue by fadullalah** [movie-web/movie-web#1131]
### What happened?

Suddenly the subtitle for all the shows has been disabled or disappeared   
![Screenshot 2024-04-16 102031](https://github.com/movie-web/movie-web/assets/54377293/64cfb120-24d1-4a54-9f70-0faf93693fb0)

### Steps to reproduce?

1. open any show 
2. hit the subtitle tap
3. nothing there

**Comment by JorrinKievit** [comment]
Some sources have subtitles. Some dont. Vidplay (vidsrcto) sometimes stops returning them. We have no control over it. Try switching sources

**Comment by fadullalah** [comment]
all serves have same issue
