### ISSUE TITLE
[Feature]: Add NSBX As Source

### ISSUE THREAD

**Issue by joshholly** [movie-web/movie-web#1133]
### What feature do you want to add?

Add NSBX As Source. Fairly easy to scrape too. And they have a TON of movies and TV shows.

For Series you do:

https://nsbx.000000077.xyz/vault?tmdbId=63770&season=1&episode=1

(that gets the late show with Stephen Colbert season 1 episode 1)

For a Movie you just do:

https://nsbx.000000077.xyz/vault?tmdbId=98406

That gets The Dog Pound (another movie I can't find on regular movie-web)

### Why do you want to have this feature?

@movie-web/providers

**Comment by TecEash1** [comment]
<img width="303" alt="image" src="https://github.com/movie-web/movie-web/assets/92249532/507b1af7-5569-479c-8fce-fd4422ec6a1a">

**Comment by JorrinKievit** [comment]
Answered 😄

**Comment by joshholly** [comment]
Can we just get NSBX since Showbox isn't working? Because NSBX works just fine.

**Comment by JorrinKievit** [comment]
> Can we just get NSBX since Showbox isn't working? Because NSBX works just fine.

If you read the reply of @TecEash1 , you would've had your answer
