### ISSUE TITLE
[Bug]: How do I force update @movie-web/providers from pnpm on Vercel?

### ISSUE THREAD

**Issue by joshholly** [movie-web/movie-web#1134]
### What happened?

So I have the latest version, 2.3.0. But that was released 5 days ago. There's been more updates since the last version number. How can I update it on vercel? I can't just run pnpm upgrade.

**Comment by JorrinKievit** [comment]
You update your instance, everytime we do a providers update we also release a movie-web update. You can always manually upgrade your packages in package.json

**Comment by joshholly** [comment]
Right, but you guys did an update to @movie-web/providers 5 hours ago. But the latest version is 2.3.0 . Which I've already upgraded to 2.3.0, but there's been changes to @movie-web/providers since the last 2.3.0 upgrade.

**Comment by joshholly** [comment]
So you guys added filemoon to @movie-web/providers. How can I make sure it upgrades to that particular one? Not the last 2.3.0 package.
