### ISSUE TITLE
[Bug]: How do I get the latest @movie-web/providers if I already upgraded to 2.3.0?

### ISSUE THREAD

**Issue by joshholly** [movie-web/movie-web#1135]
### What happened?

So I have vercel, and I have already upgraded to 2.3.0. Since then, they added filemoon. I tried to do a re-deplay on vercel hoping it will pull the latest 2.3.0 package but it didn't. I tried doing pnpm upgrade then re-pushing to my git, and that didn't work either. I'd like to get the latest @movie-web/providers , but since I've already upgraded to 2.3.0, it won't let me upgrade it any further.

**Comment by joshholly** [comment]
I tried to explain that I already upgraded to 2.3.0 but you guys close out the issue before I even get to put any feedback in.

**Comment by JorrinKievit** [comment]
Use our discord server for general questions, this is to track bugs and features
