### ISSUE TITLE
[Feature]: Ability to add custom providers via addon or scripts?

### ISSUE THREAD

**Issue by vijayvcm** [movie-web/movie-web#1136]
### What feature do you want to add?

An ability to add custom providers via addon/script file or any other way.

### Why do you want to have this feature?

It isn't easy to include all the providers in the movie-web and maintain them in the long run. Instead, we just keep the core/necessary providers like Showbox, and vidsrc (what we have currently) in the movie-web and allow the user to choose/import their custom providers either by adding an addon or injecting the custom script via external repositories. 

Currently, the movie-web providers don't support all the regional content. Most of the content was in English. I am from India and we speak around 30 languages here other than English. Also, we have a lot of streaming sites to stream but they are not available on movie-web at the moment. 

So, it would be better If movie-web allows external providers to stream. 

### Any other details to share?

An example of it can be the Stremio app. It allows developers to create their addons to stream. Likewise, we can allow developers to create custom providers for movie-web.

It need not be implemented immediately but we can consider this at some point in time.

**Comment by JorrinKievit** [comment]
Out of scope. The providers library is already made in a way so you can easily add your own sources if you use the npm library in your own project.

You can also always fork the library and use the fork for your instance.
