### ISSUE TITLE
cant sign back in

### ISSUE THREAD

**Issue by wndeoifnrwoafun** [movie-web/movie-web#1138]
### What happened?

idk what happened just cant sign in, also doesnt work on other clients. It gives me an error saying :
[POST] "https://mw-backend.lonelil.ru/auth/login/start": <no response> Failed to fetch

client: mw.lonelil.ru

**Comment by lonelil** [comment]
goto https://mw-backend.lonelil.ru and give me your ray-id

**Comment by heyjumanji** [comment]
> goto https://mw-backend.lonelil.ru and give me your ray-id

I use your database how do i can give you mine ?

**Comment by wndeoifnrwoafun** [comment]
nvm guys it works the link redirects me to a temp ban cuz of something i cant remember it has something ti do with false ddos thing
