### ISSUE TITLE
[Feature]: Card actions

### ISSUE THREAD

**Issue by Tazi0** [movie-web/movie-web#1139]
### What feature do you want to add?

1. When a user is done watching a movie, but it's still in the list because he skipped the credits. A checkmark button in the movie card on the homepage.
2. When a user wants to plan a movie he can't bookmark the movie, he must first click on the movie and then bookmark it. A bookmark button on the movie card would prevent those (annoying) steps.

### Why do you want to have this feature?

Ease of use, instead of edit and X

Ease of use, instead of playing and then bookmarking and then existing.

**Comment by Pasithea0** [comment]
Already have #2

**Comment by Tazi0** [comment]
@Pasithea0 No I don't think you've read my post correctly, #2 is for captions?

**Comment by binaryoverload** [comment]
Duplicates of #900 and #353
