### ISSUE TITLE
[Bug]: 🔴 Instance down (mw.lonelil.ru)

### ISSUE THREAD

**Issue by lawdefier** [movie-web/movie-web#1144]
### What happened?

i tried logging in on mw.lonelil.ru and it gave the error [POST] "https://mw-backend.lonelil.ru/auth/login/start": <no response> Failed to fetch

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

press sync to cloud
enter ID and password and press login

**Comment by JorrinKievit** [comment]
Not a bug in our application. As we state in the docs (https://movie-web.github.io/docs/instances), these are volunteer instances and can go down at any time. 

In this case lonelil has been experiencing ddoss attacks, and it might be slow here and there. But keep in mind we do not own the instances, so when it starts working again is out of our control. If you want to ensure having a working backend at all times, you can always host one yourself 😄
