### ISSUE TITLE
[Bug]: For some reason it doesn't let me fullscreen the video when I have Volume Master enabled

### ISSUE THREAD

**Issue by LTNGKarbn** [movie-web/movie-web#1147]
### What happened?

I use Volume Master (https://chromewebstore.google.com/detail/volume-master/jghecgabfgfdldnmbfkhmffcabddioke) because I like to boost the volume of the video, but for some reason I can't fullscreen the application when I use it. Not sure why as I haven't had this issue with anything else and it returns back to normal if I disable it.

### What browsers are you seeing the problem on?

Chrome, OperaGX

### Steps to reproduce?

1. Install the volume booster extension on Opera GX (https://chromewebstore.google.com/detail/volume-master/jghecgabfgfdldnmbfkhmffcabddioke)
2. Enable the extension and boost the volume to whatever you want
3. Go to a video on your choice of provider (I use https://mw.lonelil.ru)
4. It will not let you fullscreen

### Other relevant information

Was also able to replicate the issue on chrome

**Comment by JorrinKievit** [comment]
Seems to be an issue with the way chromium browsers work, see https://www.petasittek.com/volume-master/faq/#:~:text=Chrome%20prevents%20itself%20from%20going,and%20that's%20a%20good%20thing. This is not a bug in our application.
