### ISSUE TITLE
[[Bug]: SuperStream not working SelfHosted

### ISSUE THREAD

**Issue by Convitt** [movie-web/movie-web#123]
### What happened?

I tested the provider SuperStream with the Wednesday series on the website https://movie.squeezebox.dev/
and in my self hosted. In my Self Host it gives error, already in the project site it works normally.

![image](https://user-images.githubusercontent.com/122373050/214018324-72c7d4d4-c093-4ad0-9e09-caa9037aa5e9.png)
![image](https://user-images.githubusercontent.com/122373050/214018347-3c4198ad-ce63-417c-b002-1e9d33d00a62.png)
![image](https://user-images.githubusercontent.com/122373050/214018379-9724cf14-4b79-4d1b-bf40-2ec486c823ff.png)

**Comment by JamesHawkinss** [comment]
Please provide console logs of scraping errors

**Comment by Convitt** [comment]
Sorry, how do I get these logs? Please.

By the way, i had this print 
![image](https://user-images.githubusercontent.com/122373050/214019309-e5c3d678-f431-45e6-97ff-130e70b5126c.png)

**Comment by Convitt** [comment]
![image](https://user-images.githubusercontent.com/122373050/214020140-ff05f65d-ef29-44e5-858e-12aa987f3fc4.png)

**Comment by JamesHawkinss** [comment]
Could be that you're missing an API key, or your proxy is misconfigured. We can't provide support for self hosted instances, as mentioned in the selfhosting docs.

**Comment by Convitt** [comment]
API key for what? SuperStream?

**Comment by mrjvs** [comment]
This may be related to a bug in latest version of the proxy worker. Something about cookies breaks. And makes it retur n a 500

**Comment by mrjvs** [comment]
Reopening, I suspect this is a bug that also happens for us

**Comment by Convitt** [comment]
I fixed it just rollbacking the work.js, the lastest version is broken

**Comment by mrjvs** [comment]
will be fixed by this PR: https://github.com/movie-web/simple-proxy/pull/6

**Comment by Convitt** [comment]
Works fine! Thanks
