### ISSUE TITLE
[Feature]: Netfilm / LokLok provider

### ISSUE THREAD

**Issue by gabinfinity** [movie-web/movie-web#128]
### What feature do you want to add?

I found this repository and it has an excellent provider with several movies and series. Would it be possible to add to the movie-app? https://github.com/lamhoang1256/netfilm

### Why do you want to have this feature?

Better results

**Comment by JamesHawkinss** [comment]
Netfilm exposes its own API, which acts as a middleman for the LokLok API. We've had issues with the LokLok API in the past, so Netfilm could prove useful.

https://net-film.vercel.app/api-doc

**Comment by gabinfinity** [comment]
[image: image.png]there is a lot things here, any chances to integrate do
movie-web?

Em qua., 25 de jan. de 2023 às 07:43, James Hawkins <
***@***.***> escreveu:

**Comment by gabinfinity** [comment]
![image](https://user-images.githubusercontent.com/59806981/214549438-8bf72253-4c6f-4b6c-8cbe-eb4671d0ac90.png)

**Comment by lem6ns** [comment]
This is planned for v3.

**Comment by JamesHawkinss** [comment]
https://github.com/movie-web/movie-web/commit/2b81d061f4344b8695b0359ac24812ac15cb69a6

Netfilm provider has been implemented on v3 branch

**Comment by gabinfinity** [comment]
Thank you! s I said on discord, I have some other apis. Sora has some. They also use consumet. I will be uploading both repositories

https://github.com/Khanhtran47/Sora
https://github.com/consumet/api.consumet.org  - This is awesome
https://github.com/elsayed85/videos
