### ISSUE TITLE
[Feature]: PreMiD presence

### ISSUE THREAD

**Issue by RihanArfan** [movie-web/movie-web#130]
### What feature do you want to add?

Adding support for movie-web as a PreMiD Presence to show what people are watching on their Discord status.

It can be similar to how the Netflix presence is.
![image](https://user-images.githubusercontent.com/20425781/215228251-7f230531-6ffb-4740-b4f4-7aa4d1c33b91.png)

Creating this issue just to track, but adding the presence would be done on their repo.
- https://github.com/PreMiD/Presences
- https://docs.premid.app/en/dev/presence

### Why do you want to have this feature?

Because watching illegally is boring if people don't know you're doing it

## Todo list
 - [x] add meta data to the window
 - [ ] make presence

**Comment by mrjvs** [comment]
Sounds good, will have to be implemented after v3, we can perhaps also make some changes to make this easier. Like exposing meta data on the window object

**Comment by zisra** [comment]
If someone does this, I will be happy to work on the presence
>  Like exposing meta data on the window object

**Comment by mrjvs** [comment]
sounds good @zisra, i will let you know once we have that implemented.

**Comment by Jordaar** [comment]
Is someone still working on this, or can I take it on?

**Comment by mrjvs** [comment]
you can take it, we have the data needed stored on the window object. so you can just pull periodically. like every second or smth.
Ill assign it to you.

**Comment by Jordaar** [comment]
https://premid.app/store/presences/movie-web

<details>
<summary> Preview (prod. version) </summary>

![image](https://github.com/movie-web/movie-web/assets/69628820/3235884e-e71c-48b0-b5ec-684403ff8464)

![image](https://github.com/movie-web/movie-web/assets/69628820/269dc551-2d93-49fe-be00-b00c744a0526)

![image](https://github.com/movie-web/movie-web/assets/69628820/5eed9f10-400f-4e1d-b72c-877a662d5d61)
</details>

**Comment by mrjvs** [comment]
Looks amazing @Jordaar , that means there is nothing else to be done on premid, right? Issue can be closed?

**Comment by Jordaar** [comment]
Yes, issue can be closed.

**Comment by mrjvs** [comment]
Awesome stuff

**Comment by jayjakee** [comment]
I was watching some series over the time and it kept showing S1E1 for every episode. Is anyone else experiencing it?

**Comment by mrjvs** [comment]
> I was watching some series over the time and it kept showing S1E1 for every episode. Is anyone else experiencing it?

Yes, I can reproduce it myself. I opened a new bug report for it: #389
