### ISSUE TITLE
[Bug]: TypeError - Cannot read properties of undefined (reading 'seasons')

### ISSUE THREAD

**Issue by catburger69** [movie-web/movie-web#131]
### What happened?

I searched up "ninjago", clicked on the second option (secrets of the forbidden spinjitzu) and an error screen popped up, prompting me to report an error on the discord or github 

![download](https://user-images.githubusercontent.com/106676488/215262244-564a14af-8425-4194-a563-b4d49f914b25.png)

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Other relevant information

im on opera gx rn

**Comment by JamesHawkinss** [comment]
Thanks for reporting, looks like we're not handling this error correctly. The show you're looking for can't actually be found, so it can't find a list of Seasons - this issue will be resolved in an upcoming update. 

For now, you can assume that the series cannot be found if this issue occurs.
