### ISSUE TITLE
[Feature]: Kisskh provider

### ISSUE THREAD

**Issue by Convitt** [movie-web/movie-web#132]
### What feature do you want to add?

Is possible to add Kisskh provider? https://github.com/Khanhtran47/Sora/tree/master/app/services/kisskh

### Why do you want to have this feature?

New providers is always welcome

**Comment by mrjvs** [comment]
Url is https://kisskh.me/
Source is watermarked at video level.
@JamesHawkinss can you check if this source is not cors restricted?

**Comment by JamesHawkinss** [comment]
@mrjvs .m3u8 files appear to have no CORS restrictions on this source. 

Other endpoints appear to have `strict-origin-when-cross-origin` rules

API url is https://kisskh.me/api/

**Comment by JamesHawkinss** [comment]
Not a viable source, there is CF protection on their API endpoints. Our worker gets redirected.
