### ISSUE TITLE
[Feature]: Subtitle uploads

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#136]
### What feature do you want to add?

Ability to select and view your own subtitle files. Should support .srt and .vtt

### Why do you want to have this feature?

Not all provided subtitles are good quality, being able to bring your own can fix that.

### Anything other details to share?

Roadmap: after v3

**Comment by gabinfinity** [comment]
this is a good feature

**Comment by gabinfinity** [comment]
hey mrjvs may be this repo can help us 
https://github.com/bipuldey19/Opensubtitles-Unofficial-API - unofficial opensubs api
https://github.com/moviecollection/open-subtitles - another api provider, this is awesome, has so many subs

**Comment by mrjvs** [comment]
> hey mrjvs maybe this repo can help us 
> https://github.com/bipuldey19/Opensubtitles-Unofficial-API - unofficial opensubs api
> https://github.com/moviecollection/open-subtitles - another api provider, this is awesome, has so many subs

Unrelated to this issue.
