### ISSUE TITLE
[Feature]: Autoplay next episode

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#140]
### What feature do you want to add?

when reaching end of episode, automatically move to next episode of series

### Why do you want to have this feature?

makes it more fun to binge watch

**Comment by zisra** [comment]
If this is added, we could also add support to the `previoustrack` and `nexttrack` events

**Comment by mrjvs** [comment]
I dont think we should support those events

**Comment by zisra** [comment]
Why not?

**Comment by francescoavagliano** [comment]
Yeah it would be nice. I'm binge watching friends and it would be a nice feature to have. Thanks to the mods anyway

**Comment by dgw** [comment]
I hope autoplay will be optional when implemented. It's the first thing I turn off on new devices using apps like Hulu.

**Comment by francescoavagliano** [comment]
that's fair

**Comment by mrjvs** [comment]
This has been fixed in the latest version: #530
(although it doesnt actually move automatically, just prompts a next button)
