### ISSUE TITLE
[Bug]: Empty page

### ISSUE THREAD

**Issue by kuro-l** [movie-web/movie-web#152]
### What happened?

Not sure why but nothing loads, i just see an empty page and reloading or trying on different browsers don't work either.
<img width="1440" alt="Screenshot 2023-02-20 at 3 40 17 PM" src="https://user-images.githubusercontent.com/125861591/220042933-96b8d38f-64d7-4fcf-b5aa-6c76a9b2d112.png">

### What browsers are you seeing the problem on?

Chrome, Safari, Other (tell us in input box below)

### Steps to reproduce?

Just go on the page, tried on Opera GX as well and it does work either.

### Other relevant information

Tried on my mobile (ios and android) as well but getting the same issue

**Comment by maxwellward** [comment]
Hi! This is a known issue and will be resolved in the morning 😄 You can find more information on Discord [here](https://discord.com/channels/871713465100816424/1076882579380240435/1077073478013943818).

**Comment by JamesHawkinss** [comment]
This should now be resolved, if it's still occurring for you then try clearing your browser cache (Ctrl + F5 or equivalent). Thanks for reporting :)
