### ISSUE TITLE
[Bug]: No longer works on mobile devices

### ISSUE THREAD

**Issue by jakeshrimp9** [movie-web/movie-web#153]
### What happened?

Well that's just it, the thing is I see nothing. The new web app loads to a black screen mobile devices. On the galaxy A51 I tried chrome and Samsung internet browsers and the xcast in app browser. On iphone 13 pro max I tried brave, chrome, and safari. Tried requesting desktop mode didn't change anything. 

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

Went to movie.squeezebox.dev redirected to new site. 

Tried loading the new site direcrly, same issue

### Other relevant information

Link after loading movie.squeezebox.dev 
https://movie-web.app/v2-migration?m-time=2023-02-20T03%3A59%3A26.530Z&m-data=eJyrrgUAAXUA%2BQ%3D%3D
Produces blank black screen

Movie-web.app also loads blank black screen

**Comment by JamesHawkinss** [comment]
Hi @jakeshrimp9, thanks for the report. This issue should have been resolved as of ~30 minutes ago, can you try clearing your cache?

https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DAndroid

**Comment by jakeshrimp9** [comment]
Works perfectly fine on Firefox through Ubuntu OS and chrome and brave on windows OS. My only input on the web version is I am kind of upset I can't right click and download anymore. I do like how nice it looks now but do miss the right click download and not being able to use my phone

**Comment by JamesHawkinss** [comment]
Let me know once you've tried clearing your mobile cache, this has been observed to resolve the issue with other users

**Comment by jakeshrimp9** [comment]
> Hi @jakeshrimp9, thanks for the report. This issue should have been resolved as of ~30 minutes ago, can you try clearing your cache?
> 
> https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DAndroid

It works thank you!
