### ISSUE TITLE
[Feature]: Deploy to workers button in readme

### ISSUE THREAD

**Issue by RihanArfan** [movie-web/movie-web#158]
### What feature do you want to add?

We could add a "Deploy to Workers" button on our README to make it easier for people to self host movie-web. 

https://developers.cloudflare.com/workers/platform/deploy-button/

### Why do you want to have this feature?

Easier selfhosting and deploying

**Comment by mrjvs** [comment]
Doing decentralized proxies is a bit invasive, we shouldn't try to make selfhosted versions part of a network, they should be completely standalone imo. But we should still allow for round robin more proxies.

**Comment by mrjvs** [comment]
made issue for round robin at #159

**Comment by mrjvs** [comment]
This has been fixed in the latest version: #530
