### ISSUE TITLE
[Feature]: A settings page

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#163]
### What feature do you want to add?

A settings page, showing these items:
 - [x] Current version the app is running
 - [x] A language selector
 

### Why do you want to have this feature?

there is currently no way to see/edit the aforementioned items

**Comment by maxwellward** [comment]
Rather than a dedicated page, if it's just those two options could we put them in the footer instead?

**Comment by mrjvs** [comment]
> Rather than a dedicated page, if it's just those two options could we put them in the footer instead?

I was thinking a full page or modal, so we don't have to keep finding places to put settings when we get new ones. A bit of future proofing.

**Comment by athaller** [comment]
Was thinking about having a setting for captions on or off by default and glad I came across this topic.

Other options that can be added:
 - Autoplay On/Off Toggle
 - Captions On/Off (Default option)
 - Default/Recommended Provider
 - Default/preferred quality (as I think right now everything is hardcoded for 1080p from a quick src glance)
 - Option to skip intro/credits of tv shows (but would require a feature ticket to have the base functionality added)

**Comment by judemont** [comment]
A settings page is a good idea,
here are some other elements that could be added in the settings:
- Change keyboard shortcuts
- Disable/enable history
- Choose preferred providers
