### ISSUE TITLE
[Bug]: Netfilm provider broken

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#168]
### What happened?

netfilm provider has stopped working

### What browsers are you seeing the problem on?

Firefox

### Steps to reproduce?

1. choose netfilm
2. ...
3. profit
4. failed to run provider

### Other relevant information

api has changed, updating to new the new api method will most likely fix it

**Comment by lem6ns** [comment]
more clarification, changed m3u8 so blocks any referers
potentially host a loklok proxy on vercel or alike
