### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GodDeepak** [movie-web/movie-web#170]
### What happened?

Getting this alert in self-hosted site : 
Misconfigured instance, missing key: NORMAL_ROUTER

**Comment by JamesHawkinss** [comment]
That's a bug we caught in this version, and will be fixed in the next update.

for now as a temporary fix, you can add `NORMAL_ROUTER: "false",` to the config.js file

**Comment by GodDeepak** [comment]
I added this but issue is still there.

**Comment by mrjvs** [comment]
> I added this but issue is still there.

the latest release has the bug fix, so just update
