### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by ScripterSaurav** [movie-web/movie-web#173]
### What feature do you want to add?

Please tell me How can i add my own gdrive I'd for streaming movies??

### Why do you want to have this feature?

It will we helpful for adding movies which are not available on other providers.

**Comment by lem6ns** [comment]
not in scope of project

**Comment by mrjvs** [comment]
As lemons said. We are a video streaming site, not a personal video player. So this won't be added as a feature.
