### ISSUE TITLE
[Feature]: Pip (Picture In Picture)

### ISSUE THREAD

**Issue by ARR4NN** [movie-web/movie-web#174]
### What feature do you want to add?

A new button to the video player for Picture In Picture mode. 
![image](https://user-images.githubusercontent.com/70060472/221441596-5a06b82e-7e2b-4a95-a3e3-0c7db3512242.png)

https://www.w3.org/TR/picture-in-picture/
https://css-tricks.com/an-introduction-to-the-picture-in-picture-web-api/
https://googlechrome.github.io/samples/picture-in-picture/

### Why do you want to have this feature?

To allow watching of movies while on other tabs

**Comment by mrjvs** [comment]
We can probably do this. Can be part of 3.1 update.

Relevant docs: https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API

**Comment by zisra** [comment]
I can work on this
