### ISSUE TITLE
[Feature]: Keep subtitles in view when player UI is shown

### ISSUE THREAD

**Issue by RihanArfan** [movie-web/movie-web#180]
### What feature do you want to add?

When the video player UI is shown, currently subtitles are covered. I think we should move them up above the player components when it's shown.

![image](https://user-images.githubusercontent.com/20425781/222934486-9249c144-c583-47af-aa42-42995246afd1.png)

### Why do you want to have this feature?

Minor UI improvement

**Comment by zisra** [comment]
This is not possible without a custom renderer > #137

**Comment by RihanArfan** [comment]
Closing as that would solve this
