### ISSUE TITLE
[Bug]: Failed to read local storage

### ISSUE THREAD

**Issue by DukeBlueDevil** [movie-web/movie-web#181]
### What happened?

I was on skoolgq.github.io and I went to go watch Outer Banks. I expected it to load but instead as soon as I got to the site I found an error that says: SecurityError - Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
at Lazy

The browser I was on was Google Chrome, on an incognito page.

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

I tried to refresh and restart my computer, but the bug was still there.

**Comment by JamesHawkinss** [comment]
We do not provide support for embedded instances. If you want to use the site, use it on https://movie-web.app or self-host it.

**Comment by DukeBlueDevil** [comment]
> We do not provide support for embedded instances. If you want to use the site, use it on https://movie-web.app or self-host it.

Ok thank you luckily I have found the actual link to the movie web app and might as well stop using embedded websites.
