### ISSUE TITLE
[Bug]: ReferenceError - structuredClone is not defined

### ISSUE THREAD

**Issue by fowntain** [movie-web/movie-web#182]
### What happened?

I attempted to self-host movie-web (I created a repl just to test it), and it is configured just as required in the tutorial, but this error appeared when I tried to watch something:
![Screenshot 2023-03-07 12 31 22 PM](https://user-images.githubusercontent.com/93336301/223502539-c9329086-074c-403d-8a58-4716a15c2695.png)

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

1. Do steps in the tutorial (I did do the CF worker part and config.js)
2. Uploaded the configured folder to replit so I could test it before hosting it myself
3. Tried to watch something random, like Stranger Things

### Other relevant information

N/A

**Comment by mrjvs** [comment]
seems to be a browser issue. What version of chrome are you on?
three dots > settings > about chrome

**Comment by fowntain** [comment]
> seems to be a browser issue. What version of chrome are you on? three dots > settings > about chrome

That's the issue. I was testing it on a VM which had an old version of chrome installed. When I tested it on my normal browser, it worked fine. Thanks!
