### ISSUE TITLE
[Feature]: Fullscreen on landscape orientation on mobile devices

### ISSUE THREAD

**Issue by frost768** [movie-web/movie-web#184]
### What feature do you want to add?

On mobile, when in media player view, if user places his/her phone on landscape mode automatically launch fullscreen

### Why do you want to have this feature?

Better UX

### Anything other details to share?

Wrapping [Screen Orientation API](https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation) in a hook should suffice

**Comment by frost768** [comment]
Also shouldn't it say "Any other detail.." instead of "Anything"?

**Comment by mrjvs** [comment]
Unfortunately, the screen orientation change event is not a trusted event, we are not allowed to go fullscreen based on an untrusted event.

Trying to do so anyways simply won't work, it just doesn't go fullscreen.
