### ISSUE TITLE
[Bug]: VTT captions do not work if needsProxy is false

### ISSUE THREAD

**Issue by lem6ns** [movie-web/movie-web#188]
### What happened?

Specifying caption.type as VTT and setting caption.needsProxy to false throws a same-origin error.

Expected: Caption works fine.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Steps to reproduce?

1. Go to line 56 and line 124 in `src/backend/providers/netfilm.ts` and remove `.replace("https://convert-srt-to-vtt.vercel.app/?url=", "")`
2. Change type to MWCaptionType.VTT on line 125 and 57
3. Set source to netfilm and try using captions
4. Same-origin error occurs

### Other relevant information

Can be fixed in `src/backend/helpers/captions.ts` near line 29.

**Comment by mrjvs** [comment]
Cannot be replicated
