### ISSUE TITLE
[Bug]: Error at castingInternal

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#201]
### What happened?

sometimes this error appears, unsure the cause:
<img src="https://user-images.githubusercontent.com/100528712/224580387-e7d5875d-1cfd-4e41-b43c-5725e2c1e160.png" />

### What browsers are you seeing the problem on?

Firefox

**Comment by mrjvs** [comment]
cannot reproduce, however its a bug that happens quite often and we get a lot of reports.

**Comment by zisra** [comment]
![Image](https://github.com/movie-web/movie-web/assets/100528712/7bc79948-811a-444b-89a2-8eba5c2eb8bb)

For those who don't read all the channels

**Comment by binaryoverload** [comment]
Issue was made for V3, no reports I'm aware of since v4 has been released
