### ISSUE TITLE
[Bug]: netfilm cors error

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#203]
### What happened?

> I don't know why but some movies got cors error with netfilm provider like https://movie-web.app/media/JW-movie-1261553 or https://movie-web.app/media/JW-movie-810505 ... but others not

reproducible by multiple people

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by zisra** [comment]
The reason for this is that cloudflare overrides headers when the worker throws an exception. This also happens in cloudflare
