### ISSUE TITLE
[Bug]: no focus styles

### ISSUE THREAD

**Issue by zisra** [movie-web/movie-web#204]
### What happened?

<img width="93" alt="image" src="https://user-images.githubusercontent.com/100528712/224801364-150a5fa9-245c-4173-8fd6-252534964b9b.png">
<img width="274" alt="Screenshot 2023-03-13 at 1 54 33 PM" src="https://user-images.githubusercontent.com/100528712/224801680-f3371bae-21cd-4539-a3f8-f1315e3f7858.png">
As you can see in the image above, the focus is unstyled and tabbing out looks weird

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

Press tab in the search page, home page, or video player

### Other relevant information

[Handling Hover, Focus, and Other States](https://tailwindcss.com/docs/hover-focus-and-other-states) (Tailwind)

**Comment by frost768** [comment]
Isn't it much better for accessibility? Like for high contrast themes on the operating system

**Comment by mrjvs** [comment]
This has been fixed in the latest version: #530
