### ISSUE TITLE
[Bug]: Safari media player view doesn't fit into viewport

### ISSUE THREAD

**Issue by frost768** [movie-web/movie-web#209]
### What happened?

- [ ] controls are not accessible due to them being pushed outside the viewport (only a fraction is shown like the progress bar) (also happens on chromebooks see #253 )
- [x] selecting a subtitle causes video element to get on top of other elements
- [ ] fullscreen button icon doesn't get changed after entering into fullscreen and exiting from fullscreen with the button is not possible
## Hovered state
![a](https://user-images.githubusercontent.com/19949367/224852283-052f06a4-7933-4e66-8735-b70b0225065d.png)

## Unhovered  state
![b](https://user-images.githubusercontent.com/19949367/224852287-be2ed25d-81dc-44a6-87a7-85b8b10f374b.png)

### What browsers are you seeing the problem on?

Safari

### Steps to reproduce?

1. Open the website on Safari
2. Open any media to enter video player

### Other relevant information
One thing that works is touchbar. It detects the media and provides controls

**Comment by zisra** [comment]
Can you send a screenshot of how this looks?

**Comment by zisra** [comment]
I believe a quick and dirty solution is this, it worked for me at least 
```css
video {
  z-index: 0;
}
```

**Comment by TheGloriousDuck** [comment]
> I believe a quick and dirty solution is this, it worked for me at least
> 
> ```css
> video {
>   z-index: 0;
> }
> ```

Where do you put this? I am self-hosting, so I want to just implement the fix myself for the time being

**Comment by frost768** [comment]
> > I believe a quick and dirty solution is this, it worked for me at least
> > ```css
> > video {
> >   z-index: 0;
> > }
> > ```
> 
> Where do you put this? I am self-hosting, so I want to just implement the fix myself for the time being
Can you try this ? i think this should fix it temporarily
https://github.com/movie-web/movie-web/pull/220

**Comment by zisra** [comment]
Yes that fixes it 100%

**Comment by zisra** [comment]
@TheGloriousDuck paste that into the `./src/setup/index.css` file

**Comment by TheGloriousDuck** [comment]
Tried to setup a developer workspace on codespaces (haven't been at my PC for a while), but I couldn't get it to work (kept getting a 502 bad gateway.) I'll try out the changes in the PR that @frost768 linked to and see if that fixes the issue. In case this changes anything, I am hosting movie-web on my PC through a caddy reverse proxy.

**Comment by JipFr** [comment]
I am unable to replicate this issue on Safari. What version are you using?

<img width="1382" alt="Screenshot 2023-05-03 at 00 38 58" src="https://user-images.githubusercontent.com/17685409/235800651-10877b75-62c4-45e2-ad7e-d6374df52ee7.png">

**Comment by zisra** [comment]
Still getting that issue

**Comment by mrjvs** [comment]
This has been fixed in the latest version: #530
