### ISSUE TITLE
[Bug]: Dropdowns don't work in fullscreen

### ISSUE THREAD

**Issue by maxwellward** [movie-web/movie-web#210]
### What happened?

When viewing media in full screen, dropdown menus don't work (episodes, settings, etc.)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Steps to reproduce?

1. Open any media
2. Full screen
3. Click a dropdown

**Comment by mrjvs** [comment]
oops, will be hotfixed soon(tm)

**Comment by mrjvs** [comment]
fixed in #212
