### ISSUE TITLE
[Bug]:  Provider context should contain episode and season number for series in addition to their IDs

### ISSUE THREAD

**Issue by frost768** [movie-web/movie-web#211]
### What happened?

For searching we are using JW's API and their ids for episodes and seasons may not have an identical match on the providers' side. Common properties we should be using are episode and season number so that we can match the correct source.
This could also mean changing the URL structure to `/showId/seasonNo/episodeNo`

**Comment by mrjvs** [comment]
all data you need is provided on the context. it has a list of seasons and a list of episodes for the currently selected season.
that data also includes the number variant of the id.

**Comment by frost768** [comment]
just realized it

**Comment by mrjvs** [comment]
here is an example to convert to numbers: https://github.com/movie-web/movie-web/blob/e5eb09af4d56009f121bde17d21b53bef77b3c28/src/backend/providers/superstream/index.ts#L219
