### ISSUE TITLE
[Bug]: FlixHQ search fails when title contains slashes

### ISSUE THREAD

**Issue by Artikronisz** [movie-web/movie-web#217]
### What happened?

FlixHQ search fails when title of content contains slashes ('/', '\\')

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

1. Search for content with a slash in it's title (Movie example: "Face/Off", Show example: "Sex/Life")

### Other relevant information
- Sanitizing the original title from slashes when doing the search query returns proper results (ie: Search for "FaceOff")
--- Note that result title will have the slash 
- Using the provider's website (flixhq.to) also fails when using the GUI search (might be a good way to test out other content titles or other characters that need to be pruned)

**Comment by mrjvs** [comment]
I can't seem to reproduce.
When I search for `face/off`. I see the search result and watching with flixhq source works as expected.

Is it possible you're using an older version of the app?
through what url are you using movie-web?

**Comment by Artikronisz** [comment]
> I can't seem to reproduce. When I search for `face/off`. I see the search result and watching with flixhq source works as expected.
> 
> Is it possible you're using an older version of the app? through what url are you using movie-web?

Hi mrjvs, I sincerely want to apologize for wasting your time. You are indeed correct the latest version does yield the proper results when doing the search step. 

There seems to be another issue where season 2 for Sex/Life is showing episodes from season 1 but I will do some proper investigating tomorrow.

Sorry again
