### ISSUE TITLE
Superstream provider does not work with 2023 movies and series

### ISSUE THREAD

**Issue by anybody999** [movie-web/movie-web#222]
### What happened?

I noticed that the movies and series of the year 2023 does not work on the provider Superstream.

Another thing I noticed, the Superstream provider is the only one that provides subtitles for almost all langs, especially the "Portuguese", the rest do not.
Can you fix it?

Example: https://movie-web.app/media/JW-movie-1235410 (Plane 2023)
Example: https://movie-web.app/media/JW-movie-1256986 (Missing 2023) 
Example: https://movie-web.app/media/JW-show-361538/ (TVSHOW: Black Snow 2023)

Thanks guys, best webapp for streaming no doubt!

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by anybody999** [comment]
> We don't have control on the content provided. Nothing we can do about it

And about subtitles? More subs maybe opensubtitles api?

**Comment by mrjvs** [comment]
Content is not something we control, and for external subs we have already have an open issue. Gonna close this issue as duplicate
