### ISSUE TITLE
[Feature]: add precise seeking with thumbnails

### ISSUE THREAD

**Issue by lankylonky22** [movie-web/movie-web#223]
### What feature do you want to add?

precisee seeking with thumbnails

### Why do you want to have this feature?

its a indispensable feature

**Comment by zisra** [comment]
As well as a tooltip with the current time

**Comment by zisra** [comment]
Many providers have a vtt file with thumbnails which we could easily parse and use. They are also a standard

Honestly the current thumbnails UI is not the best ... takes long to load & is inaccurate
![image](https://github.com/movie-web/movie-web/assets/100528712/a0409e57-1108-4cf2-af40-478999c20927)

**Comment by mrjvs** [comment]
This has been fixed in the latest version: #530
