### ISSUE TITLE
[Feature]: Chapters selection

### ISSUE THREAD

**Issue by zisra** [movie-web/movie-web#225]
### What feature do you want to add?

Add a popover that allows you to switch chapters from a stream

### Why do you want to have this feature?

It's useful if you want to jump to different parts of the stream

### Anything other details to share?

Look for the EXT-X-SESSION-DATA tag in the m3u8 stream
[Apple docs](https://developer.apple.com/documentation/http_live_streaming/providing_javascript_object_notation_json_chapters)
[hls.js docs](https://github.com/video-dev/hls.js/blob/master/docs/API.md#:~:text=parsed%20%23EXT%2DX%2D-,SESSION%2DDATA,-%5D%2C%20networkDetails%3A%20%5BLoader%20specific)

**Comment by mrjvs** [comment]
Considered out of scope
