### ISSUE TITLE
[Bug]: Matching "... : The Movie" titles

### ISSUE THREAD

**Issue by frost768** [movie-web/movie-web#227]
### What happened?

Some of the movies have "The Movie" in their titles. This makes it impossible to match with some providers' given title which don't have it.

### Steps to reproduce?

1. Search for "A Silent Voice"
2. Click on the search result (result has "The Movie" in it)
3. Providers return "A Silent Voice" as their title
4.  normalizeTitle function returns false
5. Displays not found as a result

### Other relevant information

This could be fixed by changing normalizeTitle function to handle that edge case.
```ts
export function normalizeTitle(title: string): string {
  let titleTrimmed = title.trim();
  if (titleTrimmed !== "The Movie" && titleTrimmed.endsWith("The Movie")) {
    titleTrimmed = titleTrimmed.replace("The Movie", "");
  }
  return titleTrimmed
    .toLowerCase()
    .replace(/['":]/g, "")
    .replace(/[^a-zA-Z0-9]+/g, "_");
}
```

**Comment by zisra** [comment]
Includes the series. When added, this series is fixed: https://movie-web.app/media/JW-show-374293/398067/7076113

**Comment by ericbsantana** [comment]
Can I get this task from TODO to fix in a PR? @zisra

**Comment by zisra** [comment]
@ericbsantana I'm not a maintainer, but you could surely submit a PR to change [this file](https://github.com/movie-web/providers/blob/3cd023bb10b11b170b42666c696a1d337baba5f0/src/utils/compare.ts#L3) (providers in the v4 version will be in another repo)

**Comment by capak07** [comment]
Is anyone working on it, if not I would like to submit a PR for this, thanks

**Comment by zisra** [comment]
Just do it

**Comment by capak07** [comment]
@zisra just wanted to confirm that the file to be changed is in the [providers repo ](https://github.com/movie-web/providers/blob/3cd023bb10b11b170b42666c696a1d337baba5f0/src/utils/compare.ts#L3) and not the[ utils file](https://github.com/movie-web/movie-web/blob/dev/src/stores/__old/utils.ts) for this repo?

**Comment by zisra** [comment]
@capak07 Yes, looks like legacy stuff. Read "DONT_TOUCH_THIS_FOLDER"

**Comment by capak07** [comment]
@zisra I've created a PR if you want to take a look https://github.com/movie-web/providers/pull/105
