### ISSUE TITLE
[Feature]: Increase or Decrease Playback Speed

### ISSUE THREAD

**Issue by the-bose** [movie-web/movie-web#233]
### What feature do you want to add?

A new feature to increase/decease the playback speed. Could be a slider or a dropdown with 0.25x, 0.5x, 1x, 1.5x and 2x.

### Why do you want to have this feature?

Helps skimming through a chapter and/or slow the video down to notice a detail or two.

**Comment by mrjvs** [comment]
funilly enough someone is in the process of making that right now, see #224
