### ISSUE TITLE
[Feature]: Add 2embed.to provider

### ISSUE THREAD

**Issue by atozmovies** [movie-web/movie-web#236]
### What feature do you want to add?

Add 2embed.to as provider

### Why do you want to have this feature?

it has lots of embeds to choose from, lots of videos.

### Anything other details to share?

it will require scraping from embeds, which can be difficult

**Comment by lem6ns** [comment]
planned

**Comment by mrjvs** [comment]
2embed has not been in the planning, I will rename this issue to match it

**Comment by frost768** [comment]
2embed's vidcloud server videos are restricted to an origin (rabbitstream) with cors header

**Comment by zisra** [comment]
2embed uses recaptcha too
