### ISSUE TITLE
[Feature]: Ability to skip sources on initial load

### ISSUE THREAD

**Issue by ooosssay** [movie-web/movie-web#240]
### What feature do you want to add?

Add a button that has the ability to skip a source when trying to automatically find the best source to use.

### Why do you want to have this feature?

It would let us skip sources that is taking too long and end up failing so we don’t have to wait for it to move on to the next source that works and is faster.

**Comment by zisra** [comment]
I think a timeout is planned

**Comment by mrjvs** [comment]
This has been fixed in the latest version: #530
(you can just open the source menu and choose)
