### ISSUE TITLE
[Bug]: Last episode completed does not save

### ISSUE THREAD

**Issue by ooosssay** [movie-web/movie-web#241]
### What happened?

Episodes does not save during or after finishing episode.

Expected to save.

### What browsers are you seeing the problem on?

Safari

### Steps to reproduce?

1) Open any series
2) Play an episode throughly normally
3) Go to the next episode

### Other relevant information

Just a speculation it might be either
1) When looking for a source it takes a long time,  it just won’t save
or
2) Playing the video with the operating systems own player like on iOS

What I do to get around it is to when pressing play I immediately go to a timestamp where I would want it to save and It would save

**Comment by lmmelo16** [comment]
Can you assign me this bug ? I am working on it in a College class
