### ISSUE TITLE
[Bug]: Fully closing the PWA removes all data

### ISSUE THREAD

**Issue by ooosssay** [movie-web/movie-web#242]
### What happened?

There is a chance when force closing the PWA, all of the saved bookmarks is removed along with its Watch history.

### What browsers are you seeing the problem on?

Safari

### Other relevant information

I did this on iOS

**Comment by mrjvs** [comment]
While doing some googling, I saw some threads on safari deleting localstorage data after 7 days, maybe thats triggered when it gets force closed?

Im not sure, nor do I have an ios device. @JipFr can you reproduce this on your end?

**Comment by mrjvs** [comment]
cannot reproduce, closing
