### ISSUE TITLE
[Feature]: Add Learn Mode for subtitles

### ISSUE THREAD

**Issue by castdrian** [movie-web/movie-web#244]
### What feature do you want to add?

K-Drama streaming service Viki has functionality labeled as "Learn Mode" which allows to have both Korean Captions and English Subtitles on the screen simultaneously. This is a great feature to have.

### Why do you want to have this feature?

Reading the Hangeul alongside the translation is a very good learning exercise, which also applies to all other writing systems used used across other languages.

### Anything other details to share?

No not really, this is a prime example of an amazing OSS project though, because most show/movie crawlers are pretty trash and ad-filled

**Comment by mrjvs** [comment]
sounds like a cool feature, ive marked it as planned.
(not that we have an ETA on it, there are lots of features planned :P )

**Comment by binaryoverload** [comment]
I think this is out of scope for this project

There are tools such as below that can be used to make dual language subtitles
- https://subtitletools.com/merge-subtitles-online
- https://bonigarcia.dev/dualsub/
