### ISSUE TITLE
[Bug]: Pause icon shows when seeking

### ISSUE THREAD

**Issue by zisra** [movie-web/movie-web#245]
### What happened?

<img width="79" alt="Screenshot 2023-03-30 at 9 50 25 PM" src="https://user-images.githubusercontent.com/100528712/229010587-e4f858b0-d219-41d6-999a-6e9985357cb1.png">

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

1. Play a video
2. Make sure the video is paused
3. Either use the left and right arrow keys or select a specific time 
4. Observe that the icon changes

**Comment by JamesHawkinss** [comment]
Intended behaviour
