### ISSUE TITLE
[Bug]: Movie Drop-down button does not stick (?)

### ISSUE THREAD

**Issue by ooosssay** [movie-web/movie-web#247]
### What happened?

When scrolling up or down can get the movie drop-down button off

### Steps to reproduce?

Scrolling down or up on homepage

### Other relevant information

![IMG_5003](https://user-images.githubusercontent.com/129241633/229365763-042676c5-c57c-4415-9972-9c175cca5db1.jpeg)
![IMG_5004](https://user-images.githubusercontent.com/129241633/229365765-ce57dac4-34a6-481e-98b4-8b73fb0436cf.jpeg)

**Comment by mrjvs** [comment]
What browser?

**Comment by ooosssay** [comment]
Forgot to mention but safari

**Comment by mrjvs** [comment]
The backdroppable dropdown component should be modified so it only does it when the dropdown is active.
Also begs the question if we still need it, knowing the upcoming changes

**Comment by castdrian** [comment]
I think this one is just fixed, dropdown went poof, cc @mrjvs

**Comment by mrjvs** [comment]
correct, this has been fixed in v4 branch
