### ISSUE TITLE
[Bug]: no subtitles for some tv shows

### ISSUE THREAD

**Issue by mcbravey** [movie-web/movie-web#249]
### What happened?

the button for english subtitles is available but no subtitles get shown while i click on it
as if the subtitles are hidden
this is not the case for me on every tv show. just a select few

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

search spy family
click on first entry
go to captions
select english
no subtitles

### Other relevant information

spy family: https://movie-web.app/media/JW-show-283022/292506/6530205
peter grill: https://movie-web.app/media/JW-show-225119/235585/4333704
these are the two i encountered

**Comment by frost768** [comment]
This is because of the subtitle file. It is not properly formatted. This is fixed in the new subtitle system.

**Comment by frost768** [comment]
Fixed with the latest release
