### ISSUE TITLE
[Bug]: The Scrub bar circle sometimes is low quality

### ISSUE THREAD

**Issue by ooosssay** [movie-web/movie-web#251]
### What happened?

The scrub bar circle when watching a video would sometimes be pixelated.

### What browsers are you seeing the problem on?

Safari

### Steps to reproduce?

1) Start the video
2) Scrub through the scrub bar
3) The scrub bar circle being low quality

### Other relevant information

![IMG_5008](https://user-images.githubusercontent.com/129241633/230256590-5e540af8-a6a4-4537-b77f-182ac58dff54.jpeg)

**Comment by zisra** [comment]
Cannot reproduce, what type of device are you using @ooosssay ?

**Comment by ooosssay** [comment]
iPad. @zisra

**Comment by mrjvs** [comment]
cannot reproduce, closing

**Comment by mrjvs** [comment]
> Can reproduce on iPad

added for investigation to v4. if we cant find an easy fix, its considered a browser bug, out of scope

**Comment by binaryoverload** [comment]
No complaints about this since, closing
