### ISSUE TITLE
[Bug]: Controls not showing on Chromebook

### ISSUE THREAD

**Issue by TheGloriousDuck** [movie-web/movie-web#253]
### What happened?

I am unable to see the bottom controls on a Chromebook.

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

1. Navigate to a show or movie on Chrome on a Chromebook.

### Other relevant information

This is a big issue for me as I cannot pick a specific episode since the menu is on the bottom controls area.
![image](https://user-images.githubusercontent.com/43049985/230733112-6bea3d03-57c3-42ef-b739-83930abf6601.png)

**Comment by frost768** [comment]
This is probably related to #209

**Comment by TheGloriousDuck** [comment]
> This is probably related to #209

Most likely. Should I close this?

**Comment by mrjvs** [comment]
Let's keep it open for now, as the issue in #209 is very specific to safari. A fix has already been made for the new upcoming version. When that releases you can verify if that also fixes your problem

**Comment by mrjvs** [comment]
@TheGloriousDuck latest update has had a solution for the problem, can you check if it has fixed it for you?

**Comment by TheGloriousDuck** [comment]
Can confirm the problem has been fixed. Thanks!

**Comment by TheGloriousDuck** [comment]
Thought the problem was fixed but turns out it has not been.

It is definitely still an issue with the controls being outside of the viewport. because I can press tab multiple times and then enter to fullscreen, and then I can see all the controls fine.

**Comment by mrjvs** [comment]
possibly related to #209
