### ISSUE TITLE
[Feature]: foldable support (flex mode)

### ISSUE THREAD

**Issue by castdrian** [movie-web/movie-web#258]
### What feature do you want to add?

first off, if this is out of scope, please close this issue, I am aware that is this more of a niche request if anything.

What I would like, is if the responsive design would account for foldable devices, for instance when in "flex mode" (half folded) most video players that support this, move the video to one side of the folded screen and the player controls to the other one.

### Why do you want to have this feature?

Whilst ONE UI does it's best to simulate video player controls, those don't usually work that well when they're not actually the real controls.

### Anything other details to share?

I'm not sure if all browsers provide compatible web apis, I however know that Edge does, and chrome as well I think
https://blogs.windows.com/msedgedev/2020/09/14/introducing-dual-screen-foldable-web-apis/

**Comment by mrjvs** [comment]
Thanks for the feature suggestion, but none of the contributers and project maintainers have a foldable device. Making very hard to develop for. So for now, this is considered out of scope.

**Comment by castdrian** [comment]
> Thanks for the feature suggestion, but none of the contributers and project maintainers have a foldable device. Making very hard to develop for. So for now, this is considered out of scope.

I would just like to let you know that you can use an AVD for debugging no physicaldevices are needed, but alas, I respect the decision and am aware that it is niché at the moment
