### ISSUE TITLE
Please create a new self-hosted Netfilm

### ISSUE THREAD

**Issue by lamhoang1256** [movie-web/movie-web#259]
Hello movie-web. I am author of [Netfilm](https://github.com/lamhoang1256/netfilm)
And I see movie-web using my api. Movie-web and some of its forked versions are call around 100-150k requests per month in my server, which is causing my server to slow down and my Vercel bills to increase. That affects quite a lot on Netfilm. Please either stop using my API or create a new self-hosted one to help me 🙏.
Thank you for your interest in Netfilm, and I hope you can help me solve this problem soon ❤️

**Comment by mrjvs** [comment]
Hey, I apologize for the negative effect we've had on your API.
I hope your vercel and firebase bills aren't too bad.

I will disable the netfilm provider today, and it will be shipped with next release.
We hope to publish a release this weekend.

We unfortunately don't have a way to stop outdated selfhosted movie-web instances from using the netfilm provider. (most instances never update)
However if you make a simple breaking change to the API, then the selfhosted instances will be forced to update (which will have the netfilm provider disabled).
That should get rid of all movie-web traffic on netfilm.


If you have any further questions or suggestions, feel free to ask.
PS: please keep the issue open until I've disabled the provider, just to make sure that I won't forget about it

**Comment by mrjvs** [comment]
@lamhoang1256 release has been deployed. version 3.0.10 and onwards wont have any more netfilm support.

**Comment by lamhoang1256** [comment]
@mrjvs Thank you for your prompt response and for quickly resolving the problem for me 😍. I really enjoy the **movie-web** project, but unfortunately, I do not have the financial means to support such a large-scale project like yours. I also hope that removing the **Netfilm** provider will not significantly impact the movie-web experience. Once again, thank you for your assistance, and you may now close this issue.  👍
