### ISSUE TITLE
[Feature]: setting to change default state of searchbar dropdown

### ISSUE THREAD

**Issue by castdrian** [movie-web/movie-web#263]
### What feature do you want to add?

As discussed in the settings modal PR, here a seperate issue, It would be nice to either be able to change the drop down configuration default to choose whether it's set to series or movie, or to at least have it remember the last state it was left in

### Why do you want to have this feature?

I personally don't really watch movies so I would prefer to be able to configure it to default to series instead.

### Anything other details to share?

It's just a very miniscule QoL request

**Comment by mrjvs** [comment]
tracked by #337. closing
