### ISSUE TITLE
[Feature]: Choosing version of movie

### ISSUE THREAD

**Issue by TheGloriousDuck** [movie-web/movie-web#265]
### What feature do you want to add?

Sometimes movies will have different cuts, like a theatrical or director's cut. There should be a button (kind of like the episodes button when you are watching a series) that will allow you to pick a specific version.

### Why do you want to have this feature?

People may prefer to watch one version over another. Personally, I wanted to watch the Theatrical Cut of Donnie Darko but accidentally watched the Director's Cut instead.

**Comment by zisra** [comment]
I really don't think this is possible as movie-web don't manage content

**Comment by curatedcode** [comment]
If above is not possible maybe add the length of the movie next to the year so you can see it while browsing

**Comment by mrjvs** [comment]
considered out of scope for the project. too difficult to do for little benefit.
