### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by NotoriousYeet** [movie-web/movie-web#285]
### What feature do you want to add?

Support for Samsung TV internet browser

### Why do you want to have this feature?

So I can watch on my Samsung Tv rather than a PC or phone

**Comment by mrjvs** [comment]
Smart TV's and older browsers are not in scope of the project.
Use chromecasting if you want to view something on a TV.

**Comment by FeetOnTheGroundTx** [comment]
Thank you!


Sent from Yahoo Mail for iPhone


On Thursday, April 27, 2023, 9:43 AM, mrjvs ***@***.***> wrote:




Closed #285 as completed.
