### ISSUE TITLE
[Feature]: Bigger range for sub delays

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#287]
### What feature do you want to add?

range slider should stay the same. but the number on the right should be editable by clicking on it.
Should be editable to even outside the sliders range

### Why do you want to have this feature?

some subtitles are delayed more than 10 seconds

### Anything other details to share?

Season 11 Episode 3 of south park is an example of +12 seconds delay

**Comment by zisra** [comment]
I think all slider texts should be an input anyways, thet looks like input boxes
<img width="86" alt="Screenshot 2023-04-30 at 3 42 19 PM" src="https://user-images.githubusercontent.com/100528712/235375350-222c350d-bf59-4e36-8585-520c9beb3b01.png">

**Comment by frost768** [comment]
Would -20, 20 be ok?

**Comment by lem6ns** [comment]
i feel like it should be a slider with a limit, but clicking on the number allows you to change it to anything

**Comment by zisra** [comment]
https://github.com/movie-web/movie-web/assets/100528712/cfd0a7e1-3fab-4f8a-bdcf-99505c553742

Something like this

**Comment by yuriy636** [comment]
Could the range be increased while the "overhaul" is being worked on?
Been watching a show with 12s delay and it sucks.

**Comment by JipFr** [comment]
This has been added in version 4, for which there is no ETA. Just now that it’ll be there!

**Comment by mrjvs** [comment]
This has been fixed in the latest version: #530
(you can type in custom values)
