### ISSUE TITLE
[Feature]: Chromecast support

### ISSUE THREAD

**Issue by JamesHawkinss** [movie-web/movie-web#3]
Can use this lib: https://castjs.io/

**Comment by ARR4NN** [comment]
I have added this support in my own version

**Comment by JamesHawkinss** [comment]
Can you provide an example of this?

**Comment by ARR4NN** [comment]
![image](https://user-images.githubusercontent.com/70060472/126207935-ce4c7a95-14cf-4ce9-a53c-4f452aa0f528.png)

**Comment by ARR4NN** [comment]
Im working on a custom video player so it can be implemented into the actual player

**Comment by ARR4NN** [comment]
![image](https://user-images.githubusercontent.com/70060472/126464444-9b6d4a93-1e64-41e2-bb98-060f5c941a5a.png)
i added this

**Comment by JamesHawkinss** [comment]
Waiting on #61

**Comment by mrjvs** [comment]
resolved with latest release
