### ISSUE TITLE
Request feature

### ISSUE THREAD

**Issue by vjrmy** [movie-web/movie-web#313]
1. Please add more source like from FlixHQ, loklok, and Sorastream.
2. please add more default language subtitles like indonesian

**Comment by lem6ns** [comment]
1. flixhq already implemented, loklok used to be supported but broke (they put CORS to only their domain afaik, sorastream I have no idea
2. subtitles are provided by the source, not us

**Comment by calvinti12** [comment]
flixhq Stop working one day now

**Comment by mrjvs** [comment]
sorastream has been moved into a seperate issue: #314.
subtitles already have a corresponding issue: #124

closing, issue has been split into other issues

**Comment by vjrmy** [comment]
@mrjvs @lem6ns if you try http://justchill.tv/ that website use flixhq, loklok, and superstream too. I can watch Super mario bros 2023 in JustChill.tv but in movie-web.app no video source about super mario bros 2023
