### ISSUE TITLE
[Feature]: "Episode selector" icon is not intuitive

### ISSUE THREAD

**Issue by yuriy636** [movie-web/movie-web#316]
### What feature do you want to add?

Change the icon to either:

- one representing a list or something like that.
- one representing a stack, with 3 solid rectangles (like the Netflix one) instead of 2 outlined (current)

### Why do you want to have this feature?

It took me a while to understand that the button that for me meant "popup" actually opens the episode selector. Found it by just trying pressing all the buttons.

**Comment by mrjvs** [comment]
tracked by #338. closing
