### ISSUE TITLE
[Feature]: IPFS mirror support

### ISSUE THREAD

**Issue by Martinligabue** [movie-web/movie-web#317]
### What feature do you want to add?

As this is a static site, it can also be hosted on IPFS, reducing the load on the main site and sharing it with P2P between those using IPFS (via Brave or the IPFS app).

### Why do you want to have this feature?

It would make the site more resilient to higher loads and censorship, and would not change the behaviour for regular users, as they would only be redirected to IPFS if the client supported it.

### Anything other details to share?

Via IPNS, it could also have a static address, but be able to update the content of the static website as it is updated.

**Comment by mrjvs** [comment]
not in scope of the project
