### ISSUE TITLE
[Feature]: Video quality selector

### ISSUE THREAD

**Issue by nimagp** [movie-web/movie-web#318]
### What feature do you want to add?

An option to select the quality of the video played. Possibly a sub-menu of the instance selected or another option in the main playback settings

### Why do you want to have this feature?

Not all connections support 1080p playback :)

### Anything other details to share?
depends on https://github.com/movie-web/providers/issues/2 and the design

**Comment by mrjvs** [comment]
this is already being worked on, but apparently this is the first issue opened about it.
Ill keep it open for progress tracking

**Comment by nimagp** [comment]
@mrjvs as an additional suggestion, would you please consider providing the download link based on the quality selected? (If not already planed)

**Comment by thehairy** [comment]
> @mrjvs as an additional suggestion, would you please consider providing the download link based on the quality selected? (If not already planed)

The download link comes from the played source, so if you select 360p, the download should be 360p as well.

**Comment by mrjvs** [comment]
This has been fixed in the latest version: #530
