### ISSUE TITLE
[Bug]: Language doesnt get loaded after reload

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#320]
### What happened?

my chosen language doesnt get loaded back in

### What browsers are you seeing the problem on?

Firefox

### Steps to reproduce?

1. choose german in settings
2. see that it changed to german
3. reload
4. its english again, but settings menu still says german

### Other relevant information

language gets stored in local storage, but does not get loaded

**Comment by frost768** [comment]
Something like this fixes it but should we separate language from settings?
```js
i18n.changeLanguage(
  (
    JSON.parse(
      localStorage.getItem("mw-settings") ?? "{language: 'en'}"
    ) as MWSettingsData
  ).language
);
```

**Comment by mrjvs** [comment]
> Something like this fixes it but should we separate language from settings?
> ### i18n.ts
> ```ts
> i18n.changeLanguage(
>   (
>     JSON.parse(
>       localStorage.getItem("mw-settings") ?? "{'language': 'en'}"
>     ) as MWSettingsData
>   ).language
> );
> 
> export default i18n;
> ```

Language shouldn't be separated from settings, but you use the settings versioned store directly. That will avoid having to parse it manually

**Comment by frost768** [comment]
So having it in a component like App.tsx? Cause I don't think i can access settings without context

**Comment by mrjvs** [comment]
You can import `SettingsStore` from `@/state/settings/store.ts` and call `.get()` outside of react

**Comment by frost768** [comment]
Please assign this task to me on the board. I've opened a pull request without assignment.
