### ISSUE TITLE
[Feature]: Make Default Subtitle English

### ISSUE THREAD

**Issue by deadcoder0904** [movie-web/movie-web#323]
### What feature do you want to add?

Default Subtitle to be English

### Why do you want to have this feature?

Because everytime I watch, I need English Captions.

I need to manually select them now but would like it to be automatically selected since a large percentage of population anyways turns on English Captions.

If someone wants no subtitles, they can easily turn it off.

### Anything other details to share?

Right now, I have to select it, then it downloads so I have to pause the video sometimes when its slow.

If it was a default state, then I wouldn't need to go through the whole process every time.

This is really useful for Kdramas when I don't speak or understand Korean but they do have high-quality shows.

**Comment by frost768** [comment]
use settings to set default subtitle language

**Comment by deadcoder0904** [comment]
whoops, somehow i missed it.

but curious why this isn't enabled by default or at least like youtube when cc is selected... it chooses english. that'd be a better ux (at least for me) but this works for me.
