### ISSUE TITLE
[Feature]: Next Episode

### ISSUE THREAD

**Issue by Tazi0** [movie-web/movie-web#329]
### What feature do you want to add?

When an episode has completed, it would be nice to automatically go (if it exists) to the next episode

### Why do you want to have this feature?

For an improved user experiance

### Anything other details to share?

it should be indicated that it will move to the next episode, feel free in what ever. I suggest a small notification or such

**Comment by zisra** [comment]
Duplicate of #140 but still a good suggestion

**Comment by Tazi0** [comment]
> Duplicate of #140 but still a good suggestion
@zisra thanks for the reply, i must've not looked properly

**Comment by binaryoverload** [comment]
Closed this as non-planned as it's a duplicate, and I don't want any confusion about whether it's completed or not. At the time of writing this feature is tracked by #140 and is not complete
