### ISSUE TITLE
[Bug]: Chromecasting shows subtitles locally– not casted to screen

### ISSUE THREAD

**Issue by slytter** [movie-web/movie-web#330]
### What happened?

When I cast to my Chromcast and enable subtitles, the subtitles are displayed in my browser instead being casted.

<img width="673" alt="image" src="https://github.com/movie-web/movie-web/assets/15888906/6f4dcb24-2a11-47ec-9bb3-3c58e580d57b">

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

1. Cast anything from Chrome to a Chromecast
2. Enable subtitles
3. Subtitles are shown in the browser

### Other relevant information

Might be able to do a PR myself, but I've never worked with the chromecast API before. Any help or clues are appreciated :)

**Comment by lem6ns** [comment]
known, see #147

**Comment by mrjvs** [comment]
tracked by #335, closing
