### ISSUE TITLE
[Feature]: parallel content search

### ISSUE THREAD

**Issue by castdrian** [movie-web/movie-web#332]
### What feature do you want to add?

instead of running through the providers synchronously, display a universal loading screen and query all providers in parallel until one of them returns a result

### Why do you want to have this feature?

with the growing number of providers it takes quite a while to run through all of them for content that isn't available on the highest ranked providers

### Anything other details to share?

no, but I like filling out the last question either way

**Comment by zisra** [comment]
Use web workers!

**Comment by JamesHawkinss** [comment]
> Use web workers!

Jon's scrapers used web workers, there's some disadvantage of using them but I can't remember. Possibly not compatible with all browsers. Not sure.

**Comment by castdrian** [comment]
compat seems fine
https://caniuse.com/webworkers

**Comment by mrjvs** [comment]
It's not really neccesary to use webworkers, The promise API can handle this kinda stuff fine.

However my concern with this is the amount of requests, we're already hitting our limits with workers, having much more requests would not do us any good.

Superstream is amazing, it has most of the popular content. The more niche stuff does take a while however.
If you do three parallel scapers, it would do three times the amount of worker requests if it returns the final result at the first one. A 300% increase is a lot which I don't think we can afford right now.

I'd rather it be a bit slower, than upping the theoretical cost by a factor of 3.

**Comment by mrjvs** [comment]
There was talk about giving users the ability to overwrite the default provider ranking in the settings. It can be a potentional solution without having a major effect on our worker usage.

**Comment by mrjvs** [comment]
closing due to the issues brought up above
