### ISSUE TITLE
[Bug]: Chromecasting unfinished

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#335]
### What happened?

- chromecasting doesnt receive subs
- chromecasting doesnt start at where the video left off, it starts at the beginning
- chromecasting doesnt support HLS

### What browsers are you seeing the problem on?

Firefox

**Comment by FelixBoehme** [comment]
Will the casting code be affected by the planned video player refactoring?
If not I have a fix for the first two problems (haven't gotten around to the third issue).

I'd be happy to open a pull request if this can be used for the upcoming Version 4.

**Comment by mrjvs** [comment]
This has been fixed in the latest version: #530

**Comment by jrvgr** [comment]
Would like to reopen, Our chromecast unit isn't showing any. Would like to debug but no idea how
