### ISSUE TITLE
[Bug]: Native subtitle track support

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#336]
### What happened?

we have a custom subtitle renderer, it's great but it causes some issues.

The following usecases need native html subtitle tracks:
 - [ ] ios safari on iphone fullscreen
 - [ ] Picture in Picture chrome
 - [ ] Picture in Picture firefox (this may not be possible to implement)
 
 this resolves the following:
 - [ ] #237 

### What browsers are you seeing the problem on?

Other (tell us in input box below)

**Comment by arjpar** [comment]
Any update on this issue?

**Comment by mrjvs** [comment]
no

**Comment by mrjvs** [comment]
This has been fixed in the latest version: #530
