### ISSUE TITLE
[Feature]: Reimagine homepage

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#337]
### What feature do you want to add?

the homepage should be reimagined, current issues:
 - movie or series selection is slow and often forgotten to do. leading to slowdowns and confusion.
 - navigation is not responsive
 - we need a place for an "about movie-web" page

### Why do you want to have this feature?

see issues above

**Comment by zisra** [comment]
Settings button and social links should be separated, especially if we want to add a donation link

**Comment by GuiiHtto** [comment]
Would be great to have a movie page, when you select it in the search with trailers, sinopse, other movies like it.

**Comment by mrjvs** [comment]
This has been fixed in the latest version: #530
