### ISSUE TITLE
[Feature]: A settings page (instead of modal)

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#339]
### What feature do you want to add?

A settings page, not a modal.

### Why do you want to have this feature?

settings modal is not expandable, it should be a full page with navigation.

**Comment by zisra** [comment]
Does this not go against the simplicity thing?

**Comment by mrjvs** [comment]
> Does this not go against the simplicity thing?

Making it more organized does not go against the goal of simplicity

**Comment by mrjvs** [comment]
This has been fixed in the latest version: #530
