### ISSUE TITLE
[Feature]: Account syncing

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#344]
### What feature do you want to add?

Add a way to sync multiple devices to each other, so both your phone and your laptop have the same progress saved and bookmarks.

### Why do you want to have this feature?

A lot of users requested it.

### Anything other details to share?

About the account system:
 - completely optional for hosting, if you dont have it configured it will work seamlessly without it.
 - The account creation process needs no personal information, to keep yourself anonymous.
 - Account system is opt-in, the application works fully without having an account.
 - application settings: users can choose a different backend. This is useful for people who want to own their own data
 - application settings: users can choose different sets of workers. Again, useful for people who want to own their won data
 - For selfhosters: the officially hosted backend will be default
 
About data storage:
 - If account has not been mutated for a long time, it will be scheduled for deletion
 - application settings: you can export and import all user data
 - application settings: you can delete your account (if only 1 device is linked)
 - Data is stored offline first, meaning it gets stored for sure offline. then gets uploaded with retries when possible.
 
About authentication:
 - application settings: you can logout devices from an account
 - on signup, a pass phrase is generated. This will act as a password and username at the same time.
 - on login, the pass phrase can be exchanged for an access token that doesn't expire.
 - application settings: Passphrase can be regenerated

About signup flow:
 1. Click "sync to cloud"
 2. From options "login" or "create account" choose "create account"
 3. get prompted with a passphrase, with strong direction to save this somewhere
 4. Choose an account name and make an picture (color + icon combination)
 5. Name your device
 6. Done!

About login flow:
 1. Click "sync to cloud"
 2. From options "login" or "create account" choose "login"
 3. Input passphrase for the account.
 4. See your profile picture and choose a device name
 5. Done!
 

Still unknown factors:
 - Database technology hasnt been chosen
 - The passphrase could potentially be stored on the client encrypted for easy retrieval in case it goes missing

**Comment by slytter** [comment]
Could also use [Gun](https://gun.eco/) for a decentrialized authentication and storage. This would remove the need for any backend to be associated with movie-web, and would most likely work flawless with selfhosting as well.

I feel like a service like movie-web is the perfect app for using a db like gun. And I think it is pretty easy to setup ([how to create users](https://gun.eco/docs/User)).

**Comment by mrjvs** [comment]
gun still needs a central server to work properly. Also decentralized storage has inherit problems.
Gun makes it easy but still has problems that they cant work around. Like deleting data.

Plus gun's access control makes it quite difficult to share data between multiple users.
Lots of manual work with encryption magic.

I prefer to stick to what the team is familiar with instead of using something new and fancy.

**Comment by mrjvs** [comment]
This has been fixed in the latest version: #530
