### ISSUE TITLE
[Feature]: Skip button for: intro, outro, credits

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#347]
### What feature do you want to add?

A skip button for: intro, outro, credits.

We don't have a database of these, so to do this we will need to do the following:
 - backend database of user submitted skippable segments
 - upvote/downvote button after using a skip, the higher the votes, the more often it gets shown to people
 - a UI to submit skippable segments

### Why do you want to have this feature?

It's a frequent suggestion from users, mostly for TV shows and anime (#346)

### Anything other details to share?

its very similar system to sponsorblock, see: https://blog.ajay.app/voting-and-pseudo-randomness-or-sponsorblock-or-youtube-sponsorship-segment-blocker

**Comment by AYA-123** [comment]
https://openaccess.thecvf.com/content/WACV2021/papers/Hao_Intro_and_Recap_Detection_for_Movies_and_TV_Series_WACV_2021_paper.pdf looks interesting - but not a database/api

**Comment by binaryoverload** [comment]
Having a community database of skips is now, in my opinion, incompatible with the "decentralised" nature of movie-web as it is currently
