### ISSUE TITLE
[Feature]: swipe gestures

### ISSUE THREAD

**Issue by castdrian** [movie-web/movie-web#355]
### What feature do you want to add?

the video player should support swipe gestures on touch input enabled devices to ie. control the volume

### Why do you want to have this feature?

UX

### Anything other details to share?

swipe gesture for brightness alongside volume would be great as well but I'm not quite sure how feasible that is to implement

**Comment by mrjvs** [comment]
With web tech, I rarely see this done well. It's almost always janky and not performant.

Plus I don't think you can adjust brightness with web apis.

I think this will fit better in a native app. Not a web app.
