### ISSUE TITLE
[Feature]: Filter out unreleased movies on search

### ISSUE THREAD

**Issue by thehairy** [movie-web/movie-web#357]
### What feature do you want to add?

Movies that are not yet released should not be included in the search result.

### Why do you want to have this feature?

This site is not a movie info site like imdb, but an actual site to watch movies. Nobody cares about unreleased stuff.

**Comment by castdrian** [comment]
Some people might like to bookmark yet to be released media

**Comment by thehairy** [comment]
> Some people might like to bookmark yet to be released media

It shall be a setting then.

**Comment by mrjvs** [comment]
> > Some people might like to bookmark yet to be released media
> 
> It shall be a setting then.

movie-webs settings page after every issue is implemented: <img src="https://cdn.discordapp.com/attachments/342737556250689546/1120358685768683570/image.png" />

**Comment by zisra** [comment]
<img width="793" alt="Screenshot 2023-06-21 at 1 13 13 PM" src="https://github.com/movie-web/movie-web/assets/100528712/e7ff2623-dbac-42c9-8255-93ad8aaac535">
Instead filter out these bad boys

**Comment by kacperkwapisz** [comment]
@mrjvs did anyone start to work on this?

**Comment by mrjvs** [comment]
> @mrjvs did anyone start to work on this?

no, it's not in the roadmap for the next version. So even if you PR it, it won't be merged.
You can check https://github.com/orgs/movie-web/projects/1 for which issues are for the next version.

**Comment by binaryoverload** [comment]
This issue is open for takers, we do handle this better by not showing the release year if it's 0. I think filtering out unreleased movies is the solution
