### ISSUE TITLE
[devenv]: switch package manager to pnpm

### ISSUE THREAD

**Issue by castdrian** [movie-web/movie-web#360]
### What feature do you want to add?

migrate the project to use pnpm as package manager

### Why do you want to have this feature?

apparently there is a number of issues that have arisen throughout the usage of yarn

### Anything other details to share?

whilst yarn is generally the popular option, pnpm outperforms both yarn and npm by quite a noticeable margin
https://pnpm.io/

**Comment by mrjvs** [comment]
useful link: https://pnpm.io/only-allow-pnpm

**Comment by mrjvs** [comment]
This has been fixed in the latest version: #530
