### ISSUE TITLE
[devenv]: use semantic-release to automate releases and versioning

### ISSUE THREAD

**Issue by castdrian** [movie-web/movie-web#363]
currently, the semantic versioning is performed manually and releases are being created on the dev branch.

Ideally semantic-release should be used which automates versioning, changelogs and github releases every time a commit is pushed to a specified release branch

**Comment by binaryoverload** [comment]
Since this will be pretty complex to manage due to being an open-source project and unable to moderate commit messages, this won't help us.

Also, the way we currently release is not complex and doesn't require automation.
