### ISSUE TITLE
[Bug]: The hosted version prevents web inspect

### ISSUE THREAD

**Issue by nimagp** [movie-web/movie-web#370]
### What happened?

The web page uses debug statements to make the browser crash

### Steps to reproduce?

Open inspect page

### Other relevant information

Why?
What does the alert () with text "Leave us alone :(" mean and how it is displayed if there is no alert() or the string hardcoded into the code present in the repository?

**Comment by zisra** [comment]
Not a bug, see #264

**Comment by mrjvs** [comment]
like @zisra said, not a bug. check my comment on the issue they linked. Closing.
