### ISSUE TITLE
[Feature]: multi-lingual audio support

### ISSUE THREAD

**Issue by spidy2356** [movie-web/movie-web#378]
### What feature do you want to add?

add a feature to change the audio of movies and tv shows to my native language if they are available, just like Netflix.
add an audio tab in the setting just after the caption button, from which we can select different audio if they are present.
![Screenshot 2023-07-05 001301](https://github.com/movie-web/movie-web/assets/101243689/9476060b-c24a-47d0-9cc9-917bebf0f770)
 like my screenshot.

### Why do you want to have this feature?

in this modern era of movies and tv shows, native audio language prefer is most common. so the feature is most necessary.

### Anything other details to share?

no.

**Comment by castdrian** [comment]
there is no feasible way of doing this. your only bet is to pr a provider that provides dubs in the language you want once the providers repo is done and open for prs.

**Comment by spidy2356** [comment]
@castdrian my demanded language is Hindi. The SS was just an example. But don't understand how to do that.
Do u mean what I need is not possible?

**Comment by binaryoverload** [comment]
While this is something we would like to be able to do, the way this website works means that we need a provider out there which provides movies/shows in different languages to be able to do this, which is what @castdrian is talking about.

Simply put, this isn't something we can do until a provider is found with multiple languages.
