### ISSUE TITLE
[Bug] Episode and Caption popovers hidden under mobile nav

### ISSUE THREAD

**Issue by binaryoverload** [movie-web/movie-web#379]
### What happened?

On mobile landscape, without being full screen the popovers go under the top bar making it impossible to select a different season or edit caption settings.

Going into full screen fixes the issue.

![Screenshot_20230705-130257](https://github.com/movie-web/movie-web/assets/15330699/29c5846f-2947-4332-b282-a308b52159f2)
![Screenshot_20230705-130506](https://github.com/movie-web/movie-web/assets/15330699/f38195b7-8871-43cf-b183-18e83f4c76fc)

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

1. Open an episode in Android Chrome landscape
2. Open episode selector or captions menu
3. Be unable to click top elements
4. Profit

### Other relevant information

Relating to issue #369

**Comment by en1gma713** [comment]
This issue is also present on the iOS versions of both Safari and Firefox.

**Comment by mrjvs** [comment]
This has been fixed in the latest version: #530
