### ISSUE TITLE
[Bug]: Playing the wrong episode

### ISSUE THREAD

**Issue by J4mez** [movie-web/movie-web#380]
### What happened?

When trying to watch family guys s21 e19, episode 1 is loaded instead. It seems to be a problem with the provider "GOmovies". 

### What browsers are you seeing the problem on?

Firefox

### Steps to reproduce?

1. Go to family guys s21 e1 and watch a few seconds
2. Go to family guys s21 e19 and watch a few seconds, notice that it's the same. 
3. You can also verify which is the real episode on IMDB or similar.

**Comment by lem6ns** [comment]
We don't have control on the content provided. Nothing we can do about it

**Comment by zisra** [comment]
We have control over how we get the content and our code may have flaws in finding the right video, such as title matching and episodes selection using html scraping

**Comment by J4mez** [comment]
There were a few times where providers got skipped because they don't have the right episode available, that's why I opened this issue. If this is expected behavior or already a known issue feel free to close this.
