### ISSUE TITLE
Self hosted database

### ISSUE THREAD

**Issue by olafur-palsson** [movie-web/movie-web#381]
There are a couple of tickets that want synced accounts and tbh I'm interested in them.

So of course we're not going to host anything except static sites so I'm thinking we allow people to log into their own firebase instance. 

Keys stored in localstorage and such.

**Comment by mrjvs** [comment]
We've discussed database solutions internally a lot, however I realize there isnt a lot of info on github on what the plan is. So ill lay it out here:

We're gonna have a central nodeJS app for #344 and #347.
The API server hosted by us will be default on all instances, including selfhosted.
However the user can go into settings and change the URL of the API to point to whichever instance they want, like a selfhosted version.

This means people can store their data on their own server, but still keep using the officially hosted website.
But it also works the other way around: people can host their own website, but keep using our database.

---

To add on to that, the API is completely optional. If the server goes down, it will keep functioning as expected, just without the database features. This means if issues do happen with hosting or money, we can just disable it and we won't have issues.

While the firebase idea is neat. This API server plan is the one we will go with.
