### ISSUE TITLE
[Bug]: Non of the sources work on selfhosted instance

### ISSUE THREAD

**Issue by OmriOn** [movie-web/movie-web#382]
### What happened?

I just set up a self-hosted instance of movie-web and the sources don't work. even on shows like doctor who, which I know worked on the main instance. 
![image](https://github.com/movie-web/movie-web/assets/76548146/7109e255-97dd-4ec1-807b-3b4045b8d818)
![image](https://github.com/movie-web/movie-web/assets/76548146/57dcfc54-6fc2-426a-87aa-9b2c42bc0b06)
one exception is the show "Lockwood & co" where it can't find a working source apart from something called "remote stream" 
![image](https://github.com/movie-web/movie-web/assets/76548146/16e48880-8b55-4303-b83a-2dde2bbf0f33)

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

1. Self-host a movie-web instance.
2. try to watch a movie or show.

**Comment by castdrian** [comment]
there's no support for self hosting, furthermore not enough info i.e. checking the responses of the requests etc..

**Comment by zisra** [comment]
Try. using yarn instead of npm or pnpm if you haven't yet

**Comment by OmriOn** [comment]
![image](https://github.com/movie-web/movie-web/assets/76548146/1770ddf3-399a-4ee3-a662-969b63b682ce)
here are the logs

**Comment by OmriOn** [comment]
> Try using yarn instead of npm or pnpm if you haven't yet

how do i do that? im using cloudflare workers and netlify

**Comment by zisra** [comment]
Can you drop a link to your instance?

**Comment by OmriOn** [comment]
> Can you drop a link to your instance?

https://movie-omri.netlify.app/

**Comment by mrjvs** [comment]
I'm fairly certain this a cloudflare worker configuration problem.
Remotestream is the only source that doesnt use the worker, hence its the only one that worked.

As said before, we don't provide support for selfhosted instances.
Double check your configuration, try it with or without trailing slashes on the url.
Check example.env, and maybe even try the noob-friendly selfhosting guide.

closing

**Comment by zisra** [comment]
You need to add a `https://` to the beginning of your cloudflare worker @OmriOn

**Comment by OmriOn** [comment]
> You need to add a `https://` to the beginning of your cloudflare worker @OmriOn 

I'll try it

**Comment by ClassickTech** [comment]
It has nothing to do with the cloudflare script. It was somehow borked on the releases after 3.0.15. Use that one and your sources will work again. I compared that version and the latest version 3.2.1 and I think the culprit is somewhere in the index-a5d2672e.js file.
