### ISSUE TITLE
[Bug]: Captions not loading

### ISSUE THREAD

**Issue by deadcoder0904** [movie-web/movie-web#386]
### What happened?

i am trying to watch `alice in borderland (japanese series)` & i tried to load `english` captions but it just wouldn't load.

also, some subtitles really have sync issues like audio moving ahead of video. for ex, `sympathy for mr. vengeance`

### What browsers are you seeing the problem on?

Chrome

**Comment by zisra** [comment]
- I did a bit of research around the captions, and found that the client makes a request to this URL when loading captions:
https://rough.isra.workers.dev/?destination=https://mbpimages.chuaxin.com/movie_box/tv/srt/1/8/14398/1024596/Alice.in.Borderland.S01E01.1080p.NF.WEB-DL.DD+5.1.x264-iKA_English_2441807_5fd33a8e5d415.srt
As you can see, this is an issue with the captions url the providers give us which is not something we can fix
- Caption delay is inevitable. We can't do anything to fix it but you can set a delay yourself by clicking "Customize" under the captions menu

**Comment by deadcoder0904** [comment]
@zisra don't you download the caption once & load it or is the caption streaming as well?

**Comment by deadcoder0904** [comment]
oh so it's just out-of-sync subtitles. got it.
