### ISSUE TITLE
[Bug]: Premid presence for shows incorrect episode number for shows

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#389]
### What happened?

I was watching arcane S1E6. but on my premid presence it showed S1E1 instead.

link: https://movie-web.app/media/tmdb-show-94605/134187/3246867

### Steps to reproduce?

1. click link above
2. have premid installed
3. check discord presence, its the wrong episode

### Other relevant information

seems to be caused by line 260: https://github.com/PreMiD/Presences/blob/main/websites/M/movie-web/presence.ts#L260
it compares with itself, so conditional on the filter is always true. hence the first episode is selected for the number.

**Comment by mrjvs** [comment]
@Jordaar, you are more familar with the premid presence git flow. could you issue a fix for it?
See "other relevant information" on where the bug happens, should be a one-liner to fix.

if you dont want to thats also fine, just lmk.

**Comment by Jordaar** [comment]
I'll check it out

**Comment by Bloofield** [comment]
@mrjvs This bug can be closed as per the fix implemented in [PreMiD/Presences Pull Request #7615](https://github.com/PreMiD/Presences/pull/7615).

**Comment by mrjvs** [comment]
Cool, thanks for the heads up
