### ISSUE TITLE
[Bug]: Incorrect Subtitles on Specific Movie

### ISSUE THREAD

**Issue by wutv** [movie-web/movie-web#394]
### What happened?

When I watch Fifty Shades Freed on movies-web.app and click English, it loads subtitles for the wrong movie, going along the lines of "Every era has a messiah, who rules the hearts of the people, who shows them a new way of life, and who showers them with happiness. This story is not about such a Messiah." This is for a different movie (though it does sound pretty interesting, if someone could let me know which one it is)

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

1. Watch Fifty Shades Freed on superstream.
2. Select English subtitles.

### Other relevant information

Brave version info:
![image](https://github.com/movie-web/movie-web/assets/86250346/3023135b-0b75-4f84-a9d7-f0b7bcc2b2ee)

**Comment by binaryoverload** [comment]
Nothing we can do about that right now, but this issue will be resolved in version 4 where we will be dropping linked subtitles from our providers (Tracked by #321)
