### ISSUE TITLE
[Feature]: Improvements and new ideas

### ISSUE THREAD

**Issue by realgooseman** [movie-web/movie-web#396]
### What feature do you want to add?

Hi @mrjvs,

My experience has been very smooth so far. However, I got a few improvements that would be nice to have. Not expecting them to all be implemented or possible, but just to give ideas.

> **_I noted these ideas by having two particular apps in mind. [Showly](https://play.google.com/store/apps/details?id=com.michaldrabik.showly2) and [Stremio](https://play.google.com/store/apps/details?id=com.stremio.one), which are both open-source. So looking into their code might give ideas on how to proceed in the future._**

### **New ideas :**

- **_Homepage :_** Ditch movie/show dropdown menu and just leave a blank search bar. The search results are global and separated in Movie, Shows and Anime sections instead for faster discovery.

- **_Homepage :_** Adding new and featured movies/shows sections under search bar, like streaming websites (via TMDB API ?)

- **_Website :_** Adding movie/show meta details menu on the click of a movie/show instead of directly playing **_AND/OR_** meta details on the bottom-left side of the player. Like Netflix but better (including movie/episode name, synopsis, release date, IMDb/TMDB score, Rotten Tomatoes).

### **Seen in the Roadmap/feature requests and I support those features :**

- **_Video Player :_** Adding a Youtube-like toggle to enable/disable autoplay of the next episode.

- **_Website :_** Privacy-friendly account syncing (progress, favorites,...)

- **_Custom Theme :_** Light/dark base theme with custom accent color (instead of purple)

- **_Anime :_** Adding Anime to the content (ideally French subs/dubs as well)

- **_Skip button :_** For intro, outro and credits (powered by submit and vote system)

### **Some nice to haves in the future :**

- A proper Android app (F-droid/IzzyOnDroid)
- Some kind of Trakt.TV scrobbler to sync and keep track of watched content

### Why do you want to have this feature?

These features would bring Movie-web to the next level and make it very convenient for everyone.

**Comment by mrjvs** [comment]
Hey, thanks for the suggestions.
Glad you like our app so far.

We're currently working on version 4, you can see what is planned for version 4 in the github projects tab.

---

> Ditch movie/show dropdown menu and just leave a blank search bar

planned for v4, see #376 and #337 

> Adding new and featured movies/shows sections under search bar

Unfortunately, this is something we don't want to implement. For a few technical reasons, but also just for the vision of the app itself. We don't want to be a competitor to real streaming sites, rather a place to look if youre favourite streaming service doesn't have something or has something region locked.

See #311 for more details

> Adding movie/show meta details menu on the click of a movie/show instead of directly playing

Planned for version 4, see #334 

> A proper Android app (F-droid/IzzyOnDroid)

It's somewhat in preparation, we want to make the main website the best it can be first.
Issues for these are closed because it is not in scope of the current website. However it can be a new project in the future.

> Some kind of Trakt.TV scrobbler to sync and keep track of watched content

Gonna be done at some point, but other things have priority right now.

**Comment by realgooseman** [comment]
> Hey, thanks for the suggestions. Glad you like our app so far.
> 
> We're currently working on version 4, you can see what is planned for version 4 in the github projects tab.
> 
> > Ditch movie/show dropdown menu and just leave a blank search bar
> 
> planned for v4, see #376 and #337
> 
> > Adding new and featured movies/shows sections under search bar
> 
> Unfortunately, this is something we don't want to implement. For a few technical reasons, but also just for the vision of the app itself. We don't want to be a competitor to real streaming sites, rather a place to look if youre favourite streaming service doesn't have something or has something region locked.
> 
> See #311 for more details
> 
> > Adding movie/show meta details menu on the click of a movie/show instead of directly playing
> 
> Planned for version 4, see #334
> 
> > A proper Android app (F-droid/IzzyOnDroid)
> 
> It's somewhat in preparation, we want to make the main website the best it can be first. Issues for these are closed because it is not in scope of the current website. However it can be a new project in the future.
> 
> > Some kind of Trakt.TV scrobbler to sync and keep track of watched content
> 
> Gonna be done at some point, but other things have priority right now.

Thanks for the clarification, I'm excited for the future versions of Movie-web.
Glad to hear that an Android app is not excluded, and could eventually see the light of day.

**Comment by binaryoverload** [comment]
Trakt Integration is tracked by #368 - all other issues have been linked, or an explanation given as to why we're not doing it
