### ISSUE TITLE
[Bug]: Movie stated had different movie instead

### ISSUE THREAD

**Issue by MovieCat** [movie-web/movie-web#400]
### What happened?

So the movie on your cite “walking the halls” is something I wanted to watch but as soon as it starts play I notice that a different movie is playing called “Walking tall” with the rock. I want to watch the other movie so if you could get that fixed that would be fantastic 😇🙏🥰

### What browsers are you seeing the problem on?

Safari

**Comment by binaryoverload** [comment]
The issue is with the provider and the search APIs they use. Unfortunately, this isn't anything we can fix other than disabling that source.
