### ISSUE TITLE
[devops]: add CODEOWNERS.md

### ISSUE THREAD

**Issue by castdrian** [movie-web/movie-web#401]
### What feature do you want to add?

CODEOWNERS.md

### Why do you want to have this feature?

Automatically requests codeowners as reviewers on pull requests

### Anything other details to share?

nop

**Comment by binaryoverload** [comment]
We've had a discussion about this internally, and while a CODEOWNERS file can be useful for automatic reviews, at our scale it's just extra organisation we don't really need.

 Do you have a specific use case in mind?

**Comment by castdrian** [comment]
just figured it'd be useful since there aren't perms to request a review unless a review has already taken place, ie new prs just get it autoassigned, but I do agree that it's just a very negligibly useful change overall

**Comment by binaryoverload** [comment]
I will have a look at setting up a simple one that's just a blanket request to the core team, won't be too hard to setup and might help with prompting reviews

**Comment by binaryoverload** [comment]
Added CODEOWNERS in https://github.com/movie-web/movie-web/commit/606e55d5522850e310fce4f557770c9dcad5371b
