### ISSUE TITLE
[Feature]: Metastream Integration

### ISSUE THREAD

**Issue by ogamacheDev** [movie-web/movie-web#402]
### What feature do you want to add?

It would be great to have a button that creates a session in the [Metastream](https://app.getmetastream.com/) app.

### Why do you want to have this feature?

I love watching movies with friends, a quick link to Metastream would be great!

### Anything other details to share?

You can find the docs here: https://github.com/samuelmaddock/metastream
According to the docs, the button has to have a link like this: "https://app.getmetastream.com/?url=https://youtu.be/3bNITQR4Uso"

**Comment by zisra** [comment]
Great idea, but watch party is being planned in #109 . I think it would be better built-into the app

**Comment by mrjvs** [comment]
what @zisra said, a custom solution is planned.
