### ISSUE TITLE
[Bug]: FF ten seconds button pauses movie after many clicks

### ISSUE THREAD

**Issue by PizzaGH** [movie-web/movie-web#403]
### What happened?

When I click the fast-forward button many times it pauses the thing I'm watching

### What browsers are you seeing the problem on?

Chrome/Edge

**Comment by mrjvs** [comment]
can reproduce. just spam the forward button

**Comment by meljason** [comment]
> can reproduce. just spam the forward button

I just manually tested it, and it seems like this cannot be reproduced.

Tested on Edge Browser on Desktop.

**Comment by robertsspaceindustries** [comment]
can't reproduce on vivaldi
chrome has a weird issue with the player rerendering and sometimes jumping back to an earlier timestamp when pressing +10
brave no issues

**Comment by binaryoverload** [comment]
I've tried reproducing on both Chrome and Firefox.

@mrjvs since you managed to reproduce this originally, can you check again please?

**Comment by PizzaGH** [comment]
Just checked now, no longer appears on chrome
