### ISSUE TITLE
[Bug]: Shows with duplicate names only go to first result

### ISSUE THREAD

**Issue by TomDo1234** [movie-web/movie-web#412]
### What happened?

Go here https://movie-web.app/search/series/full%20house

Full house is a name that multiple shows have, click on the 2nd one that is a kdrama, it shows videos of the first result

**Comment by zisra** [comment]
That is a [TMDB](https://themoviedb.org/) issue because we use their search API. You can choose to create a content report ([docs here](https://www.themoviedb.org/bible/general#:~:text=fixed%2C%20not%20discarded.-,Duplicates,-You%20can%20use)) if it bugs you instead

**Comment by binaryoverload** [comment]
This seems to be resolved now, at least for this specific series
