### ISSUE TITLE
[Feature]: Time in video slider

### ISSUE THREAD

**Issue by arash28134** [movie-web/movie-web#413]
### What feature do you want to add?

Showing time when hovering mouse over video/movie slider.

### Why do you want to have this feature?

To know which part of movie the user is skipping to.

**Comment by mrjvs** [comment]
this already exists sort of. For a timestamp directly above the scrubber there is also this issue open: #223

<img src="https://i.imgur.com/0FOtaMO.gif" />

closing

**Comment by arash28134** [comment]
> this already exists sort of. For a timestamp directly above the scrubber there is also this issue open: #223
> 
> ![](https://camo.githubusercontent.com/22ed02bdba7e90661357abe0a31df12f02b55440a2582c0b6087bbe02e916012/68747470733a2f2f692e696d6775722e636f6d2f30464f74614d4f2e676966) [ ![68747470733a2f2f692e696d6775722e636f6d2f30464f74614d4f2e676966](https://camo.githubusercontent.com/22ed02bdba7e90661357abe0a31df12f02b55440a2582c0b6087bbe02e916012/68747470733a2f2f692e696d6775722e636f6d2f30464f74614d4f2e676966) ](https://camo.githubusercontent.com/22ed02bdba7e90661357abe0a31df12f02b55440a2582c0b6087bbe02e916012/68747470733a2f2f692e696d6775722e636f6d2f30464f74614d4f2e676966) [ ](https://camo.githubusercontent.com/22ed02bdba7e90661357abe0a31df12f02b55440a2582c0b6087bbe02e916012/68747470733a2f2f692e696d6775722e636f6d2f30464f74614d4f2e676966)
> 
> closing

It'd be nice to have the time when you hover over slider instead of holding it

**Comment by mrjvs** [comment]
see my other sentence
