### ISSUE TITLE
[Feature]: Remove Sentry/Google Analytics tracking

### ISSUE THREAD

**Issue by ata-star** [movie-web/movie-web#414]
### What feature do you want to add?

i want tracking removed

### Why do you want to have this feature?

Its Tracking me and others

### Anything other details to share?

https://github.com/movie-web/movie-web/commit/e44b36c83e8aea2bfc3a4883a90773b5363bad74

less work too!

**Comment by binaryoverload** [comment]
We provide this website for free without ads or requiring users to sign up - having some analytics is a small price to pay.

If you don't want to be including in the Google analytics, you are welcome to either:
- Fork the project, host it yourself and remove the analytics.
- Use an extension to block Google Analytics - there are plenty of them!

**Comment by lukasfri** [comment]
XD
