### ISSUE TITLE
Suggesting Provider asianhdplay.pro

### ISSUE THREAD

**Issue by senhan07** [movie-web/movie-web#415]
https://asianhdplay.pro/

**Comment by mrjvs** [comment]
> not possible

why not? from initial inspection, the m3u8 is not cors protected

**Comment by castdrian** [comment]
the site just uses the regular assortment of embeds, streamsb, doodstream, mixdrop, didn't see any plain streams

**Comment by mrjvs** [comment]
doesnt mean it isnt a possible source.
I've added it to the list of possibilities in #393.

closing
