### ISSUE TITLE
[Bug]: Not working on Tizen (Samsung TV)

### ISSUE THREAD

**Issue by aaronleetw** [movie-web/movie-web#417]
### What happened?

The website was unable to load on Tizen (Samsung TV)'s built-in Internet browser. The screen just showed the background of the web app, and no components were in view.

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

1. Open Samsung Internet on a Tizen TV
2. In the address bar, enter movie-web.app
3. Only the background is shown

**Comment by castdrian** [comment]
Samsung Internet on Tizen is not Supported.

**Comment by binaryoverload** [comment]
We don't explicitly support legacy Browsers which Tizen falls into.
