### ISSUE TITLE
[Feature]: Keyboard navigation

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#422]
### What feature do you want to add?

navigate with keyboard shortcuts.

### Why do you want to have this feature?

Generally good practice to have. would also make navigation on tvs possible (the ones that use proper browsers)

**Comment by zisra** [comment]
Kind of related to #204

**Comment by castdrian** [comment]
potentially useful here would be how https://www.youtube.com/tv is usable via keyboard (it gates via UA so you need an extension otherwise it redirects to youtube.com) https://chrome.google.com/webstore/detail/youtube-for-tv/gmmbpchnelmlmndfnckechknbohhjpge

**Comment by mrjvs** [comment]
This has been fixed in the latest version: #530
