### ISSUE TITLE
[Feature]: Change audio track

### ISSUE THREAD

**Issue by zisra** [movie-web/movie-web#423]
### What feature do you want to add?

Superstream's mp4 files have multiple audio tracks on them you can choose from. 

### Why do you want to have this feature?

I want to be able to switch the language. Often times it plays a language I don't know when English is available. 

### Anything other details to share?

I'm using the video player IINA and got this for a movie, it would be nice to have a audio selector 
![image](https://github.com/movie-web/movie-web/assets/100528712/7f318397-3cca-483b-9c6b-4e6af8c13321)

Unfortunately there is no official API lets you do this but hopefully there is some kind of hack to bypass this. There's https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/videoTracks but that does not let you do it.

**Comment by TheScreechingBagel** [comment]
to add onto this - there's a reason to implement an audio track switcher even without supporti ng other languages.
https://discord.com/channels/871713465100816424/1174238916451250226
^ that thread reports Kill Bill having multiple audio tracks, which can be selected using the ios video player, but the web player defaults to Portugese, not english

**Comment by mrjvs** [comment]
as issue states, safari is the only browser that supports switching audio tracks in videos.
I don't think is possible unless we either only support safari (which im not a fan off) or manually ripping the audio tracks from the video and play them seperately (which can be very expensive in terms of resources, especially on phones)

![https://i.imgur.com/eJvcd9M.png](https://i.imgur.com/eJvcd9M.png)

**Comment by TheScreechingBagel** [comment]
ahh, that makes sense. Unfortunate

**Comment by zisra** [comment]
We can use HLS audio tracks (I didn't know this at the time of writing the issue)

**Comment by TheScreechingBagel** [comment]
[hls.js docs](https://nochev.github.io/hls.js/docs/html/class/src/controller/audio-track-controller.js~AudioTrackController.html)

looks like you can get an indexed list and then select the audio track via that index

**Comment by mrjvs** [comment]
id like to add that this is only possible with HLS. not all sources provide HLS. and if we plan on switching superstream to HLS that would also break downloads.

**Comment by TheScreechingBagel** [comment]
couldn't the (non-hls) download link just be pulled separately? while playing hls in the browser

**Comment by zisra** [comment]
We could prioritize SuperStream and name the Superstream HLS "Superstream (with languages)." Or just tell people to switch to FebBox HLS if they ask to switch languages in the Discord server

**Comment by ldhiman** [comment]
Working on it

**Comment by Alejandro18650** [comment]
I think this feature will be fine. I am from Spain and all the series or movies that I search for in Spanish appear in their English version or, if the English version does not exist, in Spanish (although no source has them). It would be great if you could choose between Spanish from Spain or Latin Spanish
