### ISSUE TITLE
[Feature]: PiP in Firefox

### ISSUE THREAD

**Issue by Caketaco** [movie-web/movie-web#429]
### What feature do you want to add?

PiP button for the Firefox version of movie-web. I've seen it on mobile and I've heard that it's on Chrome. Firefox supports PiP, so I would love to see it there.

### Why do you want to have this feature?

PiP allows for better multitasking. In my case, it lets me watch dopey shows while doing college work, all on one screen.

**Comment by mrjvs** [comment]
I haven't done full research, but if I recall correctly firefox doesn't support any way to control PiP. We can't make a button for it. We can only hope Firefox adds it's own button natively.

**Comment by Caketaco** [comment]
![Video](https://i.imgur.com/fAy0jjs.mp4)

**Comment by Caketaco** [comment]
Whoops-- Alright, looks like you *can* use PiP if you enable the PiP button in Firefox settings.
https://i.imgur.com/DVsAxt7.mp4
Surely there's a way to add an embedded one, though, right?
Would be odd if Firefox didn't support that.
Oh well, I'll close this since I got what I wanted. Feel free to reopen if needed.

**Comment by mrjvs** [comment]
Yes, that button was added by Firefox. YouTube didn't implement it for Firefox.

Its likely that Firefox added a check "if youtube.com, then show PiP button".
