### ISSUE TITLE
[Feature]: Download caption/subtitle

### ISSUE THREAD

**Issue by dlee6036** [movie-web/movie-web#431]
### What feature do you want to add?

Hi developers,
Thanks so much for the amazing website!
Since we have a feature to download videos, I was wondering if we could add a feature to download the subtitle/caption for the video that's playing as well.
Cheers!

### Why do you want to have this feature?

When we download a video, currently there's no option to download the subtitle of the video. We have to find a subtitle manually for the video after downloading. This could be a challenge since the subtitle has to be the right one for the video - sync, language, release types, etc.

**Comment by zisra** [comment]
Maybe add a download button with the chevron? 
<img width="301" alt="Screenshot 2023-09-08 at 2 12 48 PM" src="https://github.com/movie-web/movie-web/assets/100528712/7c4f3a4b-a27a-4bd4-a9d5-1dfa3c5b9336">

**Comment by NidukaAkalanka** [comment]
+1 on this

**Comment by rahulmathews** [comment]
+1 on this along with the customisation of delay subtitles as few subtitles definitely have a delay of more than 15s.

**Comment by mrjvs** [comment]
Fixed in newly released v4
