### ISSUE TITLE
[Feature]: Opacity for subtitle too

### ISSUE THREAD

**Issue by ghfsa** [movie-web/movie-web#438]
### What feature do you want to add?

Its great that there's an option to change opacity of subtitle background. The same should be available for the _subtitle font_ too!

### Why do you want to have this feature?

For content with desaturated or less brightness, like some _horror movies or of low key lights_, one should be able to adjust the _value_ (opacity) of the subtitles too. Cause the full bright font, they fit in with anime-like content, but stand out and kinda break the immersion in low-key light content. 

Thanks for the great project.

**Comment by binaryoverload** [comment]
I am not keen on adding a full extra slider for this, but perhaps we could have a grey colour in the colour picker 🤔

**Comment by qtchaos** [comment]
Will add a darker color that's more pleasing to the eye^^
