### ISSUE TITLE
[Feature]: Support for mulitple audio (dub)

### ISSUE THREAD

**Issue by wanisramdani** [movie-web/movie-web#442]
### What feature do you want to add?

The ability to change between audio tracks

### Why do you want to have this feature?

Some animes can have multiple dub it would be great to be able to switch between them

**Comment by zisra** [comment]
#423 partially, but we don't support anime yet

**Comment by wanisramdani** [comment]
Some sources do provide anime

![image](https://github.com/movie-web/movie-web/assets/34271234/97be2b76-2bf7-4315-84f2-1b6478e3d86a)

**Comment by wanisramdani** [comment]
Closing this since there is a similar issue #423
