### ISSUE TITLE
[Feature]: make to fetch Telegram Channel media file.

### ISSUE THREAD

**Issue by ScripterSaurav** [movie-web/movie-web#452]
### What feature do you want to add?

Can you make to fetch Telegram Channel media file in it. 

### Why do you want to have this feature?

It will be very helpful. when video will be not available on other sources. Then we can Upload on Telegram Channel ourself.

**Comment by binaryoverload** [comment]
We source links from our providers that we have built-in, we have no plans to allow custom video links to be used.
