### ISSUE TITLE
[Bug]: PWA Auto rotate not working (android 13)

### ISSUE THREAD

**Issue by blikje7up** [movie-web/movie-web#454]
### What happened?

The feature in chrome "Add to Home screen" (PWA) Installs movie-web as an app. 
However the autorotate function does not work. (android 13 specific issue)

### Other relevant information

This seems to be the solution: https://github.com/photoprism/photoprism/issues/3413#issuecomment-1755990054

**Comment by blikje7up** [comment]
Tested and working on Android 13, now the screen can rotate 360° (not optimal imo). Added line below in the "manifest.webmanifest" file:
"orientation": "any",

**Comment by abdo072** [comment]
Auto rotate isn't working for me either , android 13 and i installed the web app

**Comment by mrjvs** [comment]
It's been added to the v4 project board, it will be fixed in version 4

**Comment by abdo072** [comment]
> It's been added to the v4 project board, it will be fixed in version 4.
> Thanks for the research, hopefully the fix will be that easy.

Thx ❤️, but any idea when v4 is going be out there ?

**Comment by mrjvs** [comment]
> Thx ❤️, but any idea when v4 is going be out there ?

There isn't an ETA for v4, there's a lot to do
