### ISSUE TITLE
Improving Self-Hosting Experience: Caching + Config

### ISSUE THREAD

**Issue by binaryoverload** [movie-web/movie-web#455]
Currently, we find many self-hosters have issues with their hosted instances due to a config or caching issue (Or both).

- Currently, the config is cached through PWA. Either exclude it from the cache or cache it manually in local storage
- Add a secret URL/admin to see current configuration values and some automated tests to see if it can do everything it needs to and diagnose issues.
  - Test TMDB access
  - Test if the worker can be accessed
  - Test if the backend can be reached
  - Test all config values

**Comment by mrjvs** [comment]
This has been fixed in the latest version: #530
