### ISSUE TITLE
[Bug]: no subtitles when streaming 

### ISSUE THREAD

**Issue by csoalhat** [movie-web/movie-web#460]
### What happened?

When I use chromecast to cast on my TV, the subtitles stay in the phone screen 

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

Using the latest chromecast and chromescasting with subtitles from my phones browser (android latest version pixel 6a chrome)
The screen on my phone shows the subtitles but not the TV

**Comment by JipFr** [comment]
This is a known bug and will (hopefully) be fixed in the next major version https://github.com/orgs/movie-web/projects/1/views/1?filterQuery=chromecast&pane=issue&itemId=31026262
