### ISSUE TITLE
[Bug]: Overlapping Audio of second langue

### ISSUE THREAD

**Issue by NathanielZane** [movie-web/movie-web#461]
### What happened?

For the reccomended server for the following show https://movie-web.app/media/tmdb-show-73375/91583/1439513

has a 2nd audio dubbing the original and no setting to turn off

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Steps to reproduce?

https://movie-web.app/media/tmdb-show-73375/91583/1439513
"Jack ryan S1E1"

superstream server

**Comment by qtchaos** [comment]
Unfortunately this is not something we can control, best you can do is switch sources and hope for the best.
