### ISSUE TITLE
[Bug]: Search results don't conform to spatial navigation

### ISSUE THREAD

**Issue by rupeshcsv** [movie-web/movie-web#462]
### What happened?

Silk browser on Fire TV provides spatial navigation and cursor navigation for nav options. Spatial navigation works fine on front page components but not on search results. Pressing down from the search bar goes to the result in the middle (expected (or maybe better UX is first result in the first list?)) but then pressing left goes to the logo instead of the result on the left. It also does work as expected as you go lower from the search bar and try to come back up, most likely due to the floating search bar.

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

1. On a Fire TV, Open the Amazon Silk browser
2. Set spatial navigation as the navigation choice
3. Go to the website
4. Search something
5. Navigate results using remote's navigation D-pad

### Other relevant information

Expected result is that the D-pad can browse around the search results easily, and on repeated presses of UP, it has to come up to the first list of results before it can go to the search bar.

**Comment by binaryoverload** [comment]
Bug from pre-v4
