### ISSUE TITLE
[Feature]: Bulk download For Series  

### ISSUE THREAD

**Issue by Lavoy3** [movie-web/movie-web#473]
### What feature do you want to add?

A new Button to download an entire season in one go.

### Why do you want to have this feature?

It will be way easier.

**Comment by mrjvs** [comment]
We've decided before to not add bulk downloads, its basically a worker spam button and will likely overload our servers.

**Comment by Lavoy3** [comment]
ok no problem
good to know

**Comment by QuantumCoded** [comment]
What about for those of us who selfhost and want bulk downloads? Is it possible to add this and lock this feature behind an environment variable defaulted to false so users can opt-in if they're okay with the performance hit? Sorry to bump a closed issue, but I also think this would be a very nice feature.

**Comment by binaryoverload** [comment]
movie-web is designed to watch media, not become a media downloader. There are other tools available for that.
