### ISSUE TITLE
[Feature]: Increased Caption Time Delay

### ISSUE THREAD

**Issue by Invisible40** [movie-web/movie-web#476]
### What feature do you want to add?

It would be nice to have greater than 10.0 seconds for the caption time delay, so the captions are more aligned with the video. 

### Why do you want to have this feature?

The captions are not aligned with a show I watch (Dexter)

### Anything other details to share?

This website is great and I'll continue to use!

**Comment by castdrian** [comment]
duplicate https://github.com/movie-web/movie-web/issues/287
