### ISSUE TITLE
[Bug]: atob is not defined when trying to host a server

### ISSUE THREAD

**Issue by just-idir** [movie-web/movie-web#481]
### What happened?

Im trying to host my own server that uses the @movie-web/providers package but the app always fails to deploy and shows the following error ->  ReferenceError: atob is not defined 
keep in mind the server runs normally on my local machine

**Comment by mrjvs** [comment]
What version of nodejs does your server run. And which version of providers package are you using?

**Comment by just-idir** [comment]
This issue was fixed by upgraded node to the latest version
