### ISSUE TITLE
[Feature]:  Missing Functionality in @movie-web/providers (v1.0.5)

### ISSUE THREAD

**Issue by just-idir** [movie-web/movie-web#483]
### What feature do you want to add?

Adding 1080p Video Quality Support to `@movie-web/providers` using `superstream`

### Why do you want to have this feature?

I am currently using the `@movie-web/providers` project as a dependency in my server, I've noticed that i cant get high quality (1080p) videos using `superstream`

### Anything other details to share?

I have noticed that the web app using the same source `superstream` can fetch high quality (1080p) videos. It seems that this functionality is available in the web app but not in the `@movie-web/providers`.

After inspecting the code, I found that `getstreamquality` in `@movie-web/providers` appears to have `const allowedQualities = ['360', '480', '720', '1080']`, but when fetching media, only 720p and 360p qualities are available and sometimes only 360 keep in mind that i tested the same exact media (movie) in the web app and it gets 1080p

**Comment by JipFr** [comment]
The web app shows that it can fetch 1080p videos from SuperStream, but this is a bug: SuperStream returns an empty URL for 1080p, and the current version of movie-web treats this as being an acceptable value. For that reason, it shows in the web app as 1080p when it's only 720p in reality. 

The issue has been resolved in our next (unreleased) version, but it does mean that it's sadly just a lie. SuperStream does not return 1080p streams.
