### ISSUE TITLE
[Bug]: https://movie-web.app does not display properly on iPhone/iPad

### ISSUE THREAD

**Issue by 2JayCee** [movie-web/movie-web#486]
### What happened?

Viewing the website on iPhone/iPad, the site does not properly display. Any buttons or menus are not able to be used properly. Some menus like picking seasons/episodes cause the dropdown to be untouchable. 

### What browsers are you seeing the problem on?

Safari

**Comment by blikje7up** [comment]
Please specify IOS version, Safari version and upload a screenshot of the issue

**Comment by binaryoverload** [comment]
No details provided, closing as stale
