### ISSUE TITLE
[Bug]: Missing Captions Support in @movie-web/providers  [ v1.0.5 ]

### ISSUE THREAD

**Issue by just-idir** [movie-web/movie-web#487]
### What happened?

I've been using the `@movie-web/providers` package and have found it to be a fantastic tool. However, I've noticed that captions support is currently missing. 

The `runEmbedScraper` function, when used with `upcloud`, should ideally return a stream object that includes captions. However, it seems like the captions are missing from the output stream object. 

I have compared this behavior with the `movie-web-app` backend where the same function include captions.

### Other relevant information

It seems like the function `scrape` in the `upcloudScraper` when returning the stream object only includes `type` `playlist` and `flags` unlike the same function in the `movie-web-app` that includes also `captions`.

**Comment by binaryoverload** [comment]
Thanks for the issue! We have this on our list of planning stuff to do :)

**Comment by mrjvs** [comment]
caption support has been added. the same sources as movie-web currently does have been given captions.
No documentation yet, will be added later. but its on the stream object `stream.captions`.

npm version will be live in a few minutes.
