### ISSUE TITLE
[Feature]: Add video from bflix.ru

### ISSUE THREAD

**Issue by SnowzNZ** [movie-web/movie-web#490]
### What feature do you want to add?

Add videos from bflix.to

### Why do you want to have this feature?

It has shows that movie web doesnt have

**Comment by binaryoverload** [comment]
This provider seems to have been blocked by ISPs in the UK - so I don't think it'll be worth the effort to implement if UK users (and potentially EU) can't use it

**Comment by JorrinKievit** [comment]
Also has cloudflare, so cant scrape anyway 😄
