### ISSUE TITLE
[Bug]: Iframes used to work, now they dont

### ISSUE THREAD

**Issue by SaucyOfficiale** [movie-web/movie-web#491]
### What happened?

I'd LOVE to use Movie.Web at https://sau.cy and it would be my honor to make it part of our streaming side of the platform platform. Movie Web used to have iframes enabled, but I had to switch to another provider for now that has iframes enabled. Please allow this so we can have you as part of Saucy! 🎉

**Comment by TheScreechingBagel** [comment]
just had an aneurysm from that website

**Comment by TheScreechingBagel** [comment]
there's https://github.com/movie-web/providers

and there's also https://en.wikipedia.org/wiki/Religion, please pick one and repent

**Comment by zisra** [comment]
You can selfhost and iframe

**Comment by SaucyOfficiale** [comment]
> just had an aneurysm from that website

Why are people always so rude about Saucy? I love my project. What's your problem?

**Comment by SaucyOfficiale** [comment]
> there's https://github.com/movie-web/providers
> 
> and there's also https://en.wikipedia.org/wiki/Religion, please pick one and repent

Why are people always so rude about Saucy? I love my project and all my friends are subscribed to it. What's your problem?

**Comment by SaucyOfficiale** [comment]
> just had an aneurysm from that website

Why are people always so rude about Saucy? I love my project and all my friends are subscribed to it. What's your problem?

**Comment by SaucyOfficiale** [comment]
> You can selfhost and iframe

hoping to iframe https://movie-web.app/ if not I wont be able to do it. I already have a provider that works but love movie web interface

**Comment by zisra** [comment]
@SaucyOfficiale [Selfhosting instructions](https://github.com/movie-web/movie-web/blob/dev/SELFHOSTING.md)

**Comment by SaucyOfficiale** [comment]
> @SaucyOfficiale [Selfhosting instructions](https://github.com/movie-web/movie-web/blob/dev/SELFHOSTING.md)

I dont want to spend money to selfhost and Saucy is a big app. Cloudflare Pages has unlimited bandwidth, CF Workers does not.

**Comment by SaucyOfficiale** [comment]
> @SaucyOfficiale [Selfhosting instructions](https://github.com/movie-web/movie-web/blob/dev/SELFHOSTING.md)

Just let movie web be iframed. Its that simple.

**Comment by mrjvs** [comment]
We've explicitly disallowed iframing because of saucy. You can selfhost and enable iframing in the _headers file.
