### ISSUE TITLE
[Bug]: After skipping, video freezes

### ISSUE THREAD

**Issue by MutedOrange** [movie-web/movie-web#492]
### What happened?

After skipping once, the video may freeze. After a second skip, frozen video is guaranteed. Audio and subtitles work as intended.

### What browsers are you seeing the problem on?

Chrome for android, chrome generated applet, kiwi browser

### Steps to reproduce?

1. Play any movie/tv show
2. Skip ahead and wait to load
3. If paused, hit play
4. If after the first skip the video is not frozen, skip again
5. If paused, hit play

**Comment by ordzy** [comment]
think that might just be bad internet speeds

**Comment by sabaasa** [comment]
I'm also getting this issue on an older android device specifically.

the said android device is a xiaomi phone and it has Brave installed, not sure about the exact model of the phone

**Comment by binaryoverload** [comment]
@MutedOrange / @sabaasa have you experienced this issue recently? Is this still a problem?

**Comment by sabaasa** [comment]
nope. working fine for me since the latest update, not quite sure from which version exactly it was fixed
