### ISSUE TITLE
[Bug]: Quality changes while playing source tab does not work

### ISSUE THREAD

**Issue by semihofc** [movie-web/movie-web#493]
### What happened?

Quality changes between 360p-ish and 1080p so much times, i cant set it up either since Source tab simply does not work, regardless which provider i select, its always "No embeds found for this source" (i play from that source but it just says "no embeds") and some say "Something went wrong"
Cant change quality at all

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

Open a movie/series (Mine: https://movie-web.app/media/tmdb-show-204082/297440/4669401)
Try to switch source after loaded
It doesnt work.

**Comment by mrjvs** [comment]
Providers are expected to fail. and if they dont have embeds for the source thats also expected.
it just means the sources/providers don't have the media youre looking for.

The next version (v4) will have better communication for this, but fundementally this is not a bug.
