### ISSUE TITLE
[Bug]: caption/subtitle does not appear on casted device(smart tv)

### ISSUE THREAD

**Issue by Pythoenixx** [movie-web/movie-web#506]
### What happened?

captions not appear on casted device

captions should appear on casted device

### Steps to reproduce?

cast the video to another device and turn on the subtitle

### Other relevant information

the bug is on smart tv for my cases

**Comment by JipFr** [comment]
Are you using Chromecast or AirPlay? In case of the latter, please see https://github.com/movie-web/movie-web/issues/488#issuecomment-1812705329

In case it's the first, I'm not really sure what the status on that is. @mrjvs do you know?

**Comment by mrjvs** [comment]
chromecasting subs is tracked in this: #335.
Airplay (as jip said) is tracked at: #448.

The chromecasting one is on the roadmap of v4.
Closing as duplicate.
