### ISSUE TITLE
[Bug]: No subtitles available

### ISSUE THREAD

**Issue by PEG7632** [movie-web/movie-web#510]
### What happened?

Hello ! I don't know since when exactly, but it seems that on the website, the subtitles aren't available anymore, there is only a red warning whenever I click on one of the subtitle language. I haven't tried it while hosting the app and only on the website

### Steps to reproduce?

just launch any movie and try to activate subtitle

**Comment by akshaybharwani** [comment]
Facing this on Firefox and Edge

**Comment by newlysama** [comment]
Google chrome aswell

**Comment by binaryoverload** [comment]
Unfortunately, Superstream (One of our most popular providers) has removed a bunch of subtitle files. Not much we can do about it at the moment - we will look into if there are any solutions going forward.

Whilst it's annoying, you can upload your own subtitles - which you can download from sites like [OpenSubtitles](https://www.opensubtitles.org/en/search/subs)

Not a bug™️

**Comment by akshaybharwani** [comment]
Well for me at least it's not just Superstream, I tried with Gomovies and FlixHQ as well, and subtitles didn't work for them as well.

**Comment by akshaybharwani** [comment]
Gotcha! Is there an ETA for v4?
