### ISSUE TITLE
[Feature]: Keyboard navigation improvements

### ISSUE THREAD

**Issue by krlhBlupine** [movie-web/movie-web#521]
### What feature do you want to add?

Hotkeys for search and navigation- presumably '/'. I'm partial to vim keybindings for moving around, but I could take or leave that.

### Why do you want to have this feature?

Ease of navigation from a keyboard-only setup would be a big improvement in my eyes.

**Comment by faizan-20** [comment]
Hey @JamesHawkinss  could i start working on this issue? I would also like to see some keyboard navigations on the site. 

Maybe instead of using vim keybindings for search we could use ctrl + k?

**Comment by mrjvs** [comment]
We don't want to add any more shortcuts. We have tons for the video player, tabbing works consistently throughout the app.
And `/` for search is already implemented.
