### ISSUE TITLE
[Bug]: Some of the videos aren't loading and the videos r just randomly loading and freezing while the audio is playing

### ISSUE THREAD

**Issue by Zennywennyy** [movie-web/movie-web#526]
### What happened?

Well, while using the website the videos just weren't loading like I could watch episode 1 and 3 of something and then episode 2 won't load and then with movies it'll pause, and the audio will keep playing but when I fast forward it to the part, I missed it'll play and overall, the website has just been bugging out really badly for me and it's aggravating.

### What browsers are you seeing the problem on?

Microsoft Edge

### Other relevant information

![image](https://github.com/movie-web/movie-web/assets/153780848/f09adafa-7765-4a4f-bc7b-e563248dad2f)

**Comment by zisra** [comment]
Send a relevant link to what you're trying to watch please

**Comment by Zennywennyy** [comment]
its not what im trying to watch its what my sisters trying to watch but https://movie-web.app/media/tmdb-show-6942/87664/1306317

**Comment by zisra** [comment]
This is intended, it just means the TV show doesn't exist on our site
