### ISSUE TITLE
[Bug]: Cant go back to home after using /s/

### ISSUE THREAD

**Issue by MemeCornucopia** [movie-web/movie-web#531]
### What happened?

Cant go back to home after using /s/

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

Go to for example https://movie-web.app/s/peppa%20pig and press back button a million times

### Other relevant information

https://github.com/movie-web/movie-web/assets/148788549/05b6085c-e38b-4c52-a976-71089d7956f8

**Comment by mrjvs** [comment]
This was fixed in #537, next update will contain the fix

**Comment by MemeCornucopia** [comment]
🔥💯
