### ISSUE TITLE
[Feature]: Sync proxy workers between devices

### ISSUE THREAD

**Issue by DenuxPlays** [movie-web/movie-web#539]
### What feature do you want to add?

Make it possible to sync proxy workers between devices.

### Why do you want to have this feature?

I don't want to add the my proxy-url to every device I use.

### Anything other details to share?

This would possibly reduce the load on your default proxy-workers so that you do not run out of quota as frequently.
Personally I only use the custom proxy on my PC (bc. I was too lazy to add the url on my phone, laptop, etc.).

**Comment by DenuxPlays** [comment]
> Should this be optional?

Maybe activated by default but should be toggleable

**Comment by binaryoverload** [comment]
> Should this be optional?

Personally I think the "optional" part is whether you're signed in. If you're signed in it syncs, if you're not it doesn't.

I don't think there's a situation where you wouldn't want to sync it - there isn't really a difference between proxies

**Comment by qtchaos** [comment]
Could I get assigned? I have the implementation completed on both the backend and frontend, ill PR soon.
