### ISSUE TITLE
[Bug]: Can't load any provider

### ISSUE THREAD

**Issue by newlysama** [movie-web/movie-web#545]
### What happened?

Trying to watch game of thrones on the web app, but can't load any provider.

Error : 

```
superstream: failure
TypeError: Failed to fetch
zoechip: failure
TypeError: Failed to fetch
gomovies: failure
TypeError: Failed to fetch
flixhq: failure
TypeError: Failed to fetch
remotestream: failure
TypeError: Failed to fetch
```

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

Launch game of thrones (maybe it's with all the the videos idk)

**Comment by mrjvs** [comment]
We've run out of juice for the day, it resets at midnight, in 5 hours.
![](https://i.imgur.com/Q7MWK9K.png)
