### ISSUE TITLE
[Bug]: Everything I Try To Watch Is Having Errors When Checking For Video!

### ISSUE THREAD

**Issue by Joshtee0113** [movie-web/movie-web#547]
### What happened?

When i try and play anything, anything at all, it says error occured on every source. Even things i was watching a couple nights ago, so i know they are there.

### What browsers are you seeing the problem on?

Chrome, Other (tell us in input box below)

### Steps to reproduce?

I Have Tried Both On My Phone & TV

**Comment by mrjvs** [comment]
Duplicate of #545
