### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by divmagic** [movie-web/movie-web#548]
### What happened?

```superstream: notfound Couldn't find a stream: No entry found zoechip: pending gomovies: failure TypeError: Failed to fetch flixhq: failure TypeError: Failed to fetch remotestream: failure TypeError: Failed to fetch zoechip-0: failure TypeError: Failed to fetch zoechip-1: failure TypeError: Failed to fetch ```

**Comment by akumaaayush** [comment]
Duplicate of #545
