### ISSUE TITLE
[Bug]: Blurry Posters.

### ISSUE THREAD

**Issue by Zephyriyn** [movie-web/movie-web#549]
### What happened?

```tsx
export function getMediaPoster(posterPath: string | null): string | undefined {
  if (posterPath) return `https://image.tmdb.org/t/p/w185/${posterPath}`;
}
``` 

changing 

https://image.tmdb.org/t/p/w185/${posterPath}

to 

https://image.tmdb.org/t/p/original/${posterPath}

makes the posters look a lot better, they otherwise look blurry.

Comparision: 

![image](https://github.com/movie-web/movie-web/assets/147987822/4aa957c6-44de-41d4-bb5d-34d489801b56)

![image](https://github.com/movie-web/movie-web/assets/147987822/501e001b-95bc-4b4e-93e7-696b6cce730a)

**Comment by JipFr** [comment]
This would significantly increase loading time for posters

**Comment by Zephyriyn** [comment]
i don't have really fast internet speed but it the loading speeds between the two is not noticeable for me

**Comment by binaryoverload** [comment]
Maybe there's a middle ground here between original and the current width that improves the quality - something like 300 perhaps

**Comment by mrjvs** [comment]
I do think original quality is overkill. But w185 is definitely too small. We can use a middleground.

**Comment by zisra** [comment]
The current poster size averages 19kB and a total of 200kb which is nothing compared to what people watch

**Comment by JipFr** [comment]
The difference is that the home page needs to feel fast, pop-in posters don't add to that. I agree that 185 is too small, but original is too big — especially once you have a lot of items. What options do we have for middle ground?

**Comment by Zephyriyn** [comment]
```js
// ==UserScript==
// @name         Cleaner Posters
// @version      1.0
// @description  Cleaner posters for movie-web.app
// @author       R
// @match        https://movie-web.app/*
// ==/UserScript==

(function() {
    'use strict';

    function replaceUrl(url) {
        return url.replace('w185', 'original');
    }

    function processElements() {
        var allElements = document.getElementsByTagName('div');

        for (var i = 0; i < allElements.length; i++) {
            var currentElement = allElements[i];

            for (var j = 0; j < currentElement.attributes.length; j++) {
                var attributeName = currentElement.attributes[j].name;
                var attributeValue = currentElement.attributes[j].value;

                if (attributeValue && attributeValue.toLowerCase().includes('http')) {
                    var newUrl = replaceUrl(attributeValue);

                    currentElement.setAttribute(attributeName, newUrl);
                }
            }
        }
    }

    window.onload = function() {
        processElements();
    };

})();
```

for people with fast internet speeds

**Comment by zisra** [comment]
> The difference is that the home page needs to feel fast, pop-in posters don't add to that. I agree that 185 is too small, but original is too big — especially once you have a lot of items. What options do we have for middle ground?

<img width="206" alt="Screenshot 2023-12-17 at 9 54 15 AM" src="https://github.com/movie-web/movie-web/assets/100528712/dbbf1d84-a044-49a9-8f85-e4f4158da85d">

342 (height) seems feasible. Considering the size of our image element is 234x156p
