### ISSUE TITLE
[Bug]: Quality mismatch.

### ISSUE THREAD

**Issue by Zephyriyn** [movie-web/movie-web#550]
### What happened?

the video quality displayed in the menu and the actual quality of the file are different.

Menu:
![image](https://github.com/movie-web/movie-web/assets/147987822/5d8ce53f-ec71-4404-92d1-1d42f063e40b)
![image](https://github.com/movie-web/movie-web/assets/147987822/7a1b9fc0-51ca-48b5-ae04-c3133e214fff)

File: 
![image](https://github.com/movie-web/movie-web/assets/147987822/264a1c15-9549-4df1-98c5-171771ab9695)

### Steps to reproduce?

1. go to https://movie-web.app/media/tmdb-tv-78191-you/101109/1457316
2. click on settings
3. check the quality by going into quality
4. check the download url

**Comment by binaryoverload** [comment]
If the Superstream provider is not reporting the correct quality of the video, there isn't much we can do there unfortunately
