### ISSUE TITLE
[Stupid Feature]: The passphrase system instead of passwords

### ISSUE THREAD

**Issue by schoolgadou** [movie-web/movie-web#551]
### What feature do you want to add?

I absolutely hate the passphrase system, It's not like its an account full of crypto its movie data

### Why do you want to have this feature?

I'd much rather have passwords because its easier to sign in throughout multiple devices

**Comment by erynith** [comment]
passphrases include more anonymity tho and it's called don't loose ur passphrase like how u don't loose ur passwords

**Comment by binaryoverload** [comment]
We specifically chose the passphrase system due to its anonymity; we will not be changing it. 

We have no intention on storing data related to a movie-web user.

**Comment by schoolgadou** [comment]
> passphrases include more anonymity tho and it's called don't loose ur passphrase like how u don't loose ur passwords

I remember my passwords way better than i remember paraphrases
