### ISSUE TITLE
[Bug]: Casting to chromecast no longer works

### ISSUE THREAD

**Issue by Mofker** [movie-web/movie-web#554]
### What happened?

I can no longer cast to my chromecast with the lastest version. The video will just buffer indefinitely. The video starts on both PC/Android but refuses to load once casted.

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

1. Pick any video
2. select cast and chose chromecast

**Comment by binaryoverload** [comment]
Are you still experiencing this issue? Can you try multiple media to confirm?

Sometimes we come across a HLS stream with codecs that Chromecast doesn't like - I suspect that is the issue here

**Comment by branislavbrincko** [comment]
I am experiencing similar issue - I open the app via a browser in the Chromecast (I use BrowseHere and I also tried Open TV Browser), click on the media to play it, media playback window is shown but no video is being played, no error message. Other times the error IS show - “Failed to load metadata. Could not load the media’s metadata from TMDB…” This problems appeared after roughly 2 weeks of not using the app via Chromecast. It happens for each media.

**Comment by Mofker** [comment]
I've tried casting to both a Chromecast and directly to my TV, getting the same issue on both. Alternative sites will load up and play just fine. Very rarely does the casted video actually play. If it does, it either buffers heavily or just stops after a minute or two of playing with no errors.

**Comment by adipandas** [comment]
> I've tried casting to both a Chromecast and directly to my TV, getting the same issue on both. Alternative sites will load up and play just fine. Very rarely does the casted video actually play. If it does, it either buffers heavily or just stops after a minute or two of playing with no errors.

Same issue for me as well.

**Comment by binaryoverload** [comment]
Bug from pre-v4
