### ISSUE TITLE
[Bug]: Video playback exhibits a green flickering issue

### ISSUE THREAD

**Issue by ChetFromFalloutNewVegas** [movie-web/movie-web#555]
### What happened?

There are flickers of green colors in the video, whether in full screen or not. It only stops for a while if I retry playing the same show over and over again.

I’m seeing this problem on Amazon Silk (Fire TV Stick’s browser).  

### What browsers are you seeing the problem on?

Other (tell us in input box below)

**Comment by binaryoverload** [comment]
This sounds like an issue with the browser itself not processing the video correctly or struggling to cope - with the issue being on a fire TV stick this sounds likely.

**Comment by ChetFromFalloutNewVegas** [comment]
> This sounds like an issue with the browser itself not processing the video correctly or struggling to cope - with the issue being on a fire TV stick this sounds likely.

But playing videos in Amazon Silk, even beyond movie-web, poses no issues for me.
