### ISSUE TITLE
[Feature]:  Opensubtiles not available V4?

### ISSUE THREAD

**Issue by anybody999** [movie-web/movie-web#557]
### What feature do you want to add?

Scrap subtitles via opensubtitles.org

### Why do you want to have this feature?

Option

**Comment by JipFr** [comment]
OpenSubtitles were sadly not deemed feasible due to the extreme rate limits. Sadly, there's no way to get around it.

**Comment by anybody999** [comment]
> OpenSubtitles were sadly not deemed feasible due to the extreme rate limits. Sadly, there's no way to get around it.

thank you for reply. Its possible to use other subtitle provider?

**Comment by JipFr** [comment]
Do you know any good ones?

**Comment by akumaaayush** [comment]
Idk if this helps:
https://github.com/morpheus65535/bazarr?tab=readme-ov-file#supported-subtitles-providers
Maybe inspect how bazarr subtitle system works?

**Comment by zisra** [comment]
Subscene is a good provider
