### ISSUE TITLE
[Improvement]: French translation of website

### ISSUE THREAD

**Issue by iamgpe** [movie-web/movie-web#558]
### What feature do you want to add?

Hello,

I've noticed that the French translation of the interface seems to have been done automatically and lacks naturalness. I propose to improve the quality of this translation by making it more fluent and more adapted to the French context. This would include a complete review of the texts to ensure they reflect authentic and understandable French.

### Why do you want to have this feature?

The importance of this improvement lies in the fact that many French-speaking users could feel more comfortable with a translation that sounds natural. A good translation can greatly influence the user experience and make the application or website more accessible and enjoyable for a wider audience. Moreover, it would contribute to giving a more professional image of the project.

**Comment by blikje7up** [comment]
https://weblate.movie-web.app/projects/movie-web/

**Comment by binaryoverload** [comment]
The community provides all our translations through our translation platform [Weblate](https://weblate.movie-web.app/projects/movie-web/)

You can find out how to contribute to these to improve the translations in our contributor guidelines: https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md#language-contributions
