### ISSUE TITLE
[Feature]: Search should adapt to minor typos in movie/series name

### ISSUE THREAD

**Issue by AshminJayson** [movie-web/movie-web#562]
### What feature do you want to add?

Add a string-matching feature to the search that perhaps uses levenshtein or some other distance metric and shows similar movie/series names in case the user misspelled it.

### Why do you want to have this feature?

This would 100 percent improve the user experience aspect and prevent the user from having to google the correct name in case they make a typo, and the movie doesn't show up.

### Anything other details to share?

It would probably only be a minor change to the pattern matching function which can be easily integrated to the current codebase.

**Comment by JipFr** [comment]
We do not have a movie or TV show database of our own, we use TMDB’s API to search. We have no control over their search algorithm.
