### ISSUE TITLE
[Feature]: Add subtitles using open subtitles 

### ISSUE THREAD

**Issue by NelsonGuiamba** [movie-web/movie-web#567]
### What feature do you want to add?

The feature would work like it does in MxPlayer or VLC media player, it should be able download the subtitle in the required language by the user

### Why do you want to have this feature?

I know that it is simple but it could save many time when watching a serie (You have to download all episodes subs) and import every episode you watch

**Comment by mrjvs** [comment]
Not possible. Already been tried. Can only be done on native apps, not on web apps
