### ISSUE TITLE
[Feature]: Skip forward buttons

### ISSUE THREAD

**Issue by sooswastaken** [movie-web/movie-web#573]
### What feature do you want to add?

Customization of the skip forward buttons (change from 1s to custom amount like 10 or 5s)

### Why do you want to have this feature?

More customizability

**Comment by DenuxPlays** [comment]
Maybe add  "youtube-style" like shortcuts.
Arrow-keys => 5sec 
And J and L => 10sec

**Comment by JipFr** [comment]
What button has 1s now?

**Comment by blikje7up** [comment]
arrow key already is 5 seconds

**Comment by qtchaos** [comment]
I have implemented changes that add the YouYube-style shortcuts (`j`, `l` (skip by 10 sec) and `,`, `.` (skip by 1 sec). Will PR once i get assigned :p
