### ISSUE TITLE
[Bug]: Error when loading through proxy

### ISSUE THREAD

**Issue by dragon731012** [movie-web/movie-web#576]
### What happened?

Error: [Immer] minified error nr: 11. Full error at: https://bit.ly/3cXEKWf

### What browsers are you seeing the problem on?

Chrome

**Comment by binaryoverload** [comment]
Hi there, 

Thanks for the bug report! Could you please let us know what the steps to reproduce this error are? (If you can reproduce it!)

**Comment by binaryoverload** [comment]
Closing as stale

**Comment by dragon731012** [comment]
To reproduce it, just load movie web through interstellar or any other proxy. After you click the movie, it returns an error. https://gointerstellar.app
