### ISSUE TITLE
[Bug]: Turnstile failures aren't properly handled

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#580]
### What happened?

When you fail a turnstile catpcha, it screen stays blank.
What should happen is an interactable captcha should show up to verify explicitely if the inivisible one fails.
On top of that, it should also show a proper loading screen for captcha and also a proper error if metadata load fails.

### Steps to reproduce?

1. Use a fail-only token in .env
2. watch anything
3. blank screen

### Other relevant information

May be tricky, because the video player needs to always work in fullscreen, and the widget is not in the fullscreened element.

**Comment by zisra** [comment]
I would suggest storing the solved captcha in the cookie/localstorage for a few hours so it doesn't need to be used for every request. Most sites like chatgpt do this

**Comment by mrjvs** [comment]
Turnstile tokens are only valid for 300 seconds. Storing won't help us. 

https://developers.cloudflare.com/turnstile/frequently-asked-questions/

**Comment by LazaroFilm** [comment]
When the turnstile fails, could we have an error message displayed and/or a spinner while it's attempting it? The black screen makes me think it crashed. this is especially true on my LG tv web browser which is pretty slow.

**Comment by mrjvs** [comment]
Yes, this is mentioned in the issue body
