### ISSUE TITLE
[Feature]: Browser extension for more sources

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#581]
### What feature do you want to add?

Browser extension that bypasses CORS restrictions.

### Why do you want to have this feature?

There are a lot of sources that can't be used because they are either too many requests, have CORS limitations or are IP locked.
All of these limitations can be bypassed if we work with a browser extension.

### Anything other details to share?

- This browser extension needs to work with other domains as well, for self hosters. But not automatically (that would be a security risk), just allow the user to register their domain.
- Browser extension should be 100% optional, it's only to improve on the app non-intrusively
- I'm not sure if media requests (video tag) can have their headers modified through extensions, itll need to be investigated
- It can be used for any proxy request, to lower proxy usage.
- upcloud has slow streams because wrong referrer header. if we add a `Stream.preferredHeaders` field to a stream, we can use the browser extension to speed up upcloud.

**Comment by lonelil** [comment]
Might help as an example: https://github.com/hoppscotch/hoppscotch-extension

**Comment by mrjvs** [comment]
I investigated if its possible over at https://github.com/movie-web/extension.
And for chrome is seems completely possible to do, it can overwrite all headers we need and it also triggers for calls made by video elements.

For firefox I haven't tested yet, but they implement similar extension API's so I don't see why it wouldn't work.
