### ISSUE TITLE
[Bug]: Movie ui is not disappearing even when u wait 3+s on ps4 browser.

### ISSUE THREAD

**Issue by atomiciscool** [movie-web/movie-web#584]
### What happened?

![image](https://github.com/movie-web/movie-web/assets/146490689/936f1f8f-a790-4b69-bcb7-1d0c9a4f4f4c)
The movie ui isn't dissapearing, (controls and etc) when its supposed to when u don't do anything for 3+ secondes.

### Steps to reproduce?

1. go to the ps4 browser
2. type movie-web.app
3. choose a movie
4. look

**Comment by binaryoverload** [comment]
Fixed in #583, will be merged as part of the next update

**Comment by mrjvs** [comment]
It isn't the same bug. I checked with them before the bug report.
My bad, I should've kept you updated.

**Comment by atomiciscool** [comment]
> It isn't the same bug. I checked with them before the bug report. My bad, I should've kept you updated.

So it will be fixed in next updated or not ?

**Comment by mrjvs** [comment]
It isn't fixed yet, there no ETA on when it will be fixed.

**Comment by atomiciscool** [comment]
> It isn't fixed yet, there no ETA on when it will be fixed.

okay :)

**Comment by Invisible40** [comment]
I am getting this too on my Brave browser and have been for a few days

**Comment by ForrestFire0** [comment]
Can second this, in chrome, just happened now.

**Comment by vladmashk** [comment]
I have this as well

**Comment by mrjvs** [comment]
@atomiciscool can you retest this? With #702 being resolved, this could maybe also be fixed through the same code.

**Comment by JorrinKievit** [comment]
Closing because it's stale
