### ISSUE TITLE
[Bug]: Backend false values still count as true

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#586]
### What happened?

configuring any boolean value in the config makes it read it as true

### Other relevant information

This is caused by using `z.coerce.boolean()`. it reads any string as true. instead of reading "false" as false.

**Comment by gsi-kevincarrera** [comment]
Is this still open?

**Comment by qtchaos** [comment]
> Is this still open?
Yep

**Comment by gsi-kevincarrera** [comment]
I would like to work on it

**Comment by binaryoverload** [comment]
> I would like to work on it

Go for it, I have assigned you

**Comment by Ayushmaanagarwal1211** [comment]
the reason for this error is if the length of the string is 0 then it will return false otherwise whatever is a string whose length is more than 0 it will return true .
Solution :- it can be solved by comparing that string with "false" if true then set that string to false otherwise do not change.

**Comment by gsi-kevincarrera** [comment]
You can work on it, not problem

**Comment by mrjvs** [comment]
switched assignee, @spewmaker you can work on it

**Comment by spewmaker** [comment]
@mrjvs do you mind moving this ticket to "In Progress"

**Comment by qtchaos** [comment]
> @mrjvs do you mind moving this ticket to "In Progress"

We don't have a tag for that, once PR gets merged issue will be closed.
