### ISSUE TITLE
[Bug]: Turnstile support in simple-proxy breaks other platforms

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#587]
### What happened?

SubtleCrypto is not supported on node (maybe also not on aws lambda).
So running it at all, even with turnstile disabled, will make it crash.

**Comment by JohnWickmann** [comment]
not really sure

**Comment by utsavpatel51** [comment]
I was also trying setting up simple-proxy via

`docker run -p 3000:3000 ghcr.io/movie-web/simple-proxy:2.1.0@sha256:931d4421b6d55fc27c0b093e1e232b7b8defc0649bf02a78dd5db9a520625b49`.

This will work and will server will start listening on 3000, but when you try

`curl http://localhost:3000` or use `VITE_CORS_PROXY_URL=https://localhost:3000`

it's giving 
`{"url":"/","statusCode":500,"statusMessage":"","message":"SubtleCrypto not supported!"}`

**Comment by mrjvs** [comment]
Use cloudflare in the meantime. It's not recommended to run this on a server anyway, it exposes it's ip to the providers.

**Comment by sweenu** [comment]
> Use cloudflare in the meantime. It's not recommended to run this on a server anyway, it exposes it's ip to the providers.

This would be good warning to include in the docs! I hadn't thought of it. It's a good point.
