### ISSUE TITLE
[Feature]: Segment labeling support

### ISSUE THREAD

**Issue by sooswastaken** [movie-web/movie-web#592]
### What feature do you want to add?

Labeling segments such as recaps, intros, and outros. They can be submitted by users, or intros/outros can be matched from other episodes with similar content (frames/audio of the beginning and end of an episode matching would mean a repeated segment, which then can be skipped. 

### Why do you want to have this feature?

Other sites support it such as Netflix and other anime websites.

**Comment by mrjvs** [comment]
duplicate or similar nature to #347
