### ISSUE TITLE
[Feature]: Add in the settings the default audio language that we want to use.

### ISSUE THREAD

**Issue by zyrpion** [movie-web/movie-web#600]
### What feature do you want to add?

Add in the settings the default audio language that we want to use.

### Why do you want to have this feature?

At the moment, everything is in English, but I believe that it might interest people to be able to choose the language of the audio.

### Anything other details to share?

I would see things this way.

- In the "movie-web/providers" project, add to file "src/providers/base.ts":
  ```
  export type SourcererOptions = {
    ...
    language?: string, // default "en"
    ...
  }
  ```
   
- In the application settings, we could display the list of languages available from different providers.
- One could choose a primary and a secondary language.
- Then, it would only be a matter of adding providers from other countries.

**Comment by Vijaykv5** [comment]
Yeah I think it's a great Idea.
but how we  generate custom languages ?

**Comment by spacedog4** [comment]
Yes I think in the provider we could have an attribute for languages availables for that provider

just like the flags for example:
```
export const goMoviesScraper = makeSourcerer({
  id: 'gomovies',
  name: 'GOmovies',
  rank: 110,
  flags: [flags.CORS_ALLOWED],
```

**Comment by zyrpion** [comment]
@Vijaykv5 in fact, the idea would be to be able to add new providers that don't necessarily offer content in English.

@spacedog4 It might be a good idea to use flags for this, I hadn't thought of that!

**Comment by JorrinKievit** [comment]
We have some sources that support different audio languages. There is now an audio selector in the player to switch between them. It preselects the language based on your preference
