### ISSUE TITLE
[Feature]: README.md: Add social sharing badges to encourage community engagement.

### ISSUE THREAD

**Issue by vijaysingh2219** [movie-web/movie-web#601]
### What feature do you want to add?

I want to add social sharing badges to the README.md file.

### Why do you want to have this feature?

This will provide easy ways for users to share the movie-web repository on various platforms such as X, Reddit, Telegram, WhatsApp, Mastodon, and LinkedIn. These badges aim to enhance the visibility of the movie-web open-source project and encourage community involvement.

**Comment by mrjvs** [comment]
Were not interested in encouraging sharing movie-web. It's fine the way it is
