### ISSUE TITLE
[Chore]: Improve Clarity in Captioning Options

### ISSUE THREAD

**Issue by vijaysingh2219** [movie-web/movie-web#603]
## Description

The current label for the "enableCaptions" option in the video player UI is "Enable Captions." While this is clear, we can enhance it for better inclusivity and understanding. Proposing to update the label to "Enable Captions/Subtitles" to explicitly indicate the availability of both captions and subtitles.

Proposed Change:

```json
"enableCaptions": "Enable Captions/Subtitles"
```

### Benefits:

Provides a more concise label.
Clearly communicates the availability of both captions and subtitles.
Enhances the user experience for individuals who may benefit from either feature.

### Additional Context:

This change aligns with our commitment to accessibility and user-friendly design. It ensures that users easily comprehend the available options for captioning/subtitling in the video player.

**Comment by mrjvs** [comment]
It's a bit verbose imo, may not even fit in terms of length.

@binaryoverload what do you think?

**Comment by binaryoverload** [comment]
I think we can change it to just subtitles, as that seems to be regarded as the overall term (Captions are referred to sometimes as intralingual subtitles)

So just "Enable Subtitles" I think

This goes for all instances of captions in the translations.

**Comment by binaryoverload** [comment]
@mrjvs happy with that?

**Comment by mrjvs** [comment]
Yes, sounds good.
Make sure to also remove the updated keys from the other languages, as they aren't correctly translated anymore. (Remove as in actually remove, not blank them)

**Comment by binaryoverload** [comment]
> > Yes, sounds good. Make sure to also remove the updated keys from the other languages, as they aren't correctly translated anymore. (Remove as in actually remove, not blank them)
> 
> @mrjvs Thanks for the approval! Could you please clarify which keys in the other languages should be removed?

Don't worry about removing, changing the source string automatically marks the other languages as "Needs editing"

**Comment by mrjvs** [comment]
When you change a text in the English language. You should remove that same text key in the other language files.

Removing a key will notify existing translators for that language about new things to translate.
