### ISSUE TITLE
[Feature]: change font family of captions

### ISSUE THREAD

**Issue by theMasix** [movie-web/movie-web#606]
### What feature do you want to add?

Adding the ability to set the `font-family` of subtitles using Google Fonts provider

### Why do you want to have this feature?

To have a better experience while reading captions.

### Anything other details to share?

User Journey:
- user goes to web app settings, "captions" section
- there is a select menu with a search feature through Google Fonts provided fonts
- after selecting the custom font, the player sets the `font-family` of `SubtitleView` component and loads the font by adding its link to the header.

**Comment by robertsspaceindustries** [comment]
I have a pr for this, can I get assigned?

**Comment by binaryoverload** [comment]
We'd like subtitle customisation to stay simple, so we won't be doing this.
