### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by humbertoribeiro99** [movie-web/movie-web#607]
### What feature do you want to add?

Coloque legendas na série One Piece em português

### Why do you want to have this feature?

Porque sou brasileiro, ainda não sei o inglês fluente

**Comment by castdrian** [comment]
duplicate, see https://github.com/movie-web/movie-web/issues/482

**Comment by JipFr** [comment]
We don't control the subtitles ourselves, it comes from our providers. You can upload your own subtitles that you get from OpenSubtitles or some such place in the menu.
