### ISSUE TITLE
[Feature]: Improved / custom video player

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#61]
this is so we can modify exactly how the video player functions, some ideas:
 - episode selector & season selector can be embedded into the video player
 - lazy load subtitle files
 - better looking UI for the loading/buffering

**Comment by parnexcodes** [comment]
You could use vimejs : https://vimejs.com/
It's customisable.

**Comment by TGlide** [comment]
Uploading custom subtitle files would be a good feature too

**Comment by mrjvs** [comment]
> Uploading custom subtitle files would be a good feature too

Made a new issue for it to track that progress: #136

**Comment by mrjvs** [comment]
resolved with latest release
