### ISSUE TITLE
[Feature]: Brazilian Portuguese

### ISSUE THREAD

**Issue by alphazero-dev** [movie-web/movie-web#611]
### What feature do you want to add?

Brazilian portuguese language support for both subtitles and dubbing.

### Why do you want to have this feature?

Because I am from Brazil, so my native language is portuguese brazilian.
If I wanna watch with my friends or family, it would be nice to have a brazilian portuguese version.

**Comment by robertsspaceindustries** [comment]
**movie-web** does not control the content and that includes subtitles.

**Comment by Suburbanno** [comment]
@robertsspaceindustries Brazilian Portuguese does not appear on the website in the option to change the interface language.

**Comment by robertsspaceindustries** [comment]
> @robertsspaceindustries Brazilian Portuguese does not appear on the website in the option to change the interface language.

Translations are probably unfinished, but it would be an option. **The locale exists.**

**Comment by robertsspaceindustries** [comment]
> @robertsspaceindustries Brazilian Portuguese does not appear on the website in the option to change the interface language.

The locale already exists.

**Comment by Suburbanno** [comment]
> > @robertsspaceindustries Brazilian Portuguese does not appear on the website in the option to change the interface language.
> 
> The locale already exists.

yes, it exists and is 100% finished on the weblate, but it does not appear on the website.

**Comment by binaryoverload** [comment]
> > > @robertsspaceindustries Brazilian Portuguese does not appear on the website in the option to change the interface language.
> > 
> > 
> > The locale already exists.
> 
> yes, it exists and is 100% finished on the weblate, but it does not appear on the website.

It does appear on the website, just as "Portuguese"

**Comment by Suburbanno** [comment]
> > > > @robertsspaceindustries Brazilian Portuguese does not appear on the website in the option to change the interface language.
> > > 
> > > 
> > > The locale already exists.
> > 
> > 
> > yes, it exists and is 100% finished on the weblate, but it does not appear on the website.
> 
> It does appear on the website, just as "Portuguese"

What appears on the website is only Portuguese from Portugal, it should also appear Portuguese from Brazil.

**Comment by binaryoverload** [comment]
There is a PR to resolve this, #619
