### ISSUE TITLE
[Bug]: Subtitles are not even correct, we need better sources

### ISSUE THREAD

**Issue by mkiisoft** [movie-web/movie-web#613]
### What happened?

Japanese subtitles, for example, are not even Japanese... and the subtitles are... interesting.

<img width="1415" src="https://github.com/movie-web/movie-web/assets/3221810/559671e9-8a2d-4a46-8921-e93dea47b670">

### Steps to reproduce?

Search for "Your name", choose "Japanese" as Subtitles. Link: https://movie-web.app/media/tmdb-movie-372058-your-name

### Other relevant information

How are subtitles being selected? Is there any better source for them?

**Comment by binaryoverload** [comment]
The subtitles are currently provided through our sources. We were going to use Opensubtitles, but the recent change in their API meant that it wouldn't work well for us and we had issues getting it to work reliably.

If you've got any suggestions for subtitle sources we're all ears

**Comment by Akarn-26** [comment]
I think Google's translate API could be an options but it has limited characters i guess

**Comment by ameer4** [comment]
> The subtitles are currently provided through our sources. We were going to use Opensubtitles, but the recent change in their API meant that it wouldn't work well for us and we had issues getting it to work reliably.
> 
> If you've got any suggestions for subtitle sources we're all ears

For me subscene.com is most reliable source for years, especially for Arabic subtitles.
But it is very slow, still working in some kodi addon:
https://a4k-openproject.github.io/a4kSubtitles/

I think the best solution is use multiple provider (like kodi plugin above), plus a custom one, also an option to upload subtitle directly from device, or even use custom url (like local folder) for auto selection.

**Comment by mrjvs** [comment]
Subtitles are the sources issue, not fixable
