### ISSUE TITLE
[Bug]: Multiple subtitles of the same language appear both selected

### ISSUE THREAD

**Issue by robertsspaceindustries** [movie-web/movie-web#614]
### What happened?

![image](https://github.com/movie-web/movie-web/assets/49074962/67f9616c-cdd9-49a6-93ed-6155fa1ddf51)

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

Browser: Vivaldi

Bug visible on [Full House S01E01](https://movie-web.app/media/tmdb-tv-4313-full-house/12718/297397)

**Comment by CelestialLemon** [comment]
I think it's setting the selected prop on the option based on language instead of it's id/index. I would like to work on this.

**Comment by mrjvs** [comment]
You're right, the new version of the provider package will have ids for subtitles. So we can fix this issue

**Comment by itaibo** [comment]
@CelestialLemon true. However index might change if user filters the caption list.

I reviewed the code and looks like all the function invocations relative to captions are done using the `language` value, no ID.

I've drafted a solution that deduplicates the list of available captions: https://github.com/itaibo/movie-web/commit/b5b33e27013e00bf566bd2cf55111f0463bea306

**Comment by mrjvs** [comment]
I'll assign you, but you'll have to also implement the new provider package version when it gets published later today.

**Comment by itaibo** [comment]
As I see now thanks to @mrjvs info, in case of having IDs the solution will be changing the `selected` prop:

```js
<CaptionOption
        key={`${i}-${v.url}`}
        countryCode={v.language}
        selected={selectedCaptionId === v.id}
        loading={v.language === currentlyDownloading && downloadReq.loading}
        error={
          v.language === currentlyDownloading && downloadReq.error
            ? downloadReq.error.toString()
            : undefined
        }
        onClick={() => startDownload(v.language)}
      >
        {v.languageName}
      </CaptionOption>
```

Thanks for the clarification!
