### ISSUE TITLE
[Bug]: no gear settings icon when on computer screen

### ISSUE THREAD

**Issue by LazaroFilm** [movie-web/movie-web#617]
### What happened?

The gear icon to access the movie's settings is not visible on a computer screen when the movie has not started. This prevents you from choosing the source if the movie doesn't start right away.

### Steps to reproduce?

Open movie-web on a computer screen = no gear icon, shrink the browser window's width to match the ratio of a phone, the icon appears.

### Other relevant information

wide viewport, no gear icon.
![large viewport](https://github.com/movie-web/movie-web/assets/18351100/0cb30c37-4368-4fce-b915-c517f0493321)

narrow viewport, gear icon appears.
![narrow viewport](https://github.com/movie-web/movie-web/assets/18351100/6051ae22-1393-4a19-942b-c40da1409d9d)

**Comment by LazaroFilm** [comment]
This issue also on my LG TV's browser which can't be resized.

**Comment by qtchaos** [comment]
Have encountered the same bug, I'll look into it once I get home^^

**Comment by JipFr** [comment]
Resolved in #621
