### ISSUE TITLE
[Feature]: Add language variants such pt and pt-BR

### ISSUE THREAD

**Issue by GustavoMelloGit** [movie-web/movie-web#618]
### What feature do you want to add?

I want to add the possibility to have pt-BR language support

### Why do you want to have this feature?

This opens up a vast array of possibilities for regionalizing the app

### Anything other details to share?

Already made the necessary changes, just need this issue approval in order to open the [PR](https://github.com/movie-web/movie-web/pull/619)

**Comment by mrjvs** [comment]
Approved

**Comment by Magrid0** [comment]
Can I try working on this?

**Comment by binaryoverload** [comment]
@Magrid0 there is already a PR #619 :D

**Comment by Magrid0** [comment]
> there is already a PR #619 :D

oh sorry i didn't see that
