### ISSUE TITLE
[Feature]:  paid providers

### ISSUE THREAD

**Issue by GamerClassN7** [movie-web/movie-web#624]
### What feature do you want to add?

Hello,
Would be possible to add ability to fetch media from services like netflix ?  Maybe with simple config section for filling in credentials or api token ?

Ore implementation of some sort of plugins system whitch can be writen by user :)

### Why do you want to have this feature?

I really want to use all services i am pay for,  in one nice package, I would be nice, to have every (possible) stream service in your nice web interface :)

### Anything other details to share?

For additional context providers for example for KODI.

https://github.com/kodi-czsk/plugin.video.ivysilani
https://github.com/CastagnaIT/plugin.video.netflix

Also when selfhosting full package backen/frontend, would be possible to add simpel config file which providers to use and whitch not ?

**Comment by binaryoverload** [comment]
Scraping / Accessing DRM content such as Netflix is not possible for us - primarily because it would violate their terms of service, and their lawyers are scary!

**Comment by GamerClassN7** [comment]
> Scraping / Accessing DRM content such as Netflix is not possible for us - primarily because it would violate their terms of service, and their lawyers are scary!

Understood
