### ISSUE TITLE
[Feature]: Search when typing is over

### ISSUE THREAD

**Issue by Safouene1** [movie-web/movie-web#625]
### What feature do you want to add?

instead of sending dozens of requests when I type EVERY letter, I  want to change it to send the request ONLY when the **user finish typing**

### Why do you want to have this feature?

Reduces the amount of requests called to the backend

### Anything other details to share?

I would love to work on it

**Comment by mrjvs** [comment]
This is already implemented

**Comment by beSaif** [comment]
Basically a search denouncer.

**Comment by binaryoverload** [comment]
> Basically a search denouncer.

We denounce search at every possible turn
