### ISSUE TITLE
[Feature]: Add ARM support for Docker images

### ISSUE THREAD

**Issue by Caio-Nogueira** [movie-web/movie-web#627]
### What feature do you want to add?

Publish a new Docker image for Arm processors to support development on Apple chips

### Why do you want to have this feature?

I am trying to launch the proxy locally. However i can't run the latest image (`ghcr.io/movie-web/simple-proxy:2.1.0`).

### Anything other details to share?

 Would be nice to be able to pull the image instead of building it locally

**Comment by binaryoverload** [comment]
At the moment the proxy doesn't support any platforms that aren't Cloudflare

But once that's fixed we can definitely add an ARM target in our image build 👌

**Comment by binaryoverload** [comment]
Although one does question why bother, just run a Cloudflare worker and then you don't have to bother with a Docker image 👀

**Comment by Caio-Nogueira** [comment]
Thank you for the help. I was just trying to run the application locally and Docker seemed like the quickest way to do it. I'll setup the Cloudflare worker then.

**Comment by binaryoverload** [comment]
I've added the https://github.com/movie-web/movie-web/labels/repo-backend tag as we can also do this for the backend image

**Comment by weeryan17** [comment]
Can I take this one?
