### ISSUE TITLE
[Bug]: Wrong Nepal Flag

### ISSUE THREAD

**Issue by MandipJoshi** [movie-web/movie-web#628]
### What happened?

In Locale Settings the Nepali flag displayed is wrong flag.

### What browsers are you seeing the problem on?

Firefox

### Steps to reproduce?

Go to locale settings page and click on Application language drop down

**Comment by binaryoverload** [comment]
Fixed in #623

**Comment by mrjvs** [comment]
@binaryoverload I think you mixed up estonia and nepal

**Comment by binaryoverload** [comment]
> @binaryoverload I think you mixed up estonia and nepal

You would be correct, I was confusion
