### ISSUE TITLE
[Feature]: Can we show local videos on web

### ISSUE THREAD

**Issue by ALIJ0N** [movie-web/movie-web#630]
### What feature do you want to add?

I run this project without any errors but I can't configure third party service that's why I want to show local "Videos" folder into movie-web

### Why do you want to have this feature?

add local video support

**Comment by ippbxusa** [comment]
The goal of [World Wide Digest](https://worldwidedigest.com/), which was established in 2006, is to impart technological literacy to everyone. Every item on our crew, which consists of computer aficionados, should provide readers with some useful advice, explainers, tech tips, and more. We make technology approachable and accessible to everyone, in contrast to trade websites that target tech enthusiasts.

**Comment by binaryoverload** [comment]
This is outside of this project's scope - we do not plan on doing this.
