### ISSUE TITLE
[Feature]: Add Hindi Translation

### ISSUE THREAD

**Issue by TheGuyDangerous** [movie-web/movie-web#634]
### What feature do you want to add?

Hindi Translation

### Why do you want to have this feature?

As a native hindi speaker, and hindi being used by a majority of the population in India (North India), I think it would be a valuable contribution to your repository.

### Anything other details to share?

Assign me the  issue. I have the files ready to send a PR in.

**Comment by mrjvs** [comment]
Use our translation tool: https://weblate.movie-web.app

**Comment by TheGuyDangerous** [comment]
@mrjvs I've added the translations, kindly have a look !
