### ISSUE TITLE
[Bug]: Site Can't be reached If the page is refreshed when content is not found

### ISSUE THREAD

**Issue by tejas-mn** [movie-web/movie-web#640]
### What happened?

Getting "The Site Can't be reached" when the page is refreshed when content is not found.
The back button and links visited previously also shows it can't be reached.

![image](https://github.com/movie-web/movie-web/assets/68629215/e2432b89-7f91-4b02-a13b-c734f8cd6338)

After refreshing the above page:
![image](https://github.com/movie-web/movie-web/assets/68629215/1e20efb3-9ea8-4b36-95b3-01bb22315657)

Same issue persists if I try to go back and even try to refresh here: All the back links shows it can't be reached.
![image](https://github.com/movie-web/movie-web/assets/68629215/0a83012e-52a1-4646-b66c-d92f35a1e420)

The only solution is to manually go to home page by typing the home page URL.

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

1. Go to any movie/show which is not available
2. Refresh the page.
3. Try to go back through back button.

Expected: When refreshed it should again display no content found and back links should work in step 2 and 3.
Actual: Shows site can't be reached if we try to do step 2 and 3.

**Comment by binaryoverload** [comment]
This doesn't seem to be an issue with us - please make sure you're using a DNS provider such as [1.1.1.1](https://1.1.1.1) to make sure connections are not being blocked.
