### ISSUE TITLE
[Feature]: Support for torrents

### ISSUE THREAD

**Issue by DarthGigi** [movie-web/movie-web#644]
### What feature do you want to add?

Would it be possible to add support for torrent files? Either to use your own or a torrent site like torrentgalaxy.to?
This will allow higher-quality videos without additional bandwidth expense on the servers, as the torrent contents will (or should) be downloaded to the client only.

### Why do you want to have this feature?

It would be nice for people who want to watch higher quality videos to be able to do so via this app.

**Comment by FurkanCodes** [comment]
I am not sure if this would be allowed due to copyright and legal issues, otherwise this can be done with WebTorrent I assume.

**Comment by DarthGigi** [comment]
> I am not sure if this would be allowed due to copyright and legal issues, otherwise this can be done with WebTorrent I assume. 

If it's not allowed, I do wonder what the difference is between a torrent and using the streaming sites this app uses. I don't think those sites have actually bought licenses for their content either, but I may be wrong about how those sites operate?

**Comment by FurkanCodes** [comment]
> > I am not sure if this would be allowed due to copyright and legal issues, otherwise this can be done with WebTorrent I assume.
> 
> If it's not allowed, I do wonder what the difference is between a torrent and using the streaming sites this app uses. I don't think those sites have actually bought licenses for their content either, but I may be wrong about how those sites operate?

With Peer-to-peer connection such as torrenting, ISP can easily track your location when you stream them, thus resulting in legal action. It may be added with a legal notice that user, when handling torrent in this app, is %100 responsible for his/her actions. I might be overthinking here as well, just my two cents! :)

**Comment by binaryoverload** [comment]
We have looked into this before, but due to a lack of seeders for WebTorrents, it's very slow, and the content coverage is just not there.

**Comment by FurkanCodes** [comment]
> We have looked into this before, but due to a lack of seeders for WebTorrents, it's very slow, and the content coverage is just not there.

Can't users upload their own torrent files through WebTorrents?
