### ISSUE TITLE
[Bug]: Some languages do not have a flag

### ISSUE THREAD

**Issue by russssl** [movie-web/movie-web#645]
### What happened?

Some languages do not have a flag icon (Like Hindi or Ukrainian)

### Steps to reproduce?

Open Settings, open language picker, see the bug

### Other relevant information

I suppose this is because country codes in i18n (like ua and uk as ukrainian)

**Comment by russssl** [comment]
upd: very quick and easy fix 

FlagIcons.tsx
```
// Country code overrides
const countryOverrides: Record<string, string> = {
  ....(other overrides)
  uk: "ua",
  hi: "in",
};
```

**Comment by russssl** [comment]
https://github.com/russssl/movie-web

**Comment by binaryoverload** [comment]
> upd: very quick and easy fix
> 
> FlagIcons.tsx
> 
> ```
> // Country code overrides
> const countryOverrides: Record<string, string> = {
>   ....(other overrides)
>   uk: "ua",
>   hi: "in",
> };
> ```

You're welcome to make a PR to this effect 😄

**Comment by russssl** [comment]
@binaryoverload yes I would happy to help, also I finished ukrainian translation fully, so can it be added too ?

**Comment by mrjvs** [comment]
You can make a PR: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

For the translations, You can use our translation tool: https://weblate.movie-web.app/

**Comment by russssl** [comment]
@binaryoverload @mrjvs also i have a question about toka pokana language flag, should I just put .svg somewhere inside assets lets say or create more general solution for flags that are unknown by flag-icons package

**Comment by binaryoverload** [comment]
> @binaryoverload @mrjvs also i have a question about toka pokana language flag, should I just put .svg somewhere inside assets lets say or create more general solution for flags that are unknown by flag-icons package

If you look inside the FlagIcon component, you can see how we do it for pirate and minionese
