### ISSUE TITLE
[Bug]: PWA Splash does not work on prod (file not found)

### ISSUE THREAD

**Issue by Jecta** [movie-web/movie-web#647]
### What happened?

It cannot find the files along with some other non-pwa related in the head/meta while they do exist in /public

https://github.com/movie-web/movie-web/assets/68130184/17d04191-833f-4e6c-ba24-9b2991c87184

### Steps to reproduce?

1. add app to homescreen on iOS or iPadOS

--or--

1. inspect element and click the links, some works some

**Comment by Jecta** [comment]
is the first / unnecessary?

**Comment by binaryoverload** [comment]
@JipFr can you test this please?

**Comment by JipFr** [comment]
I believe this is an issue to do with the PWA caching. I just checked, and the splash screens _are_ built in the CloudFlare process. When I go to https://movie-web.app/splash_screens/iPhone_11__iPhone_XR_landscape.png directly it shows me the site's error page, but when I reload without cache it loads fine. 

Perhaps something messed up is happening in the service worker?

**Comment by Jecta** [comment]
That is in fact the case for me as well

https://github.com/movie-web/movie-web/assets/68130184/4c59a7dd-f226-4708-9568-46656be41938

**Comment by Jecta** [comment]
When working on my own app's PWA using the same method i found out you need to add the following above the apple-touch-icon for the splash screen to work:

```html
<meta name="apple-mobile-web-app-capable" content="yes" />
```

**Comment by Jecta** [comment]
I'm not sure if this'll actually fix it due the cache issue but i have hopes it will as it did for my own PWA using that website Binaryoverload linked me and even if it doesnt because of that cache thing you still need this for the splashes to work anyway.

**Comment by JipFr** [comment]
Really? I'd assume that if it can be added to the home screen (like having a manifest and stuff allows you to do), that would be enough. Allow me to test.

**Comment by Jecta** [comment]
I found this to be true when developing my own app without that line it was a black screen on load but with it it worked like this:

https://github.com/movie-web/movie-web/assets/68130184/268b3a40-666b-4787-a0df-03f70589e876

**Comment by JipFr** [comment]
I _think_ you're right. Adding it in dev shows the splash screen, though dev obviously doesn't have the PWA stuff so without the meta tag it doesn't even open standalone. Might be worth adding the tag!

**Comment by Jecta** [comment]
So what do you want me to do now? make a new pr for that 1 line or does anyone put it in or?

**Comment by JipFr** [comment]
I'll do it later!

**Comment by JipFr** [comment]
The question is: do we close this issue? It fixes the splash screens not actually showing up, but the files are still cached improperly, no?

**Comment by Jecta** [comment]
Maybe we should close it once the tag has been added and create a new issue for the improperly cached files since it's not only the splash screens that have this issue as seen in my first comment in its attachments

**Comment by Jecta** [comment]
#709

**Comment by binaryoverload** [comment]
Resolved in #709
