### ISSUE TITLE
[Bug]: m3u8 is broken on gomostream

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#65]
throws a 404 on the m3u8 manifest request

You can replicate with this movie: `birdman`

**Comment by MineEaster** [comment]
screenshot please?

**Comment by mrjvs** [comment]
> screenshot please?

Not sure how this helps exactly but here you go. 

The gomostream provider simply gives the wrong stream link for m3u8 sources, it throws a 404 when it tries to request it. 

![Screenshot_20220502-070518_Firefox.jpg](https://user-images.githubusercontent.com/19330965/166186743-ae7432d7-1f89-4f77-866a-57c4720d90c9.jpg)
