### ISSUE TITLE
[Feature]: Auto-growing all contributor list

### ISSUE THREAD

**Issue by TheGuyDangerous** [movie-web/movie-web#653]
### What feature do you want to add?

An automatic contributor list could be great, to feature  all the contributors.. without ever updating the list.

For example - 
This is the current contri list -
![image](https://github.com/movie-web/movie-web/assets/78858516/978db4e7-a8fa-4425-9afa-eb66f47f819f)

This is what it could look like -
![image](https://github.com/movie-web/movie-web/assets/78858516/069256d1-5bf3-4e3a-8961-2df98295424b)

### Why do you want to have this feature?

It's humble to recognize all the contributors that have an impact on the project. Also helps in more visibility across popular repositories.

### Anything other details to share?

Do let me know, and I'll be happy to send in a PR, or update it - according to the maintainer's preferences. :)

**Comment by mrjvs** [comment]
Sure, sounds good
