### ISSUE TITLE
[Feature]: hold on to the spacebar to speed up the video playing

### ISSUE THREAD

**Issue by liwd190019** [movie-web/movie-web#654]
### What feature do you want to add?

hold on to the spacebar for about 1.5 seconds and the video playing speed gets increased by 2x.

### Why do you want to have this feature?

don't want to waste time when watching boring parts, but the skipped parts may be useful for the subsequent plot.

**Comment by liwd190019** [comment]
Hi, I'm new here. As I'm trying to test my changes on my local machine, I found that I can't search movie correctly even after setting up TMDB api key. Can someone give me some hints? Maybe I need to look into the backend code?

<img width="760" alt="Screenshot 2023-12-30 at 2 29 40 AM" src="https://github.com/movie-web/movie-web/assets/97966234/519df47b-7106-4f47-ba0e-5895f5e636f2">

(This screenshot is taken when I'm testing on localhost)

Thanks!

**Comment by Ayushmaanagarwal1211** [comment]
> Hi, I'm new here. As I'm trying to test my changes on my local machine, I found that I can't search movie correctly even after setting up TMDB api key. Can someone give me some hints? Maybe I need to look into the backend code?
> 
> <img alt="Screenshot 2023-12-30 at 2 29 40 AM" width="760" src="https://private-user-images.githubusercontent.com/97966234/293448679-519df47b-7106-4f47-ba0e-5895f5e636f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMDI3NzUsIm5iZiI6MTcwNDAwMjQ3NSwicGF0aCI6Ii85Nzk2NjIzNC8yOTM0NDg2NzktNTE5ZGY0N2ItNzEwNi00ZjQ3LWJhMGUtNTg5NWY1ZTYzNmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA2MDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNjhkOTQ1NWNmYjU1MTg1NmQwMjk0OWYwYTJmZjcwYmM0ODVlMTkxOTYyMjk4NWM2NTVhNTE4NTYyYjFhZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aZqoxVnuS2FS1q2purj4lZQ55fGh-AzEX16Vkxg4ygA">
> (This screenshot is taken when I'm testing on localhost)
> 
> Thanks!

Hlo for fix this issue u have to rename example.env file to .env and enter the keys required for backend in .env file ."VITE_TMDB_READ_API_KEY" you will get this key from tmdb website and you also need "VITE_CORS_PROXY_URL" via cloudflare for more details you can go to  this "https://docs.movie-web.app/self-hosting/hosting-intro" link .

**Comment by JipFr** [comment]
I don't think we really need this feature. The skip is 5 seconds and we already have a 2x speed option in settings.

**Comment by qtchaos** [comment]
( we also have shortcuts for speeding up and slowing down the player: `>`, `<`
