### ISSUE TITLE
[Feature]: Fetch Subtitles Automatically

### ISSUE THREAD

**Issue by Laurent-I** [movie-web/movie-web#656]
### What feature do you want to add?

The feature will enable the platform to automatically search and fetch subtitles for the content being played.

### Why do you want to have this feature?

This enhancement can significantly enhance user satisfaction by providing a seamless viewing experience. Users won't need to leave the platform to find subtitles, creating a more immersive and convenient environment.

**Comment by castdrian** [comment]
duplicate https://github.com/movie-web/movie-web/issues/124
