### ISSUE TITLE
[Feature]: Allow for subtitle sizes above 200%

### ISSUE THREAD

**Issue by Swexti** [movie-web/movie-web#660]
### What feature do you want to add?

The largest subtitle (Edited-To-Add: referred to as "Text Size" in the subtitle customization, if that wasn't clear) size of 200% is still quite small for me. I thought I could just type in something larger than 200%, but nope - clamps at 200% and won't go bigger.

### Why do you want to have this feature?

Again, 200% is still not large enough for me; to me, adding the ability to go beyond 200% (up to maybe 400-500%?) seems simple enough. 100% is absolutely tiny.

### Anything other details to share?

Watching on a 1440p monitor. Subtitles get a little larger if I move movie-web to my 1080p monitor, which I suppose is expected behavior.

**Comment by castdrian** [comment]
yeah I'd say that's a good a11y suggestion

**Comment by mrjvs** [comment]
You can use browser zoom to go larger. We use pretty standard sizes for subs, the fact that 1440p screen its small is due to OS or browser settings.

**Comment by Swexti** [comment]
> You can use browser zoom to go larger. We use pretty standard sizes for subs, the fact that 1440p screen its small is due to OS or browser settings.

I see! Zooming in does work well, thank you!

You're free to close this, if you want. I still think it'd be good to allow for sizes above >200%, but zooming in works good enough for me.
