### ISSUE TITLE
[Feature]: Swap to using `pnpm exec` instead of `npx` in scripts

### ISSUE THREAD

**Issue by qtchaos** [movie-web/movie-web#662]
### What feature do you want to add?

Swap to using `pnpm exec` instead of `npx` in scripts.

### Why do you want to have this feature?

This will help avoid issues with users who have only used `pnpm i` (therefore missing the necessary packages when using `npx`) or lack the `npm` package manager.

### Anything other details to share?

Only an issue with the backend repo. Ill create a PR once i get assigned.

**Comment by binaryoverload** [comment]
This is fine, but just be aware that you don't need to install packages to use `npx` as it automatically installs any packages it needs :D
