### ISSUE TITLE
[Bug]: Movies with missing posters displayed in search results

### ISSUE THREAD

**Issue by ashudevcodes** [movie-web/movie-web#665]
### What happened?

Searching for movies sometimes leads to entries with missing posters. Clicking on these movies often generates a “result not found” message. This creates a bad user experience.

### What browsers are you seeing the problem on?

Firefox

### Steps to reproduce?

1. Go to the search page
2. Search nemo (You found there were two movies that have no poster)
3. click anyone (When you click on those, the result is 'not found')

### Other relevant information

![image](https://github.com/movie-web/movie-web/assets/105356967/8e3a97eb-a603-4a11-a920-311080354a9f)
![image](https://github.com/movie-web/movie-web/assets/105356967/89b0580c-b88f-4faa-9eea-0a3d2b6405d8)

**Comment by JipFr** [comment]
I wouldn't be opposed to filtering out entries without a poster. These are so low-effort we're not likely to _ever_ find streams for them. Thoughts @mrjvs

**Comment by mrjvs** [comment]
I'm not sure if we should remove them completely. I feel like that'll cause issues. Maybe we could just move them to the back of the list though, so they are more out of sight

**Comment by castdrian** [comment]
plus perhaps render a placeholder component rather than an empty space

**Comment by ashudevcodes** [comment]
We could also do this if a movie doesn't show a poster, then we don't render that particular Card component. After all, when we click on it, it will show the message 'movie not found'

**Comment by ashudevcodes** [comment]
like this : @JipFr 
``<MediaGrid>
            {results.map((v) =>
              v.poster === undefined ? (
                ""
              ) : (
                <WatchedMediaCard key={v.id.toString()} media={v} />
              ),
            )}
         </MediaGrid>
         ``
         
component was found in ``movie-web\src\pages\parts\search\SearchListPart.tsx`` folder.

**Comment by castdrian** [comment]
that's a bad idea, if for some reason a poster isn't provided, ie tmdb cdn fails to server an existing poster or it is media that just simply no one has added a poster to it would hide the entire result

**Comment by ashudevcodes** [comment]
> I'm not sure if we should remove them completely. I feel like that'll cause issues. Maybe we could just move them to the back of the list though, so they are more out of sight

Removing them entirely could lead to issues. Yes, we can verify whether the poster is undefined then sort the array based on the poster value, and placing the movie at the end. @mrjvs
