### ISSUE TITLE
[Bug]: home.titles.day.extra - Extra day message won't show up

### ISSUE THREAD

**Issue by Kipoddo** [movie-web/movie-web#666]
### What happened?

The extra day message won't show up at all.

![image](https://github.com/movie-web/movie-web/assets/153996181/5c513c2c-5b2d-449a-840f-6251a0ad7a1c)

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Steps to reproduce?

- Refresh the page until the extra message is supposed to show up

### Other relevant information

- The string `_home.titles.day.extra_` is not translatable on Weblate.

**Comment by mrjvs** [comment]
Core of the bug is that it should check if there are any extra titles before trying to display any. Since day doesn't have extra titles.

**Comment by mrjvs** [comment]
Also congratulations, you got issue #666

**Comment by Kipoddo** [comment]
> Also congratulations, you got issue #666

Good lord , why me

**Comment by usman1100** [comment]
@Kipoddo can you assign this issue to me. My PR should've fixed this one.

**Comment by JipFr** [comment]
This has already been resolved in dev.

**Comment by JipFr** [comment]
Actually no, jvs was right. Sorry!

**Comment by MrBlackGhostt** [comment]
@JipFr if its not solve i want to contribute on this

**Comment by mrjvs** [comment]
@MrBlackGhostt I've assigned you

**Comment by mrjvs** [comment]
We have a random translation hook, you can probably make it return null and handle a fallback where its used

**Comment by JipFr** [comment]
I'm going to be very honest, I failed to read further down on this thread before making my PR. Sorry @MrBlackGhostt !
