### ISSUE TITLE
[Feature]: Add Urdu Translation

### ISSUE THREAD

**Issue by Neutx** [movie-web/movie-web#667]
### What feature do you want to add?

Urdu Translation

### Why do you want to have this feature?

As a native Urdu speaker, and born into a Muslim family I've been learning it since my childhood, I think it would be a valuable contribution to your repository.

### Anything other details to share?

Assing me the issue, I am ready to work on it.

**Comment by mrjvs** [comment]
Our translations are managed on https://weblate.movie-web.app/
It doesn't go through github. You will be able to add Urdu yourself.
