### ISSUE TITLE
[Feature]: global site name or site title from config file or form env file

### ISSUE THREAD

**Issue by vireakvibol** [movie-web/movie-web#669]
### What feature do you want to add?

Is that possible to implement the variable site name or site title from config file or ENV to apply on everywhere that display `movie-app` like at logo, html title, menu or footer etc?

### Why do you want to have this feature?

Its is easy to change just the config file without finding everywhere on the component file.

**Comment by JipFr** [comment]
You don't need to find it in the component files, it's in the locale files.

**Comment by mrjvs** [comment]
We're not going to help remove our credit. If you want to put in the effort, sure. but we're not gonna help you.

**Comment by vireakvibol** [comment]
Got your point thank you very much @mrjvs. Well yes just saw that thank you very much @mrjvs
