### ISSUE TITLE
[Feature]: Move to the top of the page with every new search.

### ISSUE THREAD

**Issue by zaim-abbasi** [movie-web/movie-web#672]
### What feature do you want to add?

Whenever we navigate to the end of the movies grid from the Search page and search for another movie while at the bottom of the page, our search results are shown at the end of the page instead of bringing us to the top.

If you can't understand my issue, you can:
* Search for any movie/show.
* Scroll to the middle or end of the page.
* Now, search for another movie while you are in the middle of the page.
* The new search results will be displayed, and you will find yourself in the middle or at the end of the page where you left off on the last search. Instead, it should bring us to the top of the page with every new search.

### Why do you want to have this feature?

Increases Usability

### Anything other details to share?

It also seems to be a bug ig

**Comment by mrjvs** [comment]
cannot reproduce, will always jump to top
