### ISSUE TITLE
[Feature]: Docker image for frontend

### ISSUE THREAD

**Issue by sweenu** [movie-web/movie-web#675]
### What feature do you want to add?

It would be great if there was also a simple docker image to serve the frontend with nginx for example.

### Why do you want to have this feature?

Deploying and updating the movie-web frontend would take me 2 seconds if I just had a Docker image with the latest version of the movie-web frontend. But with the current situation I have to download the zip file, change manually the configuration file instead of just using env variables and whenever I want to update the frontend I need to go download the latest release instead of having a Docker image of it. Moreover, seeing as I don't want to use an external service to host my website but my own Traefik instance to serve the website, I will need to make myself a nginx container to serve the static files instead of having a community configured one.

### Anything other details to share?

If you agreed to have and maintain that, I could make a PR to add the Dockerfile and the pipeline to deploy the built docker image to the registry.

**Comment by castdrian** [comment]
it also takes to seconds to deploy to vercel or netlify so you really don't have to bother with the local files situation by any means

**Comment by mrjvs** [comment]
There already is a dockerfile, just needs a workflow file so it builds one and publishes to ghcr.

You can (and should) inspire yourself from our backend repo, which has a workflow for docker which works the way we want it to.

I'll approve and assign you

**Comment by weeryan17** [comment]
Seams this has been inactive, can I take it over?

**Comment by sweenu** [comment]
> Seams this has been inactive, can I take it over?

New PR weren't allowed to be open during the new year time on this repository. I was waiting for the restriction to be lifted.

**Comment by jo-chemla** [comment]
Seems like a ghcr.io/movie-web/movie-web GHCR image now does exist, but the docs have not been updated to use it and still rely on [docker build](https://movie-web.github.io/docs/client/deploy#method-3-docker-compose-home-network). Should a new issue be opened for that matter? 

Moreover, it seems that when using that ghcr image then the `BACKEND_URL, CORS_PROXY_URL, and TMDB_READ_API_KEY` are not parsed and correctly populated within movieweb frontend settings. I cannot therefore find a place to edit the `TMDB_READ_API_KEY`. Is this normal behavior? Thanks!

**Comment by binaryoverload** [comment]
@jo-chemla 

The docs list the best way to use build arguments in the Docker version of movie-web. If you use the GHCR version, you cannot use environment vars and have to use a volume to mount the `config.js` file, which is more complicated and doesn't allow all options to be set.

Using local container names and ports within custom proxy workers will not work because the requests are made from the client - so the backend and proxies need to be accessible to the client.

**Comment by jo-chemla** [comment]
Thanks for getting back so quickly. I'll probably have to use the GHCR image + mounted `config.js` - I'm installing movieweb via portainer, and the build image yields an error like the one described [here](https://www.reddit.com/r/portainer/comments/10ltphi/git_not_found_when_trying_to_build_an_image_from/) `"message":"failed to init repo at /var/lib/docker/tmp/docker-build-git: : exec: \"git\": executable file not found in $PATH"}`

Can I just populate this exact [config.js](https://github.com/movie-web/movie-web/blob/dev/public/config.js)? Where should I mount this config.js within the container? Thanks again for your help.

**Comment by binaryoverload** [comment]
The git error message you are seeing should be resolved by installing git to your host (and maybe the Portainer container, I'm not sure where the operation is run exactly)

> Can I just populate this exact [config.js](https://github.com/movie-web/movie-web/blob/dev/public/config.js)?
Yup! Just fill out the values :) 

> Where should I mount this config.js within the container?
The `config.js` file must be mounted at `/usr/share/nginx/html/config.js`

**Comment by jo-chemla** [comment]
Thanks again for getting back so fast. I've indeed already installed git to host, and it seems that I also need to install git to the portainer container to avoid this issue for the docker-build image. 

I've used the referenced config.js file and edited the required `VITE_abc` variables, but that config does not seem to overwrite the one that was previously setup. When looking at the frontend logs, I've seen some permission-denied errors like below:
```
2024/03/12 11:20:39 [error] 31#31: *1 open() "/usr/share/nginx/html/config.js" failed (13: Permission denied), client: frontend-ip, server: localhost, request: "GET /config.js HTTP/1.1", host: "http://frontend-ip:port", referrer: "http://frontend-ip:port"
```

Usually, the way I get around such errors is either by chown/chmod the problematic file/directory (`chmod 755 and chown user:everyone)` or by adding the below `UID/GID` environment variables to the container (these of admin group and user), but this time it did not do the trick. Is there something to do on movieweb ghcr side to make this mounted config.js be readable by the container? Thanks again, 
  
```yaml
    environment:
      - UID=1000
      - GID=100
```

**Comment by binaryoverload** [comment]
Try chowning the config.js file with user and group ID `101` - this is what Nginx users iirc

**Comment by jo-chemla** [comment]
Thanks, this did the trick and the `custom config.js` can now be loaded by the client when connecting to frontend. 

The `App Information` section in the sidebar has the correct `Hostname Backend URL`. There is no way to check in the frontend settings if proxy and tmdb are correctly set, but it does seem like it, parsing through the proxy container logs. 

Note the proxy urls are still editable within frontend settings, (none are provided when first looking at settings) but I imagine this is because each user can set them - and they would be stored in the browser localStorage custom settings, and be applied and override those defined by the server.

**Comment by mrjvs** [comment]
Going to `/admin` (or `/#/admin`) gives you some test tools for people who host. Including tmdb and proxy url tests @jo-chemla 

frontend settings are always editable per user, thats intended behaviour. If they dont edit it, it will fall back to the instance configuration.
