### ISSUE TITLE
[Feature]: Revamp documentation

### ISSUE THREAD

**Issue by qtchaos** [movie-web/movie-web#679]
### What feature do you want to add?

Revamp the docs to add better instructions / more clear wording in certain parts.

### Why do you want to have this feature?

Allows for a better developer experience, especially since movie-web is getting more traction, having better documentation for self-hosting will help a lot with lessening questions in the Discord.

### Anything other details to share?

In the process of doing this anyways, if it is approved and i get assigned ill continue.

**Comment by binaryoverload** [comment]
@qtchaos Assigned
