### ISSUE TITLE
[Bug]: Wrong flag in pt-br translation

### ISSUE THREAD

**Issue by QSRafael** [movie-web/movie-web#680]
### What happened?

Recently, Brazilian Portuguese translation was added, but the flag that appears in the options menu is that of European Portuguese, which is a significantly different language.

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

Go to the language selector and check the flag

### Other relevant information

I have already implemented the solution; I just need permission to submit the pull request.

**Comment by JipFr** [comment]
Go ahead

**Comment by binaryoverload** [comment]
This is reliant on #618 I believe, as we don't handle country variants right now
