### ISSUE TITLE
[Bug]: Some other movie is playing instead of the poster of the movie clicked.

### ISSUE THREAD

**Issue by pushpenderrajput** [movie-web/movie-web#681]
### What happened?

When a movie was searched that is Mahabharat when we played it then any other old Hollywood movie is playing.
1. The Movie that was Clicked.
![Screenshot 2023-12-31 122009](https://github.com/movie-web/movie-web/assets/85430197/97b025f9-14b8-4d00-a696-84a0e7dba0b0)
2. The Movie that Played.
![Screenshot 2023-12-31 122111](https://github.com/movie-web/movie-web/assets/85430197/e8519182-119e-455a-b10c-3eff41a90662)

### Steps to reproduce?

1. Search Movie name Mahabharat.
2. Click on Movie named Mahabharat where  written 2013.
3. Play This Movie 
4. We can Observe a different Hollywood Movie is Played which is not that we Played.

**Comment by pushpenderrajput** [comment]
Issue was Faced on Chrome Browser.

**Comment by notblondenough** [comment]
let me check

**Comment by wouter173** [comment]
let me check as well

**Comment by JipFr** [comment]
There's not much we can do when a provider tells us that the movie they're returning is the right one. Sadly it looks like we don't have your movie on the platform.

**Comment by pushpenderrajput** [comment]
Then Poster should also be removed should show "No Results Found"

**Comment by qtchaos** [comment]
We can't really check if what the provider gives us is correct or not, so that wouldn't be possible

**Comment by pushpenderrajput** [comment]
Okay Let it be.
