### ISSUE TITLE
[Bug]: failed to load config from [movie-web-directory]/vite.config.mts

### ISSUE THREAD

**Issue by joshholly** [movie-web/movie-web#682]
### What happened?

Whenever I run pnpm run dev (after I ran pnpm install), I get this error:

> failed to load config from /Users/[redacted]/Sites/movie-web/vite.config.mts
>error during build:
>TypeError: Cannot redefine property: File
>    at Function.defineProperty (<anonymous>)
>     at Object.<anonymous> (/Users/[redacted]/Sites/movie-> web/node_modules/.pnpm/@babel+core@7.23.6/node_modules/@babel/core/lib/index.js:7:8)
>     at Module._compile (node:internal/modules/cjs/loader:1241:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
>     at Module.load (node:internal/modules/cjs/loader:1091:32)
 >    at Module._load (node:internal/modules/cjs/loader:938:12)
 >    at Module.require (node:internal/modules/cjs/loader:1115:19)
 >    at require (node:internal/modules/helpers:130:18)
 >    at Object.<anonymous> (/Users/[redacted]/Sites/movie-> > web/node_modules/.pnpm/@babel+core@7.23.6/node_modules/@babel/core/lib/config/helpers/config-api.js:16:14)
>     at Module._compile (node:internal/modules/cjs/loader:1241:14)
 > ELIFECYCLE  Command failed with exit code 1.

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

1. git clone the movie-web
2. cd into the directory
3. Run pnpm install
4. Run pnpm run dev

**Comment by eddie-englund** [comment]
What node version are you on?

According to docs you need node 20 at minimum

**Comment by mrjvs** [comment]
Can't reproduce, likely an issue in your environment

**Comment by Juneezee** [comment]
@joshholly See https://github.com/vitejs/vite/issues/14299. You need Node.js >=20.7.0

**Comment by Juneezee** [comment]
@mrjvs I can submit a PR to update `package.json` to enforce Node.js >=20.7.0 so that issues like this don't happen again for other users. Would you kindly assign this issue to me? Thanks.
