### ISSUE TITLE
[Feature]: embed Google Fonts

### ISSUE THREAD

**Issue by 0xb4lint** [movie-web/movie-web#699]
### What feature do you want to add?

Right now the `index.html` [contains](https://github.com/movie-web/movie-web/blob/dev/index.html#L121-L123) a standard Google Fonts snippet for loading the Open Sans font.

That results at least 3 network requests (1x`css`, 2x`woff2`) to 2 different Google servers (`fonts.googleapis.com` and `fonts.gstatic.com`).

This can be eliminated by using [`vite-plugin-webfont-dl`](https://github.com/feat-agency/vite-plugin-webfont-dl) with zero configuration. It detects the Google Fonts stylesheet link, downloads the css and woff2 files and add them to the bundle.

### Why do you want to have this feature?

That will make **movie-web** load quicker, provides better user experience and give more privacy.

**Comment by mrjvs** [comment]
Google is a great cdn, we don't need to selfhost the fonts
