### ISSUE TITLE
[Bug]: Does not open the movies on Hisense TV browser (Serie A6H)

### ISSUE THREAD

**Issue by Josemboa** [movie-web/movie-web#711]
### What happened?

When I open the link movie-web.app on my TV Hisense 43A6H I'm able to search for movies an the result appears on the screen. However, when I click in any movie from the list it does not progress and shows an empty screen.

### Steps to reproduce?

1. Open a browser on Hisense TV 43A6H
2. Open the link https://movie-web.app
3. Search for any movie and will appear a list of the movies
4. Click on any movie of the list

**Comment by mrjvs** [comment]
TV browser are not supported by movie-web
