### ISSUE TITLE
[Bug]: Superstream not working

### ISSUE THREAD

**Issue by jaiveertalwar** [movie-web/movie-web#716]
### What happened?

Recently superstream shows an error when scraping. Not sure why. I have used different devices, browsers, networks and a VPN. This is a custom deployment using the back end of movie-web but my own proxy. 

### Other relevant information

```superstream: failure
SyntaxError: JSON Parse error: Unrecognized token '<'
zoechip: failure
Error: Failed to find ZoeChip embed source for https://voe.sx/e/jhsiwq90vov2
gomovies: notfound
Couldn't find a stream: Season not found
flixhq: notfound
Couldn't find a stream: no search results match
remotestream: failure
TypeError: Load failed
```

**Comment by JorrinKievit** [comment]
Heya, It's a known issue, and is being worked on! Updates related to provider issues are posted in our Discord. So if you haven't joined, you can stay up to date there!
