### ISSUE TITLE
[Bug]: Some languages are not working

### ISSUE THREAD

**Issue by zisra** [movie-web/movie-web#717]
### What happened?

Some incompleted languages are showing the translation keys instead of an english fallback
<img width="1136" alt="Screenshot 2024-01-05 at 10 45 50 AM" src="https://github.com/movie-web/movie-web/assets/100528712/5e2c3a7d-60b3-4dcc-b3e1-d8cba3c89e29">

### Steps to reproduce?

1. Go to https://movie-web.app/settings
2. Select Bulgarian or Vietnamese

**Comment by binaryoverload** [comment]
I can replicate this issue - @zisra would you like to take on fixing it?

**Comment by zisra** [comment]
Sure @binaryoverload

**Comment by binaryoverload** [comment]
I've assigned you :)
