### ISSUE TITLE
[Bug]: Couldn't handle non-SSL connection to proxy

### ISSUE THREAD

**Issue by sweenu** [movie-web/movie-web#727]
### What happened?

I deploy the proxy in the same docker network as the frontend and backend. It is not exposed on the internet. I do not need the security of an SSL connection, yet when the frontend is trying to reach `http://proxy:3000` it gives me this error on the proxy side:
```
[nitro] [request error] [unhandled] SubtleCrypto not supported!
  at ./.output/server/node_modules/@tsndr/cloudflare-worker-jwt/index.js:2:11
  at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
  at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
  at async Object.handler (./.output/server/chunks/nitro/node-server.mjs:2241:19)
  at async Server.toNodeHandle (./.output/server/chunks/nitro/node-server.mjs:2430:7)
 ```
 It comes from cloudflare-worker-jwt that I don't need as i'm not deploying through Cloudflare.
 Could you make it so that the Cloudflare specific code is not executed when not using Cloudflare?

### What browsers are you seeing the problem on?

Firefox

**Comment by binaryoverload** [comment]
Thanks for the issue, this is a duplicate of #587 which we have a fix for in a new version coming soon :D

**Comment by sweenu** [comment]
Sorry for the duplicate. I searched issues with the label repo-proxy, should have checked also the rest.
