### ISSUE TITLE
[Feature]:  Support Other Movie Languages

### ISSUE THREAD

**Issue by tsuki-kami-studios** [movie-web/movie-web#728]
### What feature do you want to add?

A selection to get Movies in other languages (for example only in german)

### Why do you want to have this feature?

Couse i want to get german Movies

**Comment by binaryoverload** [comment]
Duplicate of #423

**Comment by tsuki-kami-studios** [comment]
Im not sure if its a duplicate, couse the other one wants to change it, but i just want to find it at first.
In my point of view i wouldnt count it as duplicate of the other one.

**Comment by binaryoverload** [comment]
> Im not sure if its a duplicate, couse the other one wants to change it, but i just want to find it at first. In my point of view i wouldnt count it as duplicate of the other one.

Finding media outside of changing audio track is a case of suggesting providers - if there are any specific providers then you're welcome to suggest those.
