### ISSUE TITLE
[Feature]: Show profile picture while editing

### ISSUE THREAD

**Issue by robertsspaceindustries** [movie-web/movie-web#729]
### What feature do you want to add?

When editing a device's profile picture, you can't see the result, there's no preview.
![image](https://github.com/movie-web/movie-web/assets/49074962/e3768d17-aaa3-4add-b3d1-eab6c451e8dc)

### Why do you want to have this feature?

So we know what we're doing when editing. 🙂

### Anything other details to share?

I can have a pr ready if assigned.

**Comment by binaryoverload** [comment]
Approved and assigned @robertsspaceindustries - thanks!
