### ISSUE TITLE
[Bug]: Failed to play the video

### ISSUE THREAD

**Issue by owocado** [movie-web/movie-web#731]
### What happened?

Movie was found and when clicked to play, it fails with error.

### What browsers are you seeing the problem on?

Google Chrome Stable 120.0.6099.130

### Steps to reproduce?

1. search for "sam bahadur"
2. open the entry shown
3. it tries to play the movie but fails

### Other relevant information

error:
```js
URL - /media/tmdb-movie-814215-sam-bahadur
API - true

showbox: failure
SyntaxError: Unexpected token 'e', "error code: 1106" is not valid JSON
zoechip: notfound
Couldn't find a stream: no search results match
gomovies: notfound
Couldn't find a stream: Media not found
flixhq: notfound
Couldn't find a stream: no search results match
smashystream: success
remotestream: waiting
smashystream-0: failure
TypeError: textFileRes.find is not a function
smashystream-1: failure
TypeError: Cannot read properties of undefined (reading 'match')
```

**Comment by binaryoverload** [comment]
This is not a bug - it's an issue with a provider that we're working on fixing.
