### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SirHaxALot4** [movie-web/movie-web#745]
### What happened?

Whenever i tried to search up a movie or anything, it just said failed to find media, please try again.

![Screenshot 2024-01-06 235417](https://github.com/movie-web/movie-web/assets/132801471/77b0daa7-33eb-4ca8-b583-7f324ea1202e)

### What browsers are you seeing the problem on?

Chrome

**Comment by zisra** [comment]
TMDB is most likely blocked in your country, please try https://1.1.1.1 to fix it
