### ISSUE TITLE
[Bug]: Publish Workflow fails due to wrong lockfile

### ISSUE THREAD

**Issue by akaJuliaan** [movie-web/movie-web#746]
### What happened?

The PR #722 which should publish a Docker Image for the frontend doesn't work, as the Deploying workflow [always fails](https://github.com/movie-web/movie-web/actions/runs/7434046497). It seems that there is something wrong with the [pnpm-lock.yaml](https://github.com/movie-web/movie-web/blob/dev/pnpm-lock.yaml).

**Comment by binaryoverload** [comment]
Thanks for the report - you're correct. The issue seems to be that the workflow uses Node 16 which is pretty outdated
