### ISSUE TITLE
[Feature]: Stream custom remote stream through URL or embed from UI

### ISSUE THREAD

**Issue by driftywinds** [movie-web/movie-web#748]
### What feature do you want to add?

Can there be a user friendly way of introducing a remote stream from URL or embed for streaming? 

### Why do you want to have this feature?

It would make things a lot easier for stream that the app cant find itself. Users could simply paste the embed or the url and the app could start streaming from the source

### Anything other details to share?

Many video hosting sources offer embeds or stream URLs which would be convenient to view through the app without the gunk that comes with websites like ads etc. 

A simple button or something that you can paste an embed or URL into, which then plays the content from that would be very useful.

**Comment by qtchaos** [comment]
The embeds themselves contain the ads (so no ads would be blocked), and iframing someone elses embed also defeats the whole purpose of movie-web.
