### ISSUE TITLE
[Bug]: Fetching any stream gives an error after watching a few streams in a day

### ISSUE THREAD

**Issue by JackGreenEarth** [movie-web/movie-web#750]
### What happened?

This happened both today and yesterday. I was watching the movie/TV series fine, then any stream I tried to watch, including ones previously watched, gave an error:

```
URL - /media/tmdb-tv-246-avatar-the-last-airbender/786/13569
API - true

showbox: success
zoechip: failure
Error: invalid season
vidsrc: failure
Error: failed to find episode element
gomovies: notfound
Couldn't find a stream: Media not found
flixhq: notfound
Couldn't find a stream: season not found
smashystream: pending
remotestream: waiting
showbox-0: failure
SyntaxError: Unexpected token 'I', "Internal S"... is not valid JSON
```

It wasn't video not found, it was an error. And it only happened after already watching a few streams without problems, and it was fine the next day, until it stopped working again. I am using Firefox on Manjaro GNOME with Ublock Origin and a few other extensions that shouldn't be blocking anything. The same thing also happened in Microsoft Edge though, and when I disabled Ublock Origin.

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Steps to reproduce?

1. Watch multiple streams in a day
2. ...
3. Profit!

### Other relevant information

I tried clearing my cache and local storage, and reopening the movie from the home screen, but neither worked.

**Comment by binaryoverload** [comment]
This isn't a bug - it's a problem with a provider of ours. We're trying to fix it but this time it's out of our control!

**Comment by JackGreenEarth** [comment]
Oh, well thanks for clearing that up then!
