### ISSUE TITLE
[Bug]: Failed to load API metadata

### ISSUE THREAD

**Issue by Colind8** [movie-web/movie-web#751]
### What happened?

Whenever I select any movie / show, it'll display this error:
![image](https://github.com/movie-web/movie-web/assets/23065578/768719c6-ba9c-4e1d-a47e-8a9792067dcc)

My internet connection is fine so I'm not sure what's happening.

### What browsers are you seeing the problem on?

Firefox

### Steps to reproduce?

1. Select any movie / show

**Comment by MomoMiles** [comment]
Can confirm. It looks like some link is causing an SSL error

**Comment by mrjvs** [comment]
This is caused by ISP blocking, probably through DNS.
Use a vpn or a different dns server to get it fixed.

**Comment by Colind8** [comment]
> This is caused by ISP blocking, probably through DNS. Use a vpn or a different dns server to get it fixed.
I don't think it's that. I tried a different DNS server but nothing changed.

I would like to add on that this message is printed to the console when I get this error:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://providers-api.cf9-08f.workers.dev/metadata. (Reason: CORS request did not succeed). Status code: (null).`

And that remote resource indeed causes an SSL error as MomoMiles stated:
"SSL_ERROR_RX_RECORD_TOO_LONG"

**Comment by mrjvs** [comment]
> I don't think it's that. I tried a different DNS server but nothing changed.
the ssl error is caused by ISP blocking or some other type of blocking. there is nothing wrong the SSL. plus we've concluded that when we rename the urls, everything works fine. Not to mention that everybody so far who has had this issue, has been able to fix it by switching to a VPN.

It's 100% because of blocking. We will do something about soon-ish, but we have other priorities right now.

**Comment by Colind8** [comment]
> It's 100% because of blocking. We will do something about soon-ish, but we have other priorities right now.

Oh. Well thank you.

**Comment by JorrinKievit** [comment]
We have added a fallback url in #1108
