### ISSUE TITLE
[Bug]: Nothing is displayed

### ISSUE THREAD

**Issue by Stefan456789** [movie-web/movie-web#752]
### What happened?

There is nothing on the screen.
I expect to see the movie-web.app home page.

### What browsers are you seeing the problem on?

Firefox

### Steps to reproduce?

1. Go to https://movie-web.app/

### Other relevant information

It works in a incognito tab, even after logging in.
It also doesn't work on my tablet.
It works after deleting cookies.

**Comment by zisra** [comment]
Try a force refresh: Command/control + Shift + R

**Comment by ari-party** [comment]
It works for me on Firefox (Dev Ed.)
Issues like these are usually because of the browser you're using

**Comment by JorrinKievit** [comment]
Can't reproduce. Feel free to reopen if it occurs consistently 😄
