### ISSUE TITLE
[Feature]: Cleanup runner code

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#756]
### What feature do you want to add?

Runner code in the provider package is bulky and janky. It needs cleanup.

### Why do you want to have this feature?

Have you read the code? its garbage!

**Comment by ZanderCeunen** [comment]
Can I help rewrite the code?

**Comment by mrjvs** [comment]
@ZanderCeunen Sure, in the providers im more specifically talking about everything going on in the /src/runners directory.
Just make it as clean as possible, the stuff that's currently in there is hard to read.

ill assign you.

**Comment by ZanderCeunen** [comment]
I finished the runner.ts script but how do I test it?

**Comment by mrjvs** [comment]
you can write a test.ts file in the tests folder. then call the methods you need to test in there.
They will be run when you do `npm run test`

**Comment by ZanderCeunen** [comment]
I tested a bit. Can you first check the code https://pastebin.com/y92KuVbg. Let me know what I have to change for making it easy to replace with the old runner.ts file.

**Comment by mrjvs** [comment]
just make a PR and request me as reviewer, im not gonna read a pastebin. If you need help with PR's you can look at [this page](https://docs.github.com/articles/creating-a-pull-request)

**Comment by ZanderCeunen** [comment]
I can not work further because I have questions about how legal the platform is. You can unassign me for now.
