### ISSUE TITLE
[Feature]: Skip intro and recap

### ISSUE THREAD

**Issue by AYA-123** [movie-web/movie-web#761]
### What feature do you want to add?

A skip recap / intro / credits button similar to netflix - for tv shows, in a single season like plex does, you could analyse for segments that match between the episodes. This could primarily be done by analyzing the audio of the file, which would find a common theme song, for instance. Matching is done per season, as many shows have a different intro segment for each season.

### Why do you want to have this feature?

Quality of life upgrade.

**Comment by mrjvs** [comment]
Duplicate of #347
