### ISSUE TITLE
[Feature]: add subtitle list on the right

### ISSUE THREAD

**Issue by fengyunzaidushi** [movie-web/movie-web#766]
### What feature do you want to add?

add subtitle list on the right.for instance,in the website like youtube we could install a extension,it can easily tshow all of the subtitles,so we could easily jump to the right node we care about.
![image](https://github.com/movie-web/movie-web/assets/53250064/a3c14037-cd96-4de3-afbe-12919c64c9cf)

### Why do you want to have this feature?

it could save much time to watch a video

**Comment by zisra** [comment]
You can download the subtitle and view it

**Comment by zorjo** [comment]
Is there any way to achieve automatic downloading of subtitles from multiple subtitle providers and then loading it into the video without manually downloading?

**Comment by JorrinKievit** [comment]
To answer your question @zorjo , no there is not. This is because we only scrape the sources one by one.

For the original issue, this is out of scope for the project. The preview thumbnails should give enough content for seeking to a certain point of the content you'd like to watch.
