### ISSUE TITLE
[Bug]: VidSrc causes a crash in the loading screen during scraping

### ISSUE THREAD

**Issue by JorrinKievit** [movie-web/movie-web#770]
### What happened?

Stops the scraping process because VidSrc fails to scrape
![image](https://github.com/movie-web/movie-web/assets/43169049/7a46721f-a558-46dd-b5fb-a2a9eb9926c8)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Steps to reproduce?

1. Visit https://movie-web.app/media/tmdb-tv-1797-honey-i-shrunk-the-kids-the-tv-show/5086/108766
2. Wait for VidSrc to start scraping

### Other relevant information

Relevant code. Throws because it cant find a matching scraperId
https://github.com/movie-web/movie-web/blob/extension/src/hooks/useProviderScrape.tsx#L95
![image](https://github.com/movie-web/movie-web/assets/43169049/2cfaf844-34b5-4d53-bd6a-8d177e949d7d)

I would assume it is an issue in the providers repo, but maybe not finding an id here shouldn't stop the entire scraping process and just skip the source?

**Comment by mrjvs** [comment]
most likely due to provider package giving back disabled embeds

**Comment by JorrinKievit** [comment]
Oh true, forgot that fix wasnt published yet

**Comment by JorrinKievit** [comment]
Just tested and this was indeed fixed with the disabled embeds filter, so this can be closed when providers package is updated @mrjvs
