### ISSUE TITLE
[Feature]: Reduce the amount of time it takes to load homepage

### ISSUE THREAD

**Issue by zisra** [movie-web/movie-web#771]
### What feature do you want to add?

Loading the profile takes about one second every time (which is really long) because all the requests run subsequently. This can be fixed by using Promise.all and all the requests will run at once

<img width="590" alt="Screenshot 2024-01-10 at 2 31 05 PM" src="https://github.com/movie-web/movie-web/assets/100528712/80b8c6e7-a42c-4f4c-ae0f-e903e55a018c">

### Why do you want to have this feature?

I'm a busy man 😎

### Anything other details to share?

Alternatives I would like to share:
- Merging all the requests in the backend into one route would be the most optimal solution
- Saving settings and information in localStorage, while only using the backend to update information
- Gradually adding the loaded information to the page while leaving a skeleton/placeholder for information that has not been loaded yet

**Comment by mrjvs** [comment]
running the the bookmarks, settings and progress data in parralel will speed it up by 300ms. other things shouldnt be made faster cuz itll make the code jank
