### ISSUE TITLE
[Feature]: Improved Search of /available command 

### ISSUE THREAD

**Issue by thehairy** [movie-web/movie-web#772]
### What feature do you want to add?

Please change the search of the /available command, so you can either provide tmdb id's directly, or show the search results a bit better, so one can differentiate between same-named movies.

### Why do you want to have this feature?

Currently its impossible to search for movies that have multiple search results that are named the same.

**Comment by castdrian** [comment]
adding the release year resolves that easily, will push to existing pr

**Comment by castdrian** [comment]
resolved via https://github.com/movie-web/discord-bot/pull/23/commits/cfbed036c9a78d07e682ddae211ff0bce60112de
https://adriancastro.dev/xshrbjowrvtk.png

**Comment by thehairy** [comment]
completed in https://github.com/movie-web/discord-bot/pull/23
