### ISSUE TITLE
[Feature]: Peer assisted video delivery

### ISSUE THREAD

**Issue by snowinszu** [movie-web/movie-web#779]
### What feature do you want to add?

The peer network builds a naturally scalable shield against service outages during viewership peaks, as well as reduce the load on the centralized infrastructure. 

### Why do you want to have this feature?

SwarmCloud is completely free of charge for open-source projects and non-profit organizations. movie-web.app is already whitelisted.

### Anything other details to share?

This is the commit that already pass test:
https://github.com/swarm-cloud/movie-web/commit/bb525d9d0b1470ba28c5fbce3c86ab80d95fbacc

**Comment by JorrinKievit** [comment]
Although it looks like a really cool concept, It is unfortunately out of scope since we only have community instances now
