### ISSUE TITLE
[Feature]: Improve Discord bot's 'cantdownload' tag

### ISSUE THREAD

**Issue by ari-party** [movie-web/movie-web#780]
### What feature do you want to add?

Better explanation for HLS playlists and downloading them

### Why do you want to have this feature?

So that there is an actual guide on converting/downloading ♥

### Anything other details to share?

PR ready, [commit](https://github.com/ari-party/movie-web-discord-bot/commit/ce10d067f50889a07ce37e07887c131239d858fe)

**Comment by castdrian** [comment]
besides the point, but please don't push pr commits to the active branch, use feature branches

**Comment by binaryoverload** [comment]
I'm happy to accept a PR for tags on the Discord bot, please go ahead
