### ISSUE TITLE
[Bug]: Performance regressions since v4.0 make unusable on Kindle Fire TV

### ISSUE THREAD

**Issue by Darthagnon** [movie-web/movie-web#783]
### What happened?

movie-web used to work great on low-power computers like the Kindle Fire TV, but ever since roughly around the 4.0 update, the new animations and transparencies combined with auto play/resume of movies have caused serious performance issues. Videos lag more, the website crashes the Amazon Silk browser more. 

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

Open movie-web.app on a low RAM low power computer (e.g. 3GB RAM, older browser) or my test case, a Kindle Fire TV stick. If you were previously watching a movie, the website will instantly attempt to load and play it, which will cause freezes of 30s+. If you manage to get to the homepage without the browser crashing, navigation will be slow and laggy. I can't say for sure it's the fancy new animations and transparencies, but I would wager it is

**Comment by mrjvs** [comment]
Video lag is unrelated. You can get better streams by using this guide: https://docs.movie-web.app/extra/streaming

**Comment by Darthagnon** [comment]
I thought it might be player JS with transparency occupying cycles instead of leaving them for video playback.

**Comment by ZlashBoi** [comment]
Actually, me too. I'm getting video streaming at lower quality and a lot of buffering. I'm on a low-end Chromebook and before, it used to work fabulously.

**Comment by qtchaos** [comment]
> I also noticed that the v4.x release zips are 10x the size of the v3.x release zips - has something heavy been added?

The size difference is due to including a 10.7MB source map, If you'd exclude the source map then the v4 release zip would be 2.27MB. This won't affect your performance in any way, its just useful for debugging production code.

**Comment by binaryoverload** [comment]
Closing as stale
