### ISSUE TITLE
[Feature]: (/providers) add debug option to runAll() & target type to RunOutPut

### ISSUE THREAD

**Issue by castdrian** [movie-web/movie-web#784]
### What feature do you want to add?

- a debug boolean as additional field in the options for runAll() which prevents it from stopping on success (until all providers have been checked)
- providing the source's target flag in the runoutput object

### Why do you want to have this feature?

for improved (and future) usage with mw-bot:
- it'd be useful if the bot checks all sources rather than stopping on success
- since the project state has maneuvered away from browser only, I am planning to add visible flags to the response embed which indicate if a source is available in plain browser mode, extension mode or native application 

### Anything other details to share?

I'll happily do this myself since I'm the one who needs it

**Comment by mrjvs** [comment]
You can already do this without building it into the lib. You can get a list of sources. You can run a specific source. You can then run the embeds returned by the specific source.

**Comment by castdrian** [comment]
I guess, it'd been quite nice to have still but oh well, plus perhaps a custom proxy target flag for shoebox since that one is a special case

**Comment by mrjvs** [comment]
In the extension branch there is a CF_BLOCKED flag. It won't be much longer till that gets into a release.

The flag does nothing on its own, its just for cases like the bot.
