### ISSUE TITLE
[Bug]: self hosted proxy no providers

### ISSUE THREAD

**Issue by Dialgatrainer02** [movie-web/movie-web#787]
### What happened?

when trying to watch anything onn a self host frontend i get 

URL - /media/tmdb-movie-9659-mad-max
API - false

showbox: failure
SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data
zoechip: notfound
Couldn't find a stream: no search results match
vidsrc: notfound
Couldn't find a stream: No streams found
gomovies: notfound
Couldn't find a stream: Media not found
flixhq: notfound
Couldn't find a stream: no search results match
smashystream: notfound
Couldn't find a stream: No streams found
remotestream: failure
TypeError: NetworkError when attempting to fetch resource.

### What browsers are you seeing the problem on?

Firefox

### Steps to reproduce?

docker host the proxy and use nginx docker web server for client

try to access the front end and watch something 
 no providers can be accessed 

### Other relevant information

im using docker to host the proxy and using nginx docker image to host the client 

i have used the api read token and have double checked its correct

**Comment by Dialgatrainer02** [comment]
my docker compose yml 

  nginx:
    image: nginx:latest
    hostname: movie-web
    ports:
      - "8888:80"
    volumes:
      - type: bind
        source: ./movie-web
        target: /usr/share/nginx/html
    restart: unless-stopped
    networks:
      - movie-web
  proxy:
    hostname: movie-proxy
    image: ghcr.io/movie-web/simple-proxy:latest
    ports:
      - 3000:3000
    networks:
      - movie-web

**Comment by progeroffline** [comment]
I have the same problem

**Comment by Dialgatrainer02** [comment]
foud the issue just needed to install the extension
