### ISSUE TITLE
[Feature]: Setup routing and navigation

### ISSUE THREAD

**Issue by JorrinKievit** [movie-web/movie-web#788]
Basic routing and navigation

This includes the following

- Bottom navigation bar 
- Pages for Home, Downloads, Search, Settings, Account
- An "Under construction" page for pages we won't make for the first basic version (Downloads)

If you need more information, don't hesitate to ask in the designated Discord channel!

Design: https://www.figma.com/file/Gp84XkTUeLJoeJ0i7kNWAz/v4?type=design&node-id=1187-8&mode=design&t=wvvCQuC640jeT7v0-0

**Comment by callmearta** [comment]
What should be in these pages for now? Just a title?

**Comment by JorrinKievit** [comment]
Ye thats fine
