### ISSUE TITLE
[Feature]: Search page

### ISSUE THREAD

**Issue by JorrinKievit** [movie-web/movie-web#789]
Implementation of the Search page.

- ~~User should be able to search using an input.~~
- Should use the TMDB API from /packages to get results.
- The cards do not need any functionality right now, a simple list of cards according to the design is sufficient.
- Pagination won't be needed, lets just return the max of 20 items.

We'd like the TMDB API to be in a separate package in the /packages folder. In here we could create utility functions that the mobile app (and in the future other apps) can use. For example a search() function which accepts the needed parameters, and returns a certain return type.

If you need more information, don't hesitate to ask in the designated Discord channel!

Design: https://www.figma.com/file/Gp84XkTUeLJoeJ0i7kNWAz/v4?type=design&node-id=1187-8&mode=design&t=wvvCQuC640jeT7v0-0

**Comment by lakshay-saini-au8** [comment]
I would like to work on this

**Comment by castdrian** [comment]
has already been done in the form of this pr
https://github.com/movie-web/native-app/pull/4

**Comment by JorrinKievit** [comment]
Ye which should not have happened thats on me😅. Someone should already be assigned to this 😇
