### ISSUE TITLE
[Feature]: Use NativeWind

### ISSUE THREAD

**Issue by JorrinKievit** [movie-web/movie-web#793]
We'd like to use NativeWind in the mobile app. This allows us to use tailwind and have a universal style system.
NativeWind V4 is in the works but not officially released yet, so let's just work with V2. 

- Convert the current StyleSheet classes to NativeWind

https://www.nativewind.dev/quick-starts/expo

**Comment by ThatGuySam** [comment]
If you’re going React Native can recommend the Obytes starter template: 
https://github.com/obytes/react-native-template-obytes

Personal, kind of mad that I didn’t find it a year ago because half of the deps it uses I had to do weeks of research and trial and error to find myself.

**Comment by castdrian** [comment]
that does kinda look fire, would be a bit ass to integrate it now tho, someone's gonna ha e fun if we decide to

**Comment by ThatGuySam** [comment]
I’ve been just using it to get ideas for solving various issues like data handling and config on my existing projects. 

Even just looking through what packages they use and each does helps a lot.

**Comment by JorrinKievit** [comment]
Yes I think its a good reference point to have! But indeed what @castdrian said it might be a bit of a pain to migrate to from the state we are currently in
