### ISSUE TITLE
Blocked site

### ISSUE THREAD

**Issue by Ds1399** [movie-web/movie-web#794]
I am just a guy who likes unblocking things when I’m bored at school, and I was wondering if there is a way to have this on github pages without locally hosting or running a different application. If you don’t want to that is fine.

**Comment by TheScreechingBagel** [comment]
yes, you can host for free on any static site host, see docs:
https://docs.movie-web.app/self-hosting/hosting-intro
but chances are if your school blocks movie-web, the providers are blocked as well. worth a shot?

**Comment by Ds1399** [comment]
Thanks I’ll try
