### ISSUE TITLE
[Bug]: Visual artifact on home screen

### ISSUE THREAD

**Issue by AYA-123** [movie-web/movie-web#796]
### What happened?

![Uploading image.png…]()
![Uploading image.png…]()

Expected a clean gradient - not a black, rectangular gap

### What browsers are you seeing the problem on?

Microsoft Edge

### Steps to reproduce?

Appears by default on home page

### Other relevant information

Windows 11

**Comment by JorrinKievit** [comment]
Black bar on top of the page is intended by design
