### ISSUE TITLE
[Bug]: [object Object] is not valid JSON on a movie

### ISSUE THREAD

**Issue by jordanbmrd** [movie-web/movie-web#799]
### What happened?

The next error happen on movie « Squeezie : Merci Internet »

```URL - /media/tmdb-movie-1219077-squeezie-merci-internet
API - true

showbox: failure
SyntaxError: "[object Object]" is not valid JSON
zoechip: notfound
Couldn't find a stream: no search results match
vidsrc: notfound
Couldn't find a stream: No streams found
gomovies: notfound
Couldn't find a stream: Media not found
flixhq: notfound
Couldn't find a stream: no search results match
smashystream: success
remotestream: notfound
Couldn't find a stream: No watchable item found
smashystream-0: failure
Error: [SmashyStream (D)] failed to find text file url or token
```

### Steps to reproduce?

1. Search for « Merci Internet »
2. Choose « Squeezie : Merci Internet »

**Comment by castdrian** [comment]
not a bug, no stream found

**Comment by jordanbmrd** [comment]
smashystream should not return `success` first if media is not found and app should display a « Movie not found » message

**Comment by mrjvs** [comment]
The app shows the text in the image below, I think this is sufficient as a "movie not found" message.
As for the success, it was smashystream successfully being scraped (smashystream does have a page for this movie: https://smashystream.xyz/movie/1219077) but unfortunately the videos on the page itself are not successfull. The final message on screen is what counts though, the debug information is just debug information.

![https://i.imgur.com/CHoOHGt.png](https://i.imgur.com/CHoOHGt.png)
