### ISSUE TITLE
[Feature]: Add https://redecanais.zip provider

### ISSUE THREAD

**Issue by Guatias** [movie-web/movie-web#805]
### What feature do you want to add?

This provider contains a huge amount of brazilian dubbed content, the biggest that I know

### Why do you want to have this feature?

Until now, I haven't found any project like this that provide brazilian content

**Comment by zisra** [comment]
We don't do dubbed content, or wouldn't without #775

**Comment by JorrinKievit** [comment]
Seems to be down, or region locked.
