### ISSUE TITLE
[Feature]: Keyboard shortcuts

### ISSUE THREAD

**Issue by RihanArfan** [movie-web/movie-web#81]
### What feature do you want to add?

Support using arrow keys and enter on the search UI to select a result

### Why do you want to have this feature?

This makes using movie-web a little more convinient for power users

**Comment by mrjvs** [comment]
Will add to the next major version todo list

**Comment by mrjvs** [comment]
implemented in version 3

**Comment by mrjvs** [comment]
resolved with latest release
