### ISSUE TITLE
[Bug]: Extension fetching limitations

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#820]
### What happened?

There are a few limitations that prevent extension from working fully:
- Instance objects like FormData and UrlSearchParams can't be sent over messaging framework. It will fail to make the request with a null response.
- User-Agent header cannot be set with the request

These two are making showbox/febbox currently broken for extension scraping.

### What browsers are you seeing the problem on?

Chrome

### Other relevant information

FormData and UrlSearchParams can be represented in plain objects, just to add a bodyType. parameter or smth to parse it back after transfering to extension.

For the user agent, maybe XMLHttpRequest will work. Or maybe using declarativeNetRequest we can set the user agent before we make our own API request.

**Comment by mrjvs** [comment]
Also gonna ping @JorrinKievit since you've worked on the extension the most. (Not to assign you or anything, but just for visibility)

**Comment by JorrinKievit** [comment]
I'll work on it
