### ISSUE TITLE
[Feature]: work with RAVE ( Watch PARTy)

### ISSUE THREAD

**Issue by Hakimbhb** [movie-web/movie-web#829]
### What feature do you want to add?

there is an app called rave that accept website  but unfortually  it doesn t recognize video from movie-web.app website i wish that you could make sit happend or have another solution to make watch party 

### Why do you want to have this feature?

by just alowing video directly in the website recognized by the app( it s on all OS)

### Anything other details to share?

this is the official link of the app : rave.io 
thank you guys!

**Comment by TheScreechingBagel** [comment]
if it accepts media from a link, you can simply click on download in movie-web, and then copy the link into rave

**Comment by mrjvs** [comment]
Making it work is Rave's responsibility, not ours to solve.

**Comment by Hakimbhb** [comment]
thats what i m doing rn but with that we loss the principe of technologie haha ! and i can t use caption!.. i m sure that it s not a heavy mission ! i wish that could be fixed!
