### ISSUE TITLE
[Feature]: PWA

### ISSUE THREAD

**Issue by RihanArfan** [movie-web/movie-web#83]
### What feature do you want to add?

Add a service worker and manifest to turn movie-web into a PWA

### Why do you want to have this feature?

This allows installing as a "native" looking application on mobile and desktop

**Comment by mrjvs** [comment]
This requires the following code changes:
- [ ] add ui for being offline, a top status bar would suffice
- [ ] all network requests would need to handle being offline
- [ ] add a manifest
- [ ] add a service worker (with properly defined caching)

**Comment by mrjvs** [comment]
I will add this to the scope of the next major version

**Comment by mrjvs** [comment]
completed in #171
