### ISSUE TITLE
[Bug]: Cannot load movies through the tor browser

### ISSUE THREAD

**Issue by OkayChocolate** [movie-web/movie-web#832]
### What happened?

I was expecting the movie to load, but on the desktop tor browser you get a "failed to verify your humanity" message as an error. And on the mobile tor browser (android) you get a "could not load API metadata, please check your internet connection" error.

### What browsers are you seeing the problem on?

the tor browser

### Steps to reproduce?

1. Open movie-web.app on either the desktop tor browser or with the mobile tor browser
2. try and load any movie 

### Other relevant information

I tried debugging this somewhat by myself, and I believe the "failed to verify your humanity" errors are not because of a failed CAPTCHA test or something similar.

When loading the movie everything seems to be going as it should until a request to api.cf6-bc5.workers.dev fails, and at the same time the "failed to verify humanity your humanity" error pops up. The firefox debugger seems to classify this error as a "CORS missing allow origin" error. And it seems like api.cf6-bc5.workers.dev doesn't allow requests from movie-web.app looking at the cross origin headers (see attached pictures)

![Screenshot from 2024-01-26 17-04-10](https://github.com/movie-web/movie-web/assets/157820716/1e8c3193-c066-47b7-9a4f-8f11a1b246b3)
![Screenshot from 2024-01-26 16-21-07](https://github.com/movie-web/movie-web/assets/157820716/e6851487-9738-408b-bc23-b3296f1cd1f1)

what's interesting and very weird is re-sending these requests manually manually using fetch() or resending them using the network tab seems to go through. The responses have valid cross origin headers. (see attached picture)
![Screenshot from 2024-01-26 16-27-29](https://github.com/movie-web/movie-web/assets/157820716/99eb2afe-7586-4af3-be1f-638335fba046)

while investigating I loaded a different movie and that time it  failed with the error "CORS failed" and without a response. Though this might just be due to the browser's cache.
![Screenshot from 2024-01-26 16-37-51](https://github.com/movie-web/movie-web/assets/157820716/a2db5042-57fc-4cce-b084-9fc722d8373f)

this all is of course from an outsiders perspective and the error might just be because of a fail to verify my humanity.

**And now over to trying to watch a movie through the mobile tor browser.** As said earlier loading the site on mobile doesn't result in a "failed to verify your humanity" error, but rather a "could not load API metadata, please check your internet connection." error. I've read issue #751 where the same error pops up, here the hypothesis seems to be that it's because of blocking. Here I think that would be highly unlikely because tor VPN like behavior. 

when loading the page through mobile the error occurs when trying to GET /metadata . The error is a "CORS missing allow origin" error. The cross origin headers don't seem to allow requests from movie-web.app which is probably why the error happens. (See attached picture) 
![Screenshot from 2024-01-26 17-18-46](https://github.com/movie-web/movie-web/assets/157820716/f7b54e2e-6602-49ed-9f67-6da6ecc31c8f)

when trying to resend that request it doesn't seem to work, that time you get a NS_ERROR_DOM_CORP_FAILED error. (see attached picture)
![Screenshot from 2024-01-26 17-19-16](https://github.com/movie-web/movie-web/assets/157820716/d545c2e4-8815-4b92-81a1-cc17e3387ec4)
this error might be caused by something with the usb debugging but I doubt it.

**Now back to the desktop browser.** While writing the mobile part I was curious if the /metatdata GET request was successful on PC. And it is, it has the correct cross origin headers. (see attached picture)
![Screenshot from 2024-01-26 17-27-48](https://github.com/movie-web/movie-web/assets/157820716/d8ee04ce-f542-44cd-bd79-ec42bf9a9a10)

sorry for the long and maybe badly written bug report, I'm just an amateur so I might have missed some important stuff.

**Comment by lonelil** [comment]
The requests with CORS errors have the cf-mitigated header, which means your request got blocked by cloudflare.

**Comment by zisra** [comment]
Try using the extension instead. I'm sure Firefox extensions work on TOR as well, correct me if I'm wrong.

**Comment by OkayChocolate** [comment]
@lonelil if there is some blocking rules the owners could change to make tor requests go through, those changes should be implemented. I feel like there should be something that could be done to not block requests coming through tor, but I don't know.

**Comment by OkayChocolate** [comment]
@zisra using the add-on gets you further into loading up a movie but not all the way, it seems to load the movie but a playback error happens. (see attached pictures)
![Screenshot from 2024-01-26 20-29-02](https://github.com/movie-web/movie-web/assets/157820716/ec45ca45-371a-411b-ad5e-7f307b15e7c1)
![Screenshot from 2024-01-26 20-29-05](https://github.com/movie-web/movie-web/assets/157820716/b75fa239-d85c-466d-a8d3-06ca777537bf)
anyway, the add-on **shouldn't be required** to watch the movies. And on the latest mobile version of the tor browser you cannot install the movie-web extension. The movie web extension does support mobile but not the version of firefox that mobile tor uses (which is firefox 115).

**Comment by zisra** [comment]
You shouldn't be watching movies on TOR. Most websites break in TOR, it's not recommended. It's also not recommended that you enabled JavaScript in TOR, so you are contradicting it's purpose. (movie-web uses Google services, which aren't to be used with TOR either)

If you want us to help you please use a regular browser. If you are concerned about your anonymity, use a VPN (ProtonVPN is a good one that's free)

Unfortunately the error you're getting seems like a normal error that we cannot fix because the movie is simply not in any of them websites we scrape.

**Comment by binaryoverload** [comment]
Isra summed it up pretty nicely - use a normal browser with a VPN and it should work. Either using the Chrome/Firefox extension or using a custom proxy.

**Comment by DolanD2** [comment]
I have the same problem, I'm using Edge browser, i left a tab with a movie open for a few hours and then this happened. I tried using a VPN and it didn't help 🤷‍♂️
Also, I use the extension.

**Comment by OkayChocolate** [comment]
"Unfortunately the error you're getting seems like a normal error that we cannot fix because the movie is simply not in any of them websites we scrape." I find this unlikely I tried multiple movies, all of them pretty well known none of them loaded. So there's probably still some error that happens only when using tor. 

I understand that supporting tor isn't a priority for you (even though I think it should), so I'll probably leave this conversation here. Anyway if questions arise about these errors, feel free to ask.

**Comment by Mennaruuk** [comment]
I'm currently using movie-web without Tor (I'm using Firefox on macOS), and it's still giving me this error. I disabled Enhanced Tracking Protection, uBlock Origin, and the movie-web addon, but the error persisted.

![Screenshot 2024-01-27 at 16-28-43 Navalny(1)](https://github.com/movie-web/movie-web/assets/52135169/c3040c16-18d9-4bad-af11-0307a3b8088d)

Browser console log says: "Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js"

![Screenshot 2024-01-27 at 4 29 59 PM](https://github.com/movie-web/movie-web/assets/52135169/f1415e4e-521c-4caf-a473-d6a2ded739ed)

When I click the link to the right that says [tmdb-movie-926676-navalny:171:171](https://movie-web.app/media/tmdb-movie-926676-navalny), at the bottom it says: "You need to enable JavaScript to run this app."

![Screenshot 2024-01-27 at 4 30 28 PM](https://github.com/movie-web/movie-web/assets/52135169/c06ea380-8685-4610-8fa4-e9432c1e5498)

Top of the Inspector log also says: "You need to enable JavaScript to run this app."

![Screenshot 2024-01-27 at 4 32 31 PM](https://github.com/movie-web/movie-web/assets/52135169/4eb1cc8f-d139-4062-ad9b-cf8519af81cb)

**Comment by binaryoverload** [comment]
> I'm currently using movie-web without Tor (I'm using Firefox on macOS), and it's still giving me this error. I disabled Enhanced Tracking Protection, uBlock Origin, and the movie-web addon, but the error persisted.
> 
> ![Screenshot 2024-01-27 at 16-28-43 Navalny(1)](https://private-user-images.githubusercontent.com/52135169/300219353-c3040c16-18d9-4bad-af11-0307a3b8088d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzOTI3NzQsIm5iZiI6MTcwNjM5MjQ3NCwicGF0aCI6Ii81MjEzNTE2OS8zMDAyMTkzNTMtYzMwNDBjMTYtMThkOS00YmFkLWFmMTEtMDMwN2EzYjgwODhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDIxNTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ZWNiY2IxMzRmNTNiZjE3Y2U5NTNkMzg3NWZiMDE1NGM5NzBhMmQ2N2NjMDFiZDM0ODVkYzRhNTkxNzUwMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D0oCPnZLBAOWBT635czhP7Acx6rdbBfeE3ubLojep-g)
> 
> Browser console log says: "Loading failed for the <script> with source “https://static.cloudflareinsights.com/beacon.min.js"
> 
> ![Screenshot 2024-01-27 at 4 29 59 PM](https://private-user-images.githubusercontent.com/52135169/300219417-f1415e4e-521c-4caf-a473-d6a2ded739ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzOTI3NzQsIm5iZiI6MTcwNjM5MjQ3NCwicGF0aCI6Ii81MjEzNTE2OS8zMDAyMTk0MTctZjE0MTVlNGUtNTIxYy00Y2FmLWE0NzMtZDZhMmRlZDczOWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDIxNTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MDEzNTEzNGMzMTg3NjQ3ZTU0ZjdhZmZjMGViZTg3YTQ2YjViMzU5YjdjOGM5ZTAxNmEwOTFkYjA5MTdhMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E-SSedaZDvWXY4w3Z6-RzVTYh1XZld0YEEN_gcZmCuk)
> 
> When I click the link to the right that says [tmdb-movie-926676-navalny:171:171](https://movie-web.app/media/tmdb-movie-926676-navalny), at the bottom it says: "You need to enable JavaScript to run this app."
> 
> ![Screenshot 2024-01-27 at 4 30 28 PM](https://private-user-images.githubusercontent.com/52135169/300219572-c06ea380-8685-4610-8fa4-e9432c1e5498.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzOTI3NzQsIm5iZiI6MTcwNjM5MjQ3NCwicGF0aCI6Ii81MjEzNTE2OS8zMDAyMTk1NzItYzA2ZWEzODAtODY4NS00NjEwLThmYTQtZTk0MzJjMWU1NDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDIxNTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMzNlYjE0Njc0YzNjNjYzNGY4OTEzYjAyOGU4MGRmYThkZjIzZTNkYzU4MjJlMjkzNTE5MmNiMTdkN2JiZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0gN4xZPln66Fv_wCFjbLQwzXwLhV8X6EpRBlaxKMOEg)
> 
> Top of the Inspector log also says: "You need to enable JavaScript to run this app."
> 
> ![Screenshot 2024-01-27 at 4 32 31 PM](https://private-user-images.githubusercontent.com/52135169/300219491-4eb1cc8f-d139-4062-ad9b-cf8519af81cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzOTI3NzQsIm5iZiI6MTcwNjM5MjQ3NCwicGF0aCI6Ii81MjEzNTE2OS8zMDAyMTk0OTEtNGViMWNjOGYtZDEzOS00MDYyLWFkOWItY2Y4NTE5YWY4MWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDIxNTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMzUxZGFkY2E4ZWNjNjc0YmYyODRkNjYzZDQwZTk3Y2Y0MmQ0OTA1MzI1MDJjMWYxNDNiN2E2ZjE2MjE4OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mINES3cxJP9hTG7LJV8qJ5o8kQucmOsGMBc6xlNeuMQ)

This is not related to the issue, I'm going to lock this issue as the issue has been addressed
