### ISSUE TITLE
[Bug]: hls: no EXTM3U delimiter

### ISSUE THREAD

**Issue by BholeyKaBhakt** [movie-web/movie-web#843]
### What happened?

Can't stream the movie as it throws error `hls: no EXTM3U delimiter` for  lookmovie & showbox today.
It's either the v4.3.3 or extension v1.0.2

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

1. Setup extension
2. Start an episode or sth
3. See the error

**Comment by zisra** [comment]
I can still reproduce this error, but it's only broken half of times

**Comment by JorrinKievit** [comment]
Is this still happening? Can't reproduce

**Comment by binaryoverload** [comment]
Closing as stale
