### ISSUE TITLE
[Bug]:  Problem with Extension: Checking for Videos

### ISSUE THREAD

**Issue by Hentilador** [movie-web/movie-web#844]
### What happened?

Whenever I try to watch a movie after installing the extension I get the:

LookMovie
Checking for Videos...

and it goes on indefinitely.

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Other relevant information

Brave Browser

**Comment by matthewhm** [comment]
same here also on Brave

**Comment by JorrinKievit** [comment]
Same here also on brave, reinstalling _should_ work as a temporary fix

**Comment by JorrinKievit** [comment]
This is a bug in Brave. It will hopefullly be resolved in the update that will be released on February 20th. Related issue: https://github.com/brave/brave-browser/issues/30854

**Comment by JorrinKievit** [comment]
If you'd like to stay on Brave, you can disable and enable the extension and it should work. You can do this in the extension settings page. Note that you have to do this each time you launch the browser.

**Comment by Avichal1234** [comment]
this is also happening on firefox. Did you manage to find a solution?

**Comment by JorrinKievit** [comment]
We are aware of the issue, no fix yet

**Comment by mrjvs** [comment]
This is fixed in latest extension update. Should be in the chrome webstore in a few days.
