### ISSUE TITLE
[Bug]: Error: extension error: An unexpected error occurred

### ISSUE THREAD

**Issue by Mennaruuk** [movie-web/movie-web#845]
### What happened?

When using movie-web with the companion addon (v1.0.2), I get the error "extension error: An unexpected error occurred" when attempting to stream any video.

![Screenshot 2024-01-28 at 00-17-50 The Amazing Race Israel - S1 E1(1)](https://github.com/movie-web/movie-web/assets/52135169/9d222bb7-772c-4324-b34a-2e2e9b2af2a1)

### What browsers are you seeing the problem on?

Firefox

### Other relevant information

Error log:
```
URL - /media/tmdb-movie-841954-and-there-was-israel
API - true

lookmovie: failure
Error: extension error: An unexpected error occurred
vidsrcto: failure
Error: extension error: An unexpected error occurred
showbox: failure
Error: extension error: An unexpected error occurred
zoechip: failure
Error: extension error: An unexpected error occurred
vidsrc: failure
Error: extension error: An unexpected error occurred
gomovies: failure
Error: extension error: An unexpected error occurred
flixhq: failure
Error: extension error: An unexpected error occurred
smashystream: failure
Error: extension error: An unexpected error occurred
remotestream: failure
Error: extension error: An unexpected error occurred
```

**Comment by Agshin2004** [comment]
the same happens to me

**Comment by JorrinKievit** [comment]
Will close this since we have an approved issue for this :D #846
