### ISSUE TITLE
[Feature]: Jellyfin plugin

### ISSUE THREAD

**Issue by allancoding** [movie-web/movie-web#853]
### What feature do you want to add?

A jellyfin plugin that you have a search tab that will do the same thing as movie-web but you wont have to leave jellyfin. It would stream the file without downloading it like other alternatives.

### Why do you want to have this feature?

Not very pressing but I'd really like the option as others I asum would. Also I would like to know some thoughts on it to see if it is possible.

### Anything other details to share?

I would like to help if this looks like a achievable feature.

**Comment by castdrian** [comment]
not related to movie mw, you can use the providers package and make with it whatever you desire

**Comment by zisra** [comment]
Not possible because plugins are written in C#, while movie-web is written in JavaScript

**Comment by allancoding** [comment]
All right. What about a livetv server or something like that?
