### ISSUE TITLE
[Bug]: Keeps on saying failed to find media anytime I search up a movie or tv show

### ISSUE THREAD

**Issue by Dyelingahkn** [movie-web/movie-web#854]
### What happened?

All I did was search up my favourite **tv show** and it said **failed to find media** so I tried again and again and that’s all I see
![IMG_1540](https://github.com/movie-web/movie-web/assets/158056642/eabd4902-fe35-4618-aabf-e2fdf13e8196)

### What browsers are you seeing the problem on?

Safari

**Comment by lonelil** [comment]
Check if can you access https://api.themoviedb.org

**Comment by zisra** [comment]
Use https://1.1.1.1 if not

**Comment by Agshin2004** [comment]
the same issue happens to me, tried 1.1.1.1, didn't work

**Comment by llagerlof** [comment]
Same is happening to me.
