### ISSUE TITLE
[Feature]: Copy playlist link

### ISSUE THREAD

**Issue by ari-party** [movie-web/movie-web#857]
### What feature do you want to add?

Instead of downloading the HLS playlist, copy the download link.

### Why do you want to have this feature?

Most HLS playlists don't have the base url prefixed in segment URLs
Playing directly from a HLS playlist's link works better

### Anything other details to share?

Assign me if approved 💓

**Comment by mrjvs** [comment]
I think I do like a copy button more than opening it directly. Ill assign you
