### ISSUE TITLE
Use less permissions for extension

### ISSUE THREAD

**Issue by mrjvs** [movie-web/movie-web#858]
Currently the extension uses a lot of permissions. We've tried our best to not make it use so many but we didnt find a way.
Let's try to find a way anyway.

In an ideal world it would work like this:
- install extension, would only request to access movie-web.app.
- for other sites, it would prompt for permission once you have turned it on for that site.
- No using host permissions, it makes the chrome review team dislike us.

I don't know if this is possible, but we should try to figure out alternatives to make it use a little permissions as possible.

**Comment by binaryoverload** [comment]
We have optimised permission usage and additionally added an explanation page so that the permissions aren't as sus.

**Comment by loan-mgt** [comment]
@binaryoverload 

> We have optimized permission usage and additionally added an explanation page so that the permissions aren't as sus.

Can you provide more detail?
*'optimized permission'* -> What permissions were added/removed? What permissions are still required? What will be the next step?

*'explanation page'* -> Link to the cited page.

Thanks ❤️

**Comment by binaryoverload** [comment]
> @binaryoverload
> 
> > We have optimized permission usage and additionally added an explanation page so that the permissions aren't as sus.
> 
> Can you provide more detail? _'optimized permission'_ -> What permissions were added/removed? What permissions are still required? What will be the next step?
> 
> _'explanation page'_ -> Link to the cited page.
> 
> Thanks ❤️

You can view the page for yourself when the new extension is released. As for what permissions were optimised, we've replaced "tabs" with "activeTab"

**Comment by binaryoverload** [comment]
@loan-mgt is this you? Not cool if it is :( 

![image](https://github.com/movie-web/movie-web/assets/15330699/4822b3ab-dcb3-47d6-8445-b6c73256bdd9)

You can read the page below (Which is included with the extension) on why we use the permission we do. 

![image](https://github.com/movie-web/movie-web/assets/15330699/e357566c-426c-473d-b0d8-0a007e92492f)

**Comment by loan-mgt** [comment]
Yes, it is me. I would love to update my comment if the situation evolves.

To add on, there is some confusion about which version we are talking about. I am referring to the version of Movie-Web available at movie-web.app on Sunday, 11-Feb-24 13:18:19 UTC, and the extension version 1.0.3.

When you say that we no longer request browser history:
- In the current available version from the Chrome store, on 1.0.3, it's false:
![image](https://github.com/movie-web/movie-web/assets/37497007/e9cb1545-dd53-4259-9498-1bf97514599b)

When you say that a more detailed description of permission requirements is available with the extension:
- I've removed the extension and installed it again, used it again, but at no point has that page been shown to me. I've seen no easy access button to view it; the only things I've seen are these:
![image](https://github.com/movie-web/movie-web/assets/37497007/adf0f825-2f92-4548-9377-573578b21b94)

**Comment by binaryoverload** [comment]
> Yes, it is me. I would love to update my comment if the situation evolves.
> 
> To add on, there is some confusion about which version we are talking about. I am referring to the version of Movie-Web available at movie-web.app on Sunday, 11-Feb-24 13:18:19 UTC, and the extension version 1.0.3.
> 
> When you say that we no longer request browser history:
> 
> * In the current available version from the Chrome store, on 1.0.3, it's false:
>   ![image](https://private-user-images.githubusercontent.com/37497007/303920785-e9cb1545-dd53-4259-9498-1bf97514599b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NTgzNTIsIm5iZiI6MTcwNzY1ODA1MiwicGF0aCI6Ii8zNzQ5NzAwNy8zMDM5MjA3ODUtZTljYjE1NDUtZGQ1My00MjU5LTk0OTgtMWJmOTc1MTQ1OTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDEzMjczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZmE0YWM2YTMwYzVlOWE5MjIwNTBkYTY5MTRkZTY4MGMyMDFjNGI5M2YyYTQ2OWU0MzA2NDQyNWE4ZGFkYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UJI2Q5Ph2H9iWJgvDPui7ot7j2x4Aw_rtALteyucG3U)
> 
> When you say that a more detailed description of permission requirements is available with the extension:
> 
> * I've removed the extension and installed it again, used it again, but at no point has that page been shown to me. I've seen no easy access button to view it; the only things I've seen are these:
>   ![image](https://private-user-images.githubusercontent.com/37497007/303920934-adf0f825-2f92-4548-9377-573578b21b94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NTgzNTIsIm5iZiI6MTcwNzY1ODA1MiwicGF0aCI6Ii8zNzQ5NzAwNy8zMDM5MjA5MzQtYWRmMGY4MjUtMmY5Mi00NTQ4LTkzNzctNTczNTc4YjIxYjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDEzMjczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNTczOTFlNjVjMzE5ZTFiNDlmYjM1NDg4ZmNkMGMzZWQ2YWFhMzdmZWQ4NDRjNWIxODg4NTgyYjMyZjk1OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kJ4rBUSeTLhpBa6QaWZ96F-Lf9YXuD4SrvQQ0FS9WLQ)

We hoped the Chrome store update would be quicker, but it has not yet been approved. If you give it another day or so, it will be updated:

![image](https://github.com/movie-web/movie-web/assets/15330699/aaa73e62-d377-4810-b5ec-5cd5db7b81f9)

![image](https://github.com/movie-web/movie-web/assets/15330699/aefa1187-f1ae-4b96-ad06-362b65dc6b9a)
