### ISSUE TITLE
[Bug]: deploy backend 'relation users does not exist'

### ISSUE THREAD

**Issue by 96weibin** [movie-web/movie-web#859]
### What happened?

In my docker env. try to install postgres and ghcr.io/movie-web/backend:latest in a same network.

$ docker add network my_network
$ docker pull postgres
$ docker run --name postgrescontainer -e POSTGRES_PASSWORD=test1234 -d --network my_network postgres
$ docker run \
    -p 80:80 \
    -e MWB_POSTGRES__CONNECTION=postgres://postgres:"test1234"@postgrescontainer:5432 \
    -e MWB_CRYPTO__SESSION_SECRET=add-your-own-secret123bcdjqwerqsjkllhhhfff38872nnnl \
    -e MWB_META__NAME=unofficial-movie-web \
    --network my_network \
    ghcr.io/movie-web/backend:latest
    
-> error:   ▪ error: select "u0"."namespace", "u0"."count" from "users" as "u0" group by "u0"."namespace" - relation "users" does not exist

sorry I don't know how to slove this error.  

### What browsers are you seeing the problem on?

Chrome, Other (tell us in input box below)

### Steps to reproduce?

$ docker add network my_network
$ docker pull postgres
$ docker run --name postgrescontainer -e POSTGRES_PASSWORD=test1234 -d --network my_network postgres
$ docker run \
    -p 80:80 \
    -e MWB_POSTGRES__CONNECTION=postgres://postgres:"test1234"@postgrescontainer:5432 \
    -e MWB_CRYPTO__SESSION_SECRET=add-your-own-secret123bcdjqwerqsjkllhhhfff38872nnnl \
    -e MWB_META__NAME=unofficial-movie-web \
    --network my_network \
    ghcr.io/movie-web/backend:latest

### Other relevant information

maybe I need a sql file to migerage db? 
Can you give me some detailed steps to deploy the backend？
thank you ！

**Comment by mrjvs** [comment]
run the migrations or just enable the setting to migrate on boot. See the docs for the setting.
