### ISSUE TITLE
[Bug]: Not loading on brave browser

### ISSUE THREAD

**Issue by Fire-eighty** [movie-web/movie-web#861]
### What happened?

Any movie/tv series i try to watch, it will come up with the movie site searching screen with lookmovies, vidscrto, ect. but will not load after that point, i tried shields down (anti ad + tracker disabled) and with shields up (trackers and ads blocked enabled) but it will not load, tried turning extention on and off but nothing works, ps. there are zero error messages

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

>open brave browser
>go to movie-web.app
>click on tv/movie
>will not play

**Comment by Fire-eighty** [comment]
note: sometimes works for me when i enable the "media router" (Media router enables cast feature in the browser.) and the "hangouts" (Uses Hangouts component to enable screen sharing and other features in the browser.
) settings

**Comment by JorrinKievit** [comment]
This has been fixed with extension v1.0.3, which is pending chome store review. Expect it to be published to the stores in the upcoming days
