### ISSUE TITLE
[Feature]: Play with movie-web button on imdb using extension

### ISSUE THREAD

**Issue by dimii27** [movie-web/movie-web#862]
### What feature do you want to add?

A button injected on the imdb site (and perhaps other movie recommandations websites?) that opens the movie on the movie-web website. 

I'm not sure if the movies are linked to the mdb id or whatever but if they are this should be a fairly easy thing to to, just like a tampermonkey script.

### Why do you want to have this feature?

Because movie-web does not, as of my knowledge, have a recommandation page so using imdb as a launching point and movie-web as a streaming player would be the best of both worlds, a good synergy.

### Anything other details to share?

Excuse my ignorance if this is more complicated than I belive it is, but it doesn't have to be anything too fancy, just a button that uses the movie id and generates the link to the corresponding page on movie-web.

**Comment by TheScreechingBagel** [comment]
seems like this would be better done with a separate small userscript tbh

**Comment by zisra** [comment]
Extensions support small userscripts

**Comment by samolukadjo** [comment]
Useful

**Comment by Purfview** [comment]
Added to [IMDb Scout Mod](https://github.com/Purfview/IMDb-Scout-Mod)

Added as a simple icon, if it has API to do search then I can make it auto-searchable.

**Comment by binaryoverload** [comment]
Good enough for me
