### ISSUE TITLE
[Bug]: Invalid arg type on backend, possibly from outdated mikro

### ISSUE THREAD

**Issue by Aperture32GLaDOS** [movie-web/movie-web#863]
### What happened?

When attempting to host the backend manually, I got the error:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined +123ms
Just after it starts connecting to postgres. After looking into it, it looks like this might be caused by using an older version of mikro (view https://github.com/mikro-orm/mikro-orm/issues/4681)

### Steps to reproduce?

1. Host a minimal postgres server
2. Attempt to run the backend, either on a docker container or manually through npm

**Comment by Saverio976** [comment]
Issue happen when running `pnpm migration:up`

**Comment by binaryoverload** [comment]
You need to make sure that you have `/db` at the end of your PostgreSQL connection string 

Replace `db` with the name of your database

**Comment by Saverio976** [comment]
Thank you 👍🏿 , that fixed it

https://movie-web.github.io/docs/backend/configuration#postgresconnection

it says that the database name must be set but i was not sure how to did it
