### ISSUE TITLE
[Bug]: We encountered an error! TypeError

### ISSUE THREAD

**Issue by Abencherif** [movie-web/movie-web#864]
### What happened?

![Screenshot_2024-02-01_13-43-51](https://github.com/movie-web/movie-web/assets/47751770/7ea7b901-cbd6-4abf-9474-e7775e64036f)

Failed to fetch dynamically imported module: https://movie-web.app/assets/PlayerView-NBls8jrk.js

### What browsers are you seeing the problem on?

Chrome

**Comment by castdrian** [comment]
try turning off all browser extensions/use incognito mode, would guess somethings interfering

**Comment by Abencherif** [comment]
it's working in incognito mode, thanks
