### ISSUE TITLE
[Bug]: Swipe bar doesn’t disappear when watching on iOS

### ISSUE THREAD

**Issue by aushafer06** [movie-web/movie-web#865]
### What happened?

When viewing a show or movie on iOS, the bottom swipe/home bar doesn’t disappear like it should. This isn’t a huge problem, but it’s definitely annoying to have a distracting white bar at the bottom of your screen when enjoying a movie.

### What browsers are you seeing the problem on?

Safari

### Steps to reproduce?

Just watch a movie on iOS, the bottom bar won’t go away.

**Comment by JipFr** [comment]
Sadly a browser limitation, nothing we can do. If you watch in normal Safari (not standalone), the white bar will vanish.
