### ISSUE TITLE
[Bug]: Downloading doesn’t work on iOS

### ISSUE THREAD

**Issue by aushafer06** [movie-web/movie-web#866]
### What happened?

When I try to download a movie, it brings me to a separate page and just starts a second instance of movie web. There isn’t a way to download on iOS. The instructions say to share the video and save to files but the share button doesn’t exist because it just brings me back to movie web and starts the movie.

### What browsers are you seeing the problem on?

Safari

### Steps to reproduce?

Try downloading a movie on iOS. It has never worked for me.

**Comment by binaryoverload** [comment]
This issue is likely to do with movie-web opening up HLS links in the browser. This behaviour has now been changed to copy the link instead
