### ISSUE TITLE
[Feature]: Change Extension Icon to gray to indicate when it's inactive

### ISSUE THREAD

**Issue by binaryoverload** [movie-web/movie-web#867]
### What feature do you want to add?

Similar to extensions like uBlock, Honey etc that change their icon to gray when the extension isn't active on the current tab

### Why do you want to have this feature?

See at a glance whether the extension is enabled on the tab

### Anything other details to share?

https://developer.chrome.com/docs/extensions/reference/api/action#method-setIcon

**Comment by zisra** [comment]
Can I take this?

**Comment by JorrinKievit** [comment]
Sure 🙂 @zisra

**Comment by JorrinKievit** [comment]
Since it has been a while, can I take this? @zisra Or are you still working on it?
