### ISSUE TITLE
[Feature]: PC - Extend the caption box length

### ISSUE THREAD

**Issue by veritasestmoi** [movie-web/movie-web#870]
### What feature do you want to add?

Extend the caption box length so it is not bundled in the middle like this:
![Bundled together](https://github.com/movie-web/movie-web/assets/68550874/7faec29b-550c-497a-a777-ea1f2fd36ec8)

So it will be more like this:
![longer](https://github.com/movie-web/movie-web/assets/68550874/9947c4e4-b668-4774-bd7d-b0396ca0f62b)

The mobile version works fine though. 

### Why do you want to have this feature?

The subtitles are taking up too much space. 

### Anything other details to share?

Mobile works fine (from what I see at the moment

THX

**Comment by Astro7145** [comment]
I want to work on it! Does that mean you want it to be like wide 2 lows in the caption rather than small 3 lows?

**Comment by veritasestmoi** [comment]
Yeah you can say that! 

But for shorter sentences we can use just one line.

Perhaps limiting the height will work. 

Appreciate!

**Comment by Astro7145** [comment]
Yeah, I think thats pretty reasonable way!
However, I just read the code, and it seemed to be parsing regular expressions and replacing those to html tags.

`const textWithNewlines = (textToUse || "")
       .split(" ")
       .map((word) => wordOverrides[word] ?? word)
       .join(" ")
       .replaceAll(/ i'/g, " I'")
       .replaceAll(/\r?\n/g, "<br />");`

So, in my opinion, it'd be better if we make it in a low, and separate it on a certain point(Maybe, it can be every 8 words, or a word when it exceeds 400px in width, or something else). Sorry if my explanation is too messy and hard to understand😓

**Comment by mrjvs** [comment]
@Astro7145 the code you quoted was just the way we "fix" captions. See the "fix capitalization" option in the subtitle customization menu. You won't have to change that code.

All that needs to be done is fix the max-width css setting of a caption cue.
It's quite short right now, it can be made bigger but not too big. We don't want long lines to go crazy long on large screens.

I'll assign you.

**Comment by Astro7145** [comment]
@mrjvs yeah, you're absolutely right! I also realized that it was just customizing the captions after I commented and reviewed the code a bit more... Thank you for you advice!

**Comment by Astro7145** [comment]
@mrjvs hmm... maybe I was wrong because the `parsedHtml` was being called for every caption when I debugged it... and the `CaptionCue` is using `parsedHtml` to display subtitles and I think there is no other way to mount a new `string | TrustedHTML` into `parsedHtml` variable other than provoking `useMemo()` by change of the value in the dependencies. Although I doubt it myself but is it really wrong...?
