### ISSUE TITLE
[Bug]: Extension stuck on "Grant Permissions"

### ISSUE THREAD

**Issue by Darthagnon** [movie-web/movie-web#872]
### What happened?

Browser extension does nothing and does not work on recent Chromium versions.

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

1. Install extension
2. Extension does nothing, is stuck on "Please Grant Permissions"; button does not work
![chrome_240203_01](https://github.com/movie-web/movie-web/assets/20792748/20900995-6d9b-4e9c-a749-f887a7c5dc7a)

### Other relevant information

Chromium version:
`Version 90.0.4430.212 (Official Build, ungoogled-chromium) (64-bit)`

**Comment by mrjvs** [comment]
cannot reproduce, even if I revoke permission manually. On latest chrome, the grant permission button works as it should.

**Comment by JorrinKievit** [comment]
FYI Someone else had this issue and had to update his Chrome to work. Your chromium version also seems very old, I am on 121.0.6167.140

**Comment by Darthagnon** [comment]
Works on newer Googled Chromium builds, e.g. Supermium. Unfortunately not retro-compatible. 

Would it be possible to put a hard block in the code to prevent it running on older/untested Chromium builds? Would prevent disappointment. [Duplicate Tab](https://chromewebstore.google.com/detail/duplicate-tab/ljhkjdibhiomfkbpkbfcffpgbpkggnif) extension has code in v2.0.0 to block running on Chromium less than v120
