### ISSUE TITLE
[Feature]: Document how this application works

### ISSUE THREAD

**Issue by igoracmelo** [movie-web/movie-web#873]
### What feature do you want to add?

An explanation in the docs or the app on how it works

### Why do you want to have this feature?

For curiosity... Like how is it different from website X or using torrents

**Comment by mrjvs** [comment]
The readme has plenty of explanations:
> This service works by displaying video files from third-party providers inside an intuitive and aesthetic user interface.

> Content is fetched from third parties and scraping is fully done on the client. This means that the hoster has no files or media on their server. All files are streamed directly from the third parties.

It's just a viewer of content for various other streaming sites.
