### ISSUE TITLE
movie-web.app/api — Rest API to access movies

### ISSUE THREAD

**Issue by creuserr** [movie-web/movie-web#875]
### What feature do you want to add?

Hello devs, I was wondering if you could create a REST API for this.

**/status** - returns the status (activity/inactivity) of providers

`movie-web.app/api/status`
```json
{
  "zoechip": true,
  "showbox": false,
  ...
}
```

**/search?q={query}** - search for a movie
`movie-web.app/api/search?q=Escape+Room`
```json
[{
  "title": "Escape Room",
  "resolutions": [1080, ...],
  "providers": ["zoechip", ...],
  "id": "escape-room-123",
  ... other information (e.g. release year, production, etc)
}]
```

**/get?id={id}&res={resolution}&src={provider}** - return the URL for downloading the movie
`movie-web.app/get?id=escape-room-123&res=1080&src=zoechip`
```json
{
  "url": "https://o.polllop.com/..."
}
```

**/caption** - return the caption/download URL for captions"

### Why do you want to have this feature?

This feature promises to be both innovative and highly valuable for developers.

### Anything other details to share?

For additional safety, you could block access to movies that claim copyright.

`https://movie-web.app/api/search?q=Escape+Room`
```json
[{
  "isBlocked": true,
  "title": "Escape Room",
  ...
}]
```

**Comment by lonelil** [comment]
Providers package and https://github.com/movie-web/providers-api already exists?

**Comment by creuserr** [comment]
oh I didn't knew that. sorry!

**Comment by mrjvs** [comment]
providers-api repo is strictly for movie-web official instance. We give no support at all for trying to use it yourself. Also breaking changes will be made without consideration for others.

https://github.com/movie-web/providers is the recommended way to use movie-web sources on your own site.
