### ISSUE TITLE
[Bug]: TypeError when loading media

### ISSUE THREAD

**Issue by TortitasT** [movie-web/movie-web#877]
### What happened?

I'm getting this error when clicking on any movie or series episode:
![Screenshot_2024-02-04-21-47-31-85_3aea4af51f236e4932235fdada7d1643](https://github.com/movie-web/movie-web/assets/76071376/69571552-b5f1-44fa-b135-1740c6c1cf77)

I've tested on Firefox (which the screenshot is from) and Chrome.

I've also cleared the site data on Chrome and it still doesn't work.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Steps to reproduce?

1. Go to main screen.
2. Click on a recent seen series episode.

**Comment by binaryoverload** [comment]
This issue should be fixed by clearing the cache for the site
