### ISSUE TITLE
[Bug]: Custom Proxy Stopped Working

### ISSUE THREAD

**Issue by HudsonBlock** [movie-web/movie-web#880]
### What happened?

I have tried re making a new proxy but its just going right to Zoe Chip and buffering. it says that the proxy is working fine when you click on it, please fix! thanks!

### Steps to reproduce?

added a custom proxy, which I forked to Netlify, the one made for Movie Web, It was working until one time it didnt work, it want in between sessions, it was at around 1am on monday and it just didnt load the next episode on my proxy, only on zoe chip, and it didnt stop buffering. I tried making a new proxy but nothing.

**Comment by TheScreechingBagel** [comment]
showbox is currently not working for everyone
