### ISSUE TITLE
Subtitle Importing on Mobile

### ISSUE THREAD

**Issue by lelemathrin** [movie-web/movie-web#882]
### What happened?

On IOS mobile browsers, we have the option to import subtitles from a file, which opens the file explorer but we’re unable to pick a .srt file, unlike on Desktop, which makes this feature absolutely unusable on Mobile.

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by lockieluke** [comment]
Yes on iOS I’m unable to pick an SRT file

**Comment by binaryoverload** [comment]
We had one of our devs running an iOS test on this, and they had no issues uploading a `.srt` file. It's possible you're downloading a file with a different extension which is causing it not to show up.
