### ISSUE TITLE
What are actually the advantages of using the extension as opposed to a self-hosted proxy?

### ISSUE THREAD

**Issue by Void-0000** [movie-web/movie-web#888]
The onboarding page says a proxy has "good quality", while the extension has "best quality", why? Is there a significant difference between the two?

Sorry if this isn't the right place to ask, but I couldn't find any information about this anywhere else and I'd personally prefer not to have to install an extension for one website.

**Comment by mrjvs** [comment]
extension can use ip locked sources. proxy cannot since its not the same ip as the viewer.
That extension also can set custom headers on streams that normally cant be set as the proxy doesnt proxy media itself (to save costs, proxying media is expensive)
