### ISSUE TITLE
[Feature]: Limit access to certain sites

### ISSUE THREAD

**Issue by sirenkovladd** [movie-web/movie-web#889]
### What feature do you want to add?

https://github.com/movie-web/extension/blob/dev/src/hooks/usePermission.ts#L17

Grant access to site content only to certain pages

### Why do you want to have this feature?

Safety and security

**Comment by mrjvs** [comment]
That list is dynamic and changes daily.
We need access to every site we make a request to, not just movie-web.app and selfhosters.
