### ISSUE TITLE
[Bug]: atob and crypto-js does not work in React Native

### ISSUE THREAD

**Issue by JorrinKievit** [movie-web/movie-web#890]
### What happened?

The providers lib is not usable in React Native because of some missing polyfills. We miss both a polyfill for atob, and for crypto-js 
![image](https://github.com/movie-web/movie-web/assets/43169049/580842b9-4cbe-461f-b677-e5b798e10132)

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

1. Install providers lib in a react native/expo project
2. Start scraping

### Other relevant information

We have fixed atob with this fix: https://github.com/movie-web/native-app/blob/15f3de83e455e4019c15d9e25c7df1ee5087cf16/apps/expo/index.js#L2

But this should be done in the providers lib instead.

**Comment by castdrian** [comment]
I’ll happily do that if assigned
