### ISSUE TITLE
[Feature]: Allow video streams to be proxied on custom proxies 

### ISSUE THREAD

**Issue by Paradox-77** [movie-web/movie-web#892]
### What feature do you want to add?

Let users who are selfhosting their proxy and have enough network bandwidth - proxy the video stream so that they need not use the extension on their browser. 

### Why do you want to have this feature?

I want to use it on devices that have webview support but don't have fancy features like extensions and plugins. And It's just convenient to open my instance on a new device and have it working without me doing anything else. 

### Anything other details to share?

I'm working under the assumption that an hour of 1080p content would take about 1.5 gigs of bandwidth. And if it's only you or your family and friends who use the instance it won't be much per month.

**Comment by binaryoverload** [comment]
As mentioned in a conversation in our Discord server, allowing this would open up inexperienced users to potentially huge bills from their proxy provider. Because of this, we won't be implementing this feature outside of the browser extension
