### ISSUE TITLE
[Bug]:  Proxy Extension permissions

### ISSUE THREAD

**Issue by loan-mgt** [movie-web/movie-web#894]
### What happened?

The Movie-web proxy extension requires permission to read and change data on **all** websites, and not just movie-web.app, to work.

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

Install the Chrome extension

### Other relevant information

Actual Behavior:
Movie-web proxy extension requires permission to read and change data on **all** websites.

Expected Behavior:
Need permission only for a select range of domains, and the default is movie-web.app.

**Comment by JorrinKievit** [comment]
Duplicate of https://github.com/movie-web/movie-web/issues/858
