### ISSUE TITLE
[Bug]: Unable to switch subtitles on Ridomovies

### ISSUE THREAD

**Issue by JorrinKievit** [movie-web/movie-web#906]
### What happened?

The Ridoo embed has the subtitles/captions in the HLS playlist. The first subtitle is shown in the player, but the subtitle menu does not show the the other subtitles that are in this HLS playlist. This means the Chinese one is always shown with no option of selecting another language.

### Steps to reproduce?

1. Go to https://movie-web.app/media/tmdb-tv-84958-loki/114355/2534997
2. Use Ridomovies

### Other relevant information

Below is an example of a master HLS playlist file with subtitles:
![image](https://github.com/movie-web/movie-web/assets/43169049/4615dee3-12ba-4438-9971-dddd14ed565c)
![image](https://github.com/movie-web/movie-web/assets/43169049/d3ede6b7-3624-4c1b-b1a8-911e3b6d5a16)

**Comment by JorrinKievit** [comment]
Some extra information for this one. It currently uses the native subtitle track renderer from hls.js. This should be using our own renderer instead.

**Comment by ssssobek** [comment]
Hey, do you have any other cases of that behavior? I managed to switch languages, and make it use the movie-web subtitle renderer instead of hls.js one, but I definitely need to do more testing.
![ckGkHe07wD](https://github.com/movie-web/movie-web/assets/95639019/1dd298d9-3337-4a2e-931e-6f1a82254174)

**Comment by JorrinKievit** [comment]
Nope! That should be it!

1. If you are able to choose another subtitle (by language, and should load flags). 
2. You are able to turn it on and off
3. It uses our own subtitle renderer.

^ if this all works feel free to open a PR so we can review it and also test it a bit 😁

**Comment by ssssobek** [comment]
Could I get this assigned to me? Not quite ready for a PR, but closer than ever
