### ISSUE TITLE
[Bug]: Failed to verify your humanity.Please try again.

### ISSUE THREAD

**Issue by Mastermind-sap** [movie-web/movie-web#912]
### What happened?

The site was working fine earlier but now I am getting the message ```Failed to verify your humanity.Please try again.``` on any movie or series I want to watch.

### What browsers are you seeing the problem on?

Chrome

### Other relevant information

I tried deleting the browser cookies related to the site and now the doesn't even load.

**Comment by ART3MISTICAL** [comment]
Same problem, tried again after turning off the extension, it worked

**Comment by Mastermind-sap** [comment]
@ART3MISTICAL The site is not responding I also tried removing the extension but the site is not loading.

**Comment by binaryoverload** [comment]
Please clear your browser cache for movie-web
