### ISSUE TITLE
[Bug]: movies not playing

### ISSUE THREAD

**Issue by Preston-Riley** [movie-web/movie-web#913]
### What happened?

All movies i have tried will not work it just says we have gone through all of our providers and could not find it

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Steps to reproduce?

Run any movie

**Comment by JorrinKievit** [comment]
Do you use the extension or custom proxy?

**Comment by Preston-Riley** [comment]
Custom proxy

**Comment by Preston-Riley** [comment]
Using cloudflare

**Comment by JorrinKievit** [comment]
Most of the sources are down. Only showbox works reliably but is blocking cloudflare. So if you want to get better sources either host on netlify, or use the extension

**Comment by TheScreechingBagel** [comment]
> Using cloudflare

use netlify, showbox blocks cloudflare

extension is even better unless you’re on ios

**Comment by Preston-Riley** [comment]
Ok thanks
