### ISSUE TITLE
[Bug]: website not reachable on ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by zeltrex7** [movie-web/movie-web#914]
### What happened?

have been facing this issue when trying to visit the url https://movie-web.app nothing is returned on my linux machine on windows it is working fine . please let me know if there something to do to make it work . Thanks
[Screencast from 15-02-24 12:09:29 PM IST.webm](https://github.com/movie-web/movie-web/assets/93510067/5e23b16f-8f4a-4951-8aec-2cd59e26ce95)

### What browsers are you seeing the problem on?

Firefox, Chrome, Other (tell us in input box below)

**Comment by erikk333** [comment]
Try change DNS in browser settings. Just a suggestion. If it doesn't help then sorry
