### ISSUE TITLE
[Bug]: Fail to load profile without VPN

### ISSUE THREAD

**Issue by chamannarved** [movie-web/movie-web#917]
### What happened?

I Can't load my profile on a normal internet connection.
When I connect to a VPN service then it works normally.

![image](https://github.com/movie-web/movie-web/assets/24298575/aca7f4c0-ccf7-4a78-9634-bb980e5d310e)

after I log out I can't log in to my account.

![image](https://github.com/movie-web/movie-web/assets/24298575/ad54179d-3317-49ca-bc94-d411878699c6)

App worked on normal internet connection in previous versions but now needs to connect to a VPN Service. 

### What browsers are you seeing the problem on?

Firefox

### Steps to reproduce?

1. Create a sync account. (now need to connect to a VPN to create or log in to the account)
2. Disconnect to VPN.
3. Then open/reload the app.

**Comment by castdrian** [comment]
sounds like your ISP might be blocking something, you could take a look at the console to see which requests fail

**Comment by chamannarved** [comment]
I have the same ISP before this error then it works perfectly.

**Comment by binaryoverload** [comment]
It works over VPN, so this isn't a problem with us. It might be a DNS issue, so you can use https://1.1.1.1/dns instead to see if that fixes the issue.

Otherwise, it's out of our hands
