### ISSUE TITLE
[Feature]: Enhanced Search Bar Placeholder

### ISSUE THREAD

**Issue by vijaysingh2219** [movie-web/movie-web#918]
### What feature do you want to add?

To enhance user experience, I recommend adding an array of diverse placeholders to the search bar in our web app. By randomizing these placeholders with each user entry, we create a dynamic and engaging atmosphere. 

### Why do you want to have this feature?

Users will encounter varied prompts like "Discover your perfect show or movie" or "Search for your preferred shows and movies" promoting a fresh and personalized interaction every time. This approach not only adds an element of surprise but also encourages users to approach their searches with renewed curiosity, contributing to a more positive and enjoyable web app experience.

**Comment by binaryoverload** [comment]
You gave us a good chuckle with that one, approved 😆 

For anyone who wants to implement this, this should be implemented in the same way as we do titles with the most random weighting on the normal version, with alternatives being less frequent
