### ISSUE TITLE
[Bug]: Error while deploying movie web backend docker image on render

### ISSUE THREAD

**Issue by vijayvcm** [movie-web/movie-web#924]
### What happened?

I am trying to host the docker image in the render.com.

I have created a new Postgresql instance in `Neon` and copied that connection string into the render.com environmental variable.

I had the three environmental variables shown below.

    -e MWB_POSTGRES__CONNECTION=connection string here \
    -e MWB_CRYPTO__SESSION_SECRET=add-your-own-secret \
    -e MWB_META__NAME=unofficial-movie-web \

After the build stage, when the migrations started to happen I saw some errors related to Postgresql. I have attached the error image for reference below.

Also, I have tried adding the below env variables as well

```
MWB_POSTGRES__SSL=true
```

I am following the below link. Am I missing something here?

https://docs.movie-web.app/backend/deploy

<img width="815" alt="image" src="https://github.com/movie-web/movie-web/assets/11239522/c85e7fed-bca5-4c8d-a79f-d0f93dabb741">

### Steps to reproduce?

1. Login to render.com
2. Create a new service and choose movie web backend docker image
3. Create a new Postgresql instance in Neon 
4. Copy the connection string and configure environmental variables in render.com along with the mandatory env variables given in the above link.
5. When the deployment started, after the build stage you can see the errors.

**Comment by binaryoverload** [comment]
You need to run the migrations against your Postgres database

You can do this by running `pnpm run migration:up`, or setting `MWB_POSTGRES__MIGRATE_ON_BOOT` to `true`
