### ISSUE TITLE
[Bug]: the latest version of the extension on firefox isn't accepted

### ISSUE THREAD

**Issue by Headedbranch225** [movie-web/movie-web#925]
### What happened?

I was setting up the extension, and it is saying the extension is too old, even though I reinstalled the extension from Firefox to ensure I was using the latest version.

### What browsers are you seeing the problem on?

Firefox

### Steps to reproduce?

go to the setup and try and setup the extension.

**Comment by binaryoverload** [comment]
I cannot replicate this issue, make sure to clear your cache locally as this was an issue on an older version of the movie-web client.

The version it was fixed was `4.4.2`, make sure it shows that version in https://movie-web.app/settings
