### ISSUE TITLE
[Bug]: Poor Foreign character support for subtitles

### ISSUE THREAD

**Issue by thedavidweng** [movie-web/movie-web#926]
### What happened?

For foreign language subtitles outside English, such as Chinese and Arabic, the subtitles cannot be fully displayed due to lack of characters in fonts.

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

Open a subtitle file that contains foreign language. (Eg. [House.of.Cards.2013.S01E11.](https://assrt.net/xml/sub/691/691715.xml).

**Comment by zisra** [comment]
<img width="556" alt="Screenshot 2024-03-06 at 11 12 33 AM" src="https://github.com/movie-web/movie-web/assets/100528712/e0b198c8-4a92-46ef-ad83-6c50aa2113c5">
Cannot reproduce ... maybe update your OS fonts or your browser

**Comment by thedavidweng** [comment]
> <img alt="Screenshot 2024-03-06 at 11 12 33 AM" width="556" src="https://private-user-images.githubusercontent.com/100528712/310591412-e0b198c8-4a92-46ef-ad83-6c50aa2113c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTAwNTIsIm5iZiI6MTcwOTc4OTc1MiwicGF0aCI6Ii8xMDA1Mjg3MTIvMzEwNTkxNDEyLWUwYjE5OGM4LTRhOTItNDZlZi1hZDgzLTZjNTBhYTIxMTNjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QwNTM1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDBmYTQxZWQ0M2RlY2Y3ZDFiM2FhMDJhYjY3ODQ1YmQ2Mzc2YjYyOTA3NDc3YzQyYTE3OTFmZDI4MTk2MDNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6xfeo2yW3uCxJbrG7XEpcvmwDzy1H-FXWkzem7DLEKE"> Cannot reproduce ... maybe update your OS fonts or your browser

hmmm, I'm on macOS with default settings, and most of the Chinese characters are missing in the attached .srt.

**Comment by binaryoverload** [comment]
I cannot reproduce these issues, which likely means the issue is with either the fonts on your computer or your network blocking the download of Google fonts
