### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ahablak** [movie-web/movie-web#931]
### What happened?

After about 20 mins of watching, the video pauses and starts loading and then stops with the erroe:

htmlvideo: Some kind of network error occurred which prevented the media from being successfully fetched, despite having previously been available.

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

1. Load and watch video for 10-20 minutes.
2. Error pops up.

**Comment by JorrinKievit** [comment]
Could be that the provider server simply fails to respond. Feel free to reopen if it happens consistently. Without reproduction this won't be fixable.
