### ISSUE TITLE
[Bug]: Checking movies by release year should be added

### ISSUE THREAD

**Issue by GiorgiCoder** [movie-web/movie-web#932]
### What happened?

I was trying to find Netflix's Avatar so I searched it and found one of 2024. But when I the media that was found was animated series of 2005. Probably because they have the same name(?)

**Comment by owenand001** [comment]
Yes!! I was trying to search for Stalker 1979 by searching “Stalker” and I couldn’t find it until searching “Stalker 1979”

**Comment by JorrinKievit** [comment]
We do this where we can, but with some providers it is simply not possible to also match on release year. This will probably only result in even fewer matches.

Feel free to check the movie-web/providers library and see if the scrapers can be improved to also match the release year.
