### ISSUE TITLE
[Feature]: Empowering Search Results with TMDB Link Integration

### ISSUE THREAD

**Issue by vijaysingh2219** [movie-web/movie-web#934]
### What feature do you want to add?

I propose adding a TMDB icon to the search results in the `MediaCard.tsx` component. This icon will be a direct link, directing users to the corresponding TMDB page for the movie, series, or show displayed in the search results.

This feature aims to allow users to access detailed information about the movie or series before watching it, allowing them to make more informed decisions.

### Why do you want to have this feature?

To elevate user experience, the integration of TMDB links in search results aims to empower viewers with detailed insights into movies or series, aiding informed decisions and enriching their overall engagement with our platform.

**Comment by zisra** [comment]
This would probably be best in the format as #334

**Comment by JorrinKievit** [comment]
I agree, lets mark this as a duplicate and follow #334
