### ISSUE TITLE
[Feature]: Allow dismissing the 'Check your internet connection' error

### ISSUE THREAD

**Issue by Stretch96** [movie-web/movie-web#944]
### What feature do you want to add?

Whilst playing videos, the 'Check your internet connection' error sometimes appears, even if connection from the client device is fine
The only way to hide it currently, is to modify the the CSS via the developer browser (eg. set `display: none` to the div showing the error)
Would be nice to have a 'Dismiss' button within the bar that shows the error

### Why do you want to have this feature?

The error bar can't be easily dismissed, causing a distraction whilst watching videos

**Comment by TheScreechingBagel** [comment]
Sounds like you're still using movie-web.app . That site has been taken down, and you're using a cached version (will stop working soon)

you should switch to a community instance: https://movie-web.github.io/docs/instances

**Comment by zisra** [comment]
This should still be approved because there are false positives for this error

**Comment by TheScreechingBagel** [comment]
true add an x or smthn

**Comment by saadmalik96** [comment]
You can use an adblocker to block the element.

**Comment by TheScreechingBagel** [comment]
> You can use an adblocker to block the element.

or just use a new instance, movie-web.app is not supported
