### ISSUE TITLE
[Bug]: Unnecessary internet connection toast shown

### ISSUE THREAD

**Issue by chengfengfengwang** [movie-web/movie-web#945]
### What happened?

I am using the movie-web extension to watch movies. I received an error message saying 'check your internet connection', but my video continues to play normally. My network connection is stable. I opened my browser to check, and it seems the issue stems from fetching 'https://movie-web.app/ping.txt'.

<img width="938" alt="image" src="https://github.com/movie-web/movie-web/assets/23279667/4aae1de4-49f0-4f18-90e8-371d0e23fd54">

### What browsers are you seeing the problem on?

Chrome

### Other relevant information

I am a user from mainland China, and I am using a VPN to watch...

**Comment by castdrian** [comment]
the domain was taken down, use a mirror, your browser is running on a cached version

**Comment by chengfengfengwang** [comment]
> the domain was taken down, use a mirror, your browser is running on a cached version
Do you mean this project no longer provides the 'https://movie-web.app/' service? Do I now have to host my own instance of movie-web?

**Comment by castdrian** [comment]
correct, the demo site no longer exists
