### ISSUE TITLE
[Feature]: Search all sources for highest quality stream

### ISSUE THREAD

**Issue by owenand001** [movie-web/movie-web#950]
### What feature do you want to add?

A functionality to search through all streams for the highest quality content.

### Why do you want to have this feature?

It’s annoying to have to click through all of the sources manually and sometimes have the app crash to find the highest resolution stream.

### Any other details to share?

Maybe a setting in settings to choose the default stream resolution to search for.

**Comment by zisra** [comment]
Sources are (or should be) ordered by quality anyways

**Comment by JorrinKievit** [comment]
We will not scrape all sources at the same time because this increases the workload on the proxy servers 20x. This won't be scalable for self-hosters.
