### ISSUE TITLE
[Bug]: Extension version too old

### ISSUE THREAD

**Issue by lockieluke** [movie-web/movie-web#957]
### What happened?

When I was trying to view a content, I was prompted to install the Chrome extension and I then enabled it on the website.  movie-web successfully detected it but said it's too old even though it's the newest version

### What browsers are you seeing the problem on?

Chrome

### Other relevant information

I've found a temporary solution:
1. Unpack the extension
2. Edit the `manifest.json` in it and change `version` to `1.0.2`
3. Install/Reload the extension in Chrome/Arc
4. Reload the page

**Comment by JorrinKievit** [comment]
Which site are you using?

**Comment by lockieluke** [comment]
https://movie-web.app/

**Comment by JorrinKievit** [comment]
That domain no longer exists. Check the Discord for information, and https://movie-web.github.io/docs/instances

**Comment by lockieluke** [comment]
Ahh it's probably the PWA cache then, so much has changed since the last time I used which was only a month ago, good to see that you guys are making great progress!  Keep up the good work 👍

**Comment by JorrinKievit** [comment]
Yes it is indeed PWA cache 😄
