### ISSUE TITLE
[Bug]: Frontend bug on the main page

### ISSUE THREAD

**Issue by Alejandro18650** [movie-web/movie-web#962]
### What happened?

The text "Detener Edición" is not in the center, and it hides the "Continuar viendo" text

https://github.com/movie-web/movie-web/assets/92676426/ea6e8dd0-0ed5-4d7b-97dc-16affb09f300

### What browsers are you seeing the problem on?

Firefox

**Comment by mustafa-kapadia1483** [comment]
Hi @JorrinKievit, I would like to take up this issue & work on it. 
When checking the CSS code for this. Found the issue to be adding margin inside the button to give padding which I believe is a wrong approach. 
We can remove `mx-4` which should solve this issue.

![image](https://github.com/movie-web/movie-web/assets/60058032/54abbd03-36cd-4071-9ef0-f96cf282d2f3)

**Comment by mustafa-kapadia1483** [comment]
If we reduct the font size & padding for mobile we can keep the same layout:
![image](https://github.com/movie-web/movie-web/assets/60058032/f77de683-f9e4-4370-8cc1-36926a3bb040)

**Comment by Alejandro18650** [comment]
I don't think it's a good solution. That breaks the aesthetics of the website.
We can try to separate it in two rows in mobile.

**Comment by JorrinKievit** [comment]
^ Ye would be nice if you start editing the continue watching label goes above it with a nice transition
