### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by aymanlamOuO7** [movie-web/movie-web#963]
### What happened?

i cant log in 

### Steps to reproduce?

![image](https://github.com/movie-web/movie-web/assets/132263167/511129fa-740c-49c4-936d-8e84814fc08c)

**Comment by TheScreechingBagel** [comment]
movie-web.app has been taken down, use a community instance instead: https://movie-web.github.io/docs/instances

what you’re seeing is a cached version of the site, no updates and will disappear soon
