### ISSUE TITLE
[Feature]: Add Back4App to the backend

### ISSUE THREAD

**Issue by itsmeadarsh2008** [movie-web/movie-web#970]
### What feature do you want to add?

[Back4App (b4a)](https://www.back4app.com/)

### Why do you want to have this feature?

It is free forever for personal use (generous free tier)
![image](https://github.com/movie-web/movie-web/assets/71959210/6fcc491b-00f4-47da-be70-1f1f52326d57)

### Any other details to share?

A Railway Alternative
![back4app-workflow](https://github.com/movie-web/movie-web/assets/71959210/730b014f-3314-45ae-b65e-2bd8ca64d66e)

**Comment by TheScreechingBagel** [comment]
25k free requests seems kinda low but i’m not sure

**Comment by itsmeadarsh2008** [comment]
I have hosted several APIs using Python on this, the response time is **blazingly fast**. Maintainers should look into their services.

**Comment by binaryoverload** [comment]
This isn't in scope for the project - people can host the backend however they like.

**Comment by itsmeadarsh2008** [comment]
Just like in Railway, you have set up easy configuration (put information and deploy) for the backend. I want the same for Back4App. It is free for your personal use. It supports docker
