### ISSUE TITLE
[Bug]: My request needs to carry the url parameter of the apikey to access it normally

### ISSUE THREAD

**Issue by OnGoingLzy** [movie-web/movie-web#977]
### What happened?

My request needs to carry the url parameter of the apikey to access it normally, otherwise the response prompts me: "Invalid key", is this normal?
eg ： **api_key: apiKey,** `export async function multiSearch(
  query: string,
): Promise<(TMDBMovieSearchResult | TMDBShowSearchResult)[]> {
  const data = await get<TMDBSearchResult>("search/multi", {
    query,
    include_adult: false,
    language: "en-US",
    page: 1,
    api_key: apiKey,
  });
  // filter out results that aren't movies or shows
  const results = data.results.filter(
    (r) =>
      r.media_type === TMDBContentTypes.MOVIE ||
      r.media_type === TMDBContentTypes.TV,
  );
  return results;
}`

**Comment by JorrinKievit** [comment]
What are you trying to do? These requests pass in a read api key in the authorization header

**Comment by JorrinKievit** [comment]
Closed due to inactivity
