### ISSUE TITLE
Can u guys pls add download button too

### ISSUE THREAD

**Issue by Aruraka** [movie-web/movie-web#978]
### What feature do you want to add?

Hello guys can u please add download button and make sure whether the downloaded shows stay at the app itself instead of in the internal memory of phone 

### Why do you want to have this feature?

I wanna want this feature as I have limited net.so I wanna download shows

### Any other details to share?

And can u guys make the download option available in different qualities too like 240 p to 480p ?

**Comment by TheScreechingBagel** [comment]
1. there is already a download button, showbox is the only source that has mp4 tho
2. probably not, at least not until the native app is done
3. it downloads whatever quality is selected in the video player
