### ISSUE TITLE
[Bug]: spanish translation missing symbols

### ISSUE THREAD

**Issue by MattEzekiel** [movie-web/movie-web#982]
### What happened?

For the spanish translations it is missing some symbols like `¡` `¿`

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Other relevant information

There is an easy fix every time you have an `!` symbol or `?` at the start of the sentence you should have `¡` or `¿`

**Comment by MattEzekiel** [comment]
I can solve it

**Comment by MattEzekiel** [comment]
I would like to solve it

**Comment by binaryoverload** [comment]
Translations can be fixed on https://movie-web.github.io/links/weblate
