### ISSUE TITLE
[Bug]: Favicon doesn't appear on the docs website

### ISSUE THREAD

**Issue by apers00n** [movie-web/movie-web#983]
### What happened?

The icon in the tab for the website is missing. There's a favicon in the docs repo [https://raw.githubusercontent.com/movie-web/docs/master/public/favicon.ico](url) but the website doesn't seem to be using it. 
<img width="1440" alt="Example 1" src="https://github.com/movie-web/movie-web/assets/99437297/c06f150b-bd7d-4f7c-bcd5-5f858e05a10c">
---
---

<img width="1440" alt="Example 2" src="https://github.com/movie-web/movie-web/assets/99437297/b75b82d2-51c2-4b75-abdc-c714fd629008">

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by binaryoverload** [comment]
Fixed in https://github.com/movie-web/docs/commit/0fb2861625f74c3b84b0583fe60133bbed20cef2
