### ISSUE TITLE
[Feature]: A way to remove the "Check your Internet Connection" banner

### ISSUE THREAD

**Issue by adisidev** [movie-web/movie-web#984]
### What feature do you want to add?

I would like to add a way to remove the "Check your Internet Connection" red banner. Perhaps, a cross on the right most side that allows me to dismiss it?

### Why do you want to have this feature?

Sometimes the banner comes up even when my internet connection is working just fine. Anyhow, even if my internet connection is slow, I'd rather watch bad quality video without the banner than with.

### Any other details to share?

I just wanted to thank all the contributors - this is truly an amazing app!

**Comment by JorrinKievit** [comment]
Check pinned issue
