### ISSUE TITLE
[Bug]: Long language names for Greek, Malay

### ISSUE THREAD

**Issue by zisra** [movie-web/movie-web#986]
### What happened?

Both Greek and Malay have really long and bad language names that not only look bad but take extra space. I'm sure there are more languages with a weird name like this but they should all be fixed

### Steps to reproduce?

1. (With extension) go to Simpsons Movie
2. Press cog
3. Press Subtitle settings
4. Observe Greek and Malay:

<img width="335" alt="Screenshot 2024-03-06 at 12 34 13 PM" src="https://github.com/movie-web/movie-web/assets/100528712/f6855e36-0ea1-4394-b4de-01874d3a8f9f">

**Comment by arrzdev** [comment]
Can I get assigned to this? I am working on this to a college class.

**Comment by binaryoverload** [comment]
We've done enough messing about with languages - I don't want to be adding overrides for loads of languages
