### ISSUE TITLE
[Bug]: Check your internet connection banner doesn't go away when network is restored

### ISSUE THREAD

**Issue by JoeEverest** [movie-web/movie-web#987]
### What happened?

<img width="1121" alt="image" src="https://github.com/movie-web/movie-web/assets/42711226/9bdd0ca9-7cee-4f44-a2d5-f1cce66325b7">

### Steps to reproduce?

Disconnect internet temporarily while movie is playing, wait for banner to appear, restore internet connection

**Comment by JipFr** [comment]
Is this on the official instance? If so, please see #936 and close the issue.

**Comment by seal349** [comment]
This is happening to me all the time, and I am on Firefox if that helps.

**Comment by JorrinKievit** [comment]
Check pinned issue

**Comment by JorrinKievit** [comment]
I'll close it due to no response, feel free to reopen if the issue persists!
