### ISSUE TITLE
[Feature]: Filemoon, Vidplay, MyCloud

### ISSUE THREAD

**Issue by DigitalCorrosion** [movie-web/movie-web#989]
### What feature do you want to add?

I frequent a site (until I found movie-web) that always has these links and they work. Was not sure if you have had these before or not but just an idea. The website I'm referencing is watch32.id

Not sure what it is a knockoff of but it always has everything I've searched for. 

### Why do you want to have this feature?

More sources available. 

### Any other details to share?

That wraps it up!

**Comment by JorrinKievit** [comment]
This embeds VidSrcTo, which we already have as a source, see #393
