### ISSUE TITLE
[Bug]: Cannot use custom proxy while the chrome extension is disabled

### ISSUE THREAD

**Issue by bob4444-test** [movie-web/movie-web#991]
### What happened?

When I attempted to watch a movie/tv show on my selfhosted movie-web, I get the error:
'We couldn't find that'.
When I click Show details, I see:
'Error: extension error: _blahblahblah_.vercel.app is not whitelisted. Open the extension and click on the power button to whitelist the site.' 
When I try to play the movie on a browser that has not downloaded the extension it works perfectly.

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Steps to reproduce?

1. Navigate to your selfhosted movie-web instance.
2. Add a custom proxy to it.
3. Download the Movie-web chrome extension.
4. Disable the Movie-web chrome extension on the page of your instance.
5. Watch as no movie or tv shows works on the browser that you installed the now disabled movie web extension.
6. Open a broswer that does not have the extension downloaded.
7. Watch as the custom proxy does its job and works.

**Comment by JorrinKievit** [comment]
I'm not sure I get it. This is the desired result right? If you don't whitelist the site on the extension, it won't work. It won't fallback to the proxy.

**Comment by TheScreechingBagel** [comment]
that’s expected behaviour, you gotta enable the extension?

**Comment by bob4444-test** [comment]
> I'm not sure I get it. This is the desired result right? If you don't whitelist the site on the extension, it won't work. It won't fallback to the proxy.

Why not? Shouldn't it use the proxy if the extension is disabled?

**Comment by castdrian** [comment]
Why would you install the extension if you're not turning it on, hence why should it ignore the fact that it's disabled

**Comment by bob4444-test** [comment]
> Why would you install the extension if you're not turning it on, hence why should it ignore the fact that it's disabled

In my case, I was trying to test if the custom proxy was working. (So I could use move-web on my phone)
I expected movie-web to switch to using custom proxy after I disabled the extension, but instead movie-web told me to enable the extension.

**Comment by binaryoverload** [comment]
Custom proxies can be tested using the /admin page, other than that I don't know of a use case where you would install the extension but not use it
