### ISSUE TITLE
[Feature]: Add provider to the URL when loaded

### ISSUE THREAD

**Issue by Dinesh-Gautam** [movie-web/movie-web#996]
### What feature do you want to add?

When a provider is loaded/changed, add the provider ID to the URL
something like this,
`.../media/tmdb-tv-1402-the-walking-dead/3643/63339?provider=provider_id`

### Why do you want to have this feature?

- Whenever I reload the page, the providers are loaded again. Instead, if the provider info is given in the URL, the page can simply load that provider if available.
- Links can be shared with provider info, so the person the link is shared with does not have to wait for all the providers to load only to find out the last provider works.

**Comment by castdrian** [comment]
duplicate https://github.com/movie-web/movie-web/issues/406

**Comment by binaryoverload** [comment]
duplicate https://github.com/movie-web/movie-web/issues/406
