### ISSUE TITLE
[Bug]: Not getting stream links with providers

### ISSUE THREAD

**Issue by fsmdeveloper** [movie-web/movie-web#997]
### What happened?

for some movies, I'm getting this error. is there any solution or any option to skip specific sources? I want to skip Goojara/DoodStream. please help me with this issue. I'm using the NestJS framework (Nodejs).

```
{
    "sourceId": "goojara",
    "embedId": "dood",
    "stream": {
        "id": "primary",
        "type": "file",
        "flags": [],
        "captions": [],
        "qualities": {
            "unknown": {
                "type": "mp4",
                "url": "<!doctype html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"utf-8\">\n   <h1>Oops! Sorry</h1>\n                <p>File you are looking for is not found.</p>\n"
                }
 }
        },
        "headers": {
            "Referer": "https://d0000d.com/"
        }
    }
```

### Steps to reproduce?

I'm using the NestJS framework (Nodejs).

**Comment by JorrinKievit** [comment]
Thats a bug in the providers library. It should not return an entry for goojara at all with an URL like that

**Comment by JorrinKievit** [comment]
You can select the providers to scrape with this setting https://movie-web.github.io/providers/essentials/customize-providers#adding-only-select-few-providers

**Comment by fsmdeveloper** [comment]
Thank you so much bro. please fix this issue soon as possible!! I love this project and provider package!  😍😍
